### ISSUE TITLE
:param field atribute clash with signatures parameters

### ISSUE THREAD

**Issue by joaquinferrero** [Perl/perl5#21497] opened 2023-09-19 12:20 UTC
**Description**
The presence of the attribute **:param** in one of the fields in the definition of a class generates an error "_Subroutine attributes must come before the signature_" if such definition occurs after the declaration of a subroutine with a signature with parameters.

**Steps to Reproduce**

This work perfectly:
```
#!/usr/bin/env perl
use v5.38;

use feature 'class';
no warnings 'experimental::class';

## - Create class
class Point {
    field $x :param;            # <= Bug?
    field $y;

    method zero { $x = $y = 0; }
    method x    { $x }
}


## - Functions/Subroutines
sub no_params { say "No params" }

sub with_params($param1, $param2) {
    say "Param1: $param1";
    say "Param2: $param2";
}


#my $punto = Point->new;
my $punto = Point->new(x => 42);
say ".x : ", $punto->x;                         # 42


##
&no_params;
&with_params(41, 2);

__END__
```
But this don't work:
```
#!/usr/bin/env perl
use v5.38;

use feature 'class';                            # A partir de Perl v5.38
no warnings 'experimental::class';

## - Functions/Subroutines
sub no_params { say "No params" }

sub with_params($param1, $param2) {
    say "Param1: $param1";
    say "Param2: $param2";
}


## - Create class
class Point {
    field $x :param;            # <= Bug?
    field $y;

    method zero { $x = $y = 0; }
    method x    { $x }
}


#my $punto = Point->new;
my $punto = Point->new(x => 42);
say ".x : ", $punto->x;                         # 42


##
&no_params;
&with_params(41, 2);

__END__
```
Error: Subroutine attributes must come before the signature at fallo_class.pl line 18.

If the attribute :param is removed, it works without errors:
```
    field $x;   # removed :param
    ...
my $punto = Point->new;
$punto->zero;
```

**Expected behavior**
The expected result should be the same output, regardless of order in which the definitions of classes and subroutines are found.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 38 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=3.13.0-37-generic
    archname=x86_64-linux
    uname='linux arcanus 3.13.0-37-generic #64-ubuntu smp mon sep 22 21:28:38 utc 2014 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/explorer/perl5/perlbrew/perls/perl-5.38.0 -Aeval:scriptdir=/home/explorer/perl5/perlbrew/perls/perl-5.38.0/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-std=gnu99 -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-std=gnu99 -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion=''
    gccversion='4.8.5'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.19'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Jul  4 2023 16:13:14
  %ENV:
    PERL5LIB="/home/explorer/perl5/lib/perl5"
    PERLBREW_HOME="/home/explorer/.perlbrew"
    PERLBREW_MANPATH="/home/explorer/perl5/perlbrew/perls/perl-5.38.0/man"
    PERLBREW_PATH="/home/explorer/perl5/perlbrew/bin:/home/explorer/perl5/perlbrew/perls/perl-5.38.0/bin"
    PERLBREW_PERL="perl-5.38.0"
    PERLBREW_ROOT="/home/explorer/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.97"
    PERLBREW_VERSION="0.97"
    PERLDOC_POD2="1"
  @INC:
    /home/explorer/perl5/lib/perl5
    /home/explorer/perl5/perlbrew/perls/perl-5.38.0/lib/site_perl/5.38.0/x86_64-linux
    /home/explorer/perl5/perlbrew/perls/perl-5.38.0/lib/site_perl/5.38.0
    /home/explorer/perl5/perlbrew/perls/perl-5.38.0/lib/5.38.0/x86_64-linux
    /home/explorer/perl5/perlbrew/perls/perl-5.38.0/lib/5.38.0
```

**Comment by leonerd** [comment] 2023-09-19 12:29
Duplicate of #21158 which was fixed by #21159. Too late to get into 5.38.0 but it's in the 5.39 development series.

**Closed as not planned by leonerd** 2023-09-19 12:29 UTC
Labels: Needs Triage
