### ISSUE TITLE
Inconsistent use of parenthesis in map when loading hashes

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21602] opened 2023-10-29 23:25 UTC
In the following the assignment to **%b** works as expected  but the almost identical assignment to **%B** generates a syntax error.  May I urge that the two assignments should work in the same way to minimize surprise?

```
use v5.34;

my %a = map {($_=>0)} 1..3;
my %b = map { $_=>0 } 1..3;

my %A = map {("a$_"=>0)} 1..3;
my %B = map { "a$_"=>0 } 1..3;  # syntax error near "} 1"
```

**Comment by tonycoz** [comment] 2023-10-29 23:43
It is a documented behaviour, see the end of `perldoc -f map`.

Changing it would break existing code.  In some cases I think silently.

The problem is an ambiguity in the grammar: is a `{` after a map the start of a hashref in `map EXPR, LIST` or is it the start of BLOCK in `map BLOCK LIST`.

It might be there will be a `listopexpr` feature in the future that disables the EXPR versions of grep and map when disabled, which would remove the ambiguity.

**Comment by Grinnz** [comment] 2023-10-30 02:31
Duplicate of https://github.com/Perl/perl5/issues/14781, https://github.com/Perl/perl5/issues/14195

**Closed as completed** 2023-11-07 02:09 UTC

**Comment by guest20** [comment] 2023-11-07 15:22
@philiprbrenan You can also use `map +{ ... }, ...` or `map {; ...} ...` to clarify to the reader/parser what you're hoping for.
