### ISSUE TITLE
BBC: Blead breaks ADAMK/Devel-Dumpvar-1.06.tar.gz

### ISSUE THREAD

**Issue by andk** [Perl/perl5#20345] opened 2022-09-23 19:54 UTC
**Description**

Starting with v5.37.3-114-gc74a928a43 tests are failing for ADAMK/Devel-Dumpvar-1.06.tar.gz

Sample fail report: http://www.cpantesters.org/cpan/report/a6fce3b4-39d7-11ed-9c39-ec949d66406b

Git bisect for this fail lead me to

``` text
commit c74a928a43322c574522f122a3f3a29262f90613
Author: Richard Leach <rich+perl@hyphen-dash-hyphen.info>
Date:   Sun Aug 7 23:34:42 2022 +0000

    Add OPpTARGET_MY optimization to OP_UNDEF
```

**Steps to Reproduce**

cpan -i ADAMK/Devel-Dumpvar-1.06.tar.gz

**Expected behavior**

Should build, test and install the pkg

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 37 subversion 4) configuration:
  Commit id: f2582f5b18658f945a763f2edc110cdc7c5220e7
  Platform:
    osname=linux
    osvers=5.4.0-125-generic
    archname=x86_64-linux-thread-multi
    uname='linux k93focal 5.4.0-125-generic #141-ubuntu smp wed aug 10 13:42:03 utc 2022 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.4/d119 -Dmyhostname=k93focal -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Uuselongdouble -DEBUGGING=both'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Sep 21 2022 03:04:18
  %ENV:
    PERL5LIB="/tmp/loop_over_bdir-2945421-pdrHb6/Linux-InitFS-0.2-0/blib/arch:/tmp/loop_over_bdir-2945421-pdrHb6/Linux-InitFS-0.2-0/blib/lib:/tmp/loop_over_bdir-2945421-pdrHb6/ProjectBuilder-0.14.1-0/blib/arch:/tmp/loop_over_bdir-2945421-pdrHb6/ProjectBuilder-0.14.1-0/blib/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="2945431"
    PERL5_CPAN_IS_RUNNING="2945431"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /tmp/loop_over_bdir-2945421-pdrHb6/Linux-InitFS-0.2-0/blib/arch
    /tmp/loop_over_bdir-2945421-pdrHb6/Linux-InitFS-0.2-0/blib/lib
    /tmp/loop_over_bdir-2945421-pdrHb6/ProjectBuilder-0.14.1-0/blib/arch
    /tmp/loop_over_bdir-2945421-pdrHb6/ProjectBuilder-0.14.1-0/blib/lib
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.4/d119/lib/site_perl/5.37.4/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.4/d119/lib/site_perl/5.37.4
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.4/d119/lib/5.37.4/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.4/d119/lib/5.37.4
    .
```

**Comment by richardleach** [comment] 2022-09-23 20:07
This looks to have been fixed in blead today via https://github.com/Perl/perl5/commit/22d01053ed299e489bfee2839fb35dfeece9d1fb.

The failing test in _Devel::Dumpvar_ creates multiple objects via the syntax:
`bless( do{\(my $o = undef)}`
which was the original problem in #20336 and what the above commit was intended to fix.

**Comment by jkeenan** [comment] 2022-09-23 22:02
Confirmed; closing ticket.
```
$ ./bin/perl -v | head -2 | tail -1;./bin/perl -MDevel::Dumpvar -E 'say q|hello
world|'
This is perl 5, version 37, subversion 5 (v5.37.5 (v5.37.4-22-g92ee38c43e)) built for amd64-freebsd-thread-multi
hello world
```

**Closed as completed by jkeenan** 2022-09-23 22:02 UTC
Labels: BBC, Closable?
