### ISSUE TITLE
feature 'class': out of memory error if subclassing a class with an explicit new

### ISSUE THREAD

**Issue by djerius** [Perl/perl5#22491] opened 2024-08-08 20:09 UTC
**Description**

While poking at Class to see how one might create a virtual class which can't be instantiated, I tried adding a `new` which would die to the parent class (I understand that this is explicitly advised against in the documentation):

Foo.pm:
```
use feature 'class';
class Foo {
    sub new { ... }
}
1;
```
Bar.pm:
```
use feature 'class';
class Bar : isa(Foo) { }
1;
```
with the result:
```
$ perl -I. Bar.pm
class is experimental at Bar.pm line 5.
class is experimental at Foo.pm line 5.
Out of memory in perl:util:safesyscalloc
```

**Expected behavior**

I expected that Perl would scold me for defining `new`, but I was hoping it would just make the parent class non-instantiable.

**Perl configuration**

```

Summary of my perl5 (revision 5 version 40 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=6.9.7+bpo-amd64
    archname=x86_64-linux
    uname='linux leafhopper 6.9.7+bpo-amd64 #1 smp preempt_dynamic debian 6.9.7-1~bpo12+1 (2024-07-03) x86_64 gnulinux '
    config_args='-Dprefix=/home/dj/.plenv/versions/5.40 -de -Dversiononly -A'eval:scriptdir=/home/dj/.plenv/versions/5.40/bin''
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='12.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.36'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Aug  5 2024 00:46:42
  %ENV:
    PERL_CPANM_OPT="--cascade-search --mirror-only  --mirror /home/dj/Work/darkpan --mirror http://www.cpan.org"
    PERL_CPAN_MIRROR_TINY_BASE="/home/dj/Work/darkpan"
    PERL_DARKPAN="/home/dj/Work/darkpan"
  @INC:
    /home/dj/.plenv/versions/5.40/lib/perl5/site_perl/5.40.0/x86_64-linux
    /home/dj/.plenv/versions/5.40/lib/perl5/site_perl/5.40.0
    /home/dj/.plenv/versions/5.40/lib/perl5/5.40.0/x86_64-linux
    /home/dj/.plenv/versions/5.40/lib/perl5/5.40.0

```

**Comment by mauke** [comment] 2024-08-08 21:06
Seems to be fixed in blead.
Bisect says 39dd28f9eafb1932132c9d1099532d371c913923 is the commit that fixed it.

**Comment by djerius** [comment] 2024-08-08 21:14
Thanks. 
FWIW, I've settled on the somewhat clunky:

```
    ADJUST {
        require Carp;
        Carp::croak("can't instantiate @{[__PACKAGE__]}") if __CLASS__ eq __PACKAGE__;
    }
```

**Comment by jkeenan** [comment] 2024-08-09 20:54
> Seems to be fixed in blead. Bisect says [39dd28f](https://github.com/Perl/perl5/commit/39dd28f9eafb1932132c9d1099532d371c913923) is the commit that fixed it.

Confirmed.
```
$ ./bin/perl -v | head -2 | tail -1
This is perl 5, version 41, subversion 3 (v5.41.3 (v5.41.2-239-g2c387e63ae)) built for x86_64-linux-thread-multi

$ cat Foo.pm; echo ''; cat Bar.pm
use feature 'class';
class Foo {
    sub new { ... }
}
1;

use feature 'class';
class Bar : isa(Foo) { }
1;

$ ./bin/perl -Ilib -I. Bar.pm
class is experimental at Bar.pm line 2.
class is experimental at Foo.pm line 2.
```
Closing.  Thanks.

**Closed as completed by jkeenan** 2024-08-09 20:54 UTC
