### ISSUE TITLE
Cannot build 5.32.0 on macOS 11.1 in DynaLoader.t

### ISSUE THREAD

**Issue by sparvu** [Perl/perl5#18499] opened 2021-01-20 16:12 UTC
I am trying to build perl 5.32.0 on latest Apple M1 laptop. After patching, to pass this https://github.com/Perl/perl5/issues/18119 I was able to get to make test but ended up with different errors. Anyone been able too build latest 5.32.0 on latest macOS? This happens on x64 / M1.

```
...
ext/B/t/walkoptree ............................................. ok
ext/B/t/xref ................................................... ok
ext/Devel-Peek/t/Peek .......................................... ok
ext/DynaLoader/t/DynaLoader .................................... # Failed test 20 - array should contain one result or more: libc => () at t/DynaLoader.t line 127
#      got "0"
# expected >= "1"
FAILED at test 20
ext/Errno/t/Errno .............................................. ok
ext/Fcntl/t/autoload ........................................... ok
ext/Fcntl/t/fcntl .............................................. ok
...
t/porting/maintainers .......................................... ok
t/porting/manifest ............................................. ok
t/porting/pending-author ....................................... skipped
t/porting/perlfunc ............................................. ok
t/porting/pod_rules ............................................ ok
t/porting/podcheck ............................................. ok
t/porting/re_context ........................................... ok
t/porting/readme ............................................... ok
t/porting/regen ................................................ ok
t/porting/ss_dup ............................................... ok
t/porting/test_bootstrap ....................................... ok
t/porting/utils ................................................ skipped
Failed 1 test out of 2467, 99.96% okay.
	../ext/DynaLoader/t/DynaLoader.t
### Since not all tests were successful, you may want to run some of
### them individually and examine any diagnostic messages they produce.
### See the INSTALL document's section on "make test".
### You have a good chance to get more information by running
###   ./perl harness
### in the 't' directory since most (>=80%) of the tests succeeded.
### You may have to set your dynamic library search path,
### DYLD_LIBRARY_PATH, to point to the build directory:
###   setenv DYLD_LIBRARY_PATH `pwd`; cd t; ./perl harness
###   DYLD_LIBRARY_PATH=`pwd`; export DYLD_LIBRARY_PATH; cd t; ./perl harness
###   export DYLD_LIBRARY_PATH=`pwd`; cd t; ./perl harness
### for csh-style shells, like tcsh; or for traditional/modern
### Bourne-style shells, like bash, ksh, and zsh, respectively.
Elapsed: 609 sec
u=2.59  s=1.93  cu=259.08  cs=25.68  scripts=2467  tests=1208216
make: *** [test] Error 1
```

**Description**
Cannot build perl 5.32.0 on latest macOS 11.1 (x64 / M1)

**Steps to Reproduce**
Get latest distribution 5.32.0 and try to build on macOS 11.1 x64 or M1

**Expected behavior**
Should be able to build on latest macOs release

**Errors

**Perl configuration**

```
% ./perl -V
Can't locate Config.pm in @INC (you may need to install the Config module) (@INC contains: /opt/kronometrix/lib/perl5/site_perl/5.32.0/darwin-2level /opt/kronometrix/lib/perl5/site_perl/5.32.0 /opt/kronometrix/lib/perl5/5.32.0/darwin-2level /opt/kronometrix/lib/perl5/5.32.0).
BEGIN failed--compilation aborted.

```

**Comment by Leont** [comment] 2021-01-20 16:16
This is a duplicate of #18407. Yes it's known, and it's fixed in the soon to be released 5.32.1 (and patchperl)

**Closed as completed by Leont** 2021-01-20 16:16 UTC
Labels: Needs Triage

**Comment by sparvu** [comment] 2021-01-20 16:41
cool. thank you, waiting 5.32.1

**Comment by Leont** [comment] 2021-01-23 15:28
> cool. thank you, waiting 5.32.1

It has just been released :-)

**Comment by sparvu** [comment] 2021-01-23 17:35
Cooool. Thanks a lot for headsup
