### ISSUE TITLE
 Illegal character in prototype for ? : 1 when using sub as a subroutine name

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21614] opened 2023-11-04 05:30 UTC
Using **sub** as a subroutine name produces surprising messages as shown below.  May I urge that **sub** should be a  permissible as a subroutine name?
 
```
use v5.34;

sub sub($) {1}
sub(1);     # Illegal character in prototype for ? : 1 
            # Illegal declaration of anonymous subroutine 
```

**Comment by Grinnz** [comment] 2023-11-04 05:58
No, because it is already a keyword, in expression context it declares an anonymous subroutine (hence the error message).

**Comment by mauke** [comment] 2023-11-04 07:59
I don't see what's so urgent about this. (Also, IMHO this is a duplicate of #21613).

**Comment by mauke** [comment] 2023-11-04 08:27
Here's an example that would silently parse differently under this change:
```perl
my $x = rand() < .5 ? sub() : foo(q:) { 2 } : %q; #;);
```
Currently `foo(q:)` is parsed as a subroutine attribute and the statement is parsed as:
```perl
my $x = (
    (rand() < 0.5)
        ? sub () :foo(q:) { 2; }  # anonymous subroutine with prototype and attributes
        : %q
);
```
If we changed the meaning of `sub`, it would instead be parsed like this:
```perl
my $x = (
    (rand() < 0.5)
        ? &sub()  # a subroutine call
        : foo(') { 2 } ' % ' #')  # also a subroutine call
);
```

At minimum we would need solid rules for when `sub` is to be parsed as a subroutine call and when it is supposed to act as a keyword. The presence of `sub (` is insufficient to disambiguate, due to the existence of prototypes (in old code) and "signatures" (parameter lists) (in new code).
But any such rule would necessarily be brittle, I think, adding a lot of complexity to Perl's syntax with little benefit. I don't like it.

**Comment by jkeenan** [comment] 2023-11-16 01:29
@mauke and @Grinnz have provided good reasons why we should not make changes in this area.  Closing.

**Closed as completed by jkeenan** 2023-11-16 01:29 UTC
