### ISSUE TITLE
[doc] typo in perl-5.40.0/lib/DB.pm

### ISSUE THREAD

**Issue by sobrado8086** [Perl/perl5#22742] opened 2024-11-13 16:01 UTC
**Where**

There is a typo in DB.pm; report closed by mistake while editing, a few minutes ago.

**Description**

See attached diff.
[DB.pm.patch](https://github.com/user-attachments/files/17735421/DB.pm.patch)

**Comment by mauke** [comment] 2024-11-13 21:20
Duplicate of #22732.

**Closed as not planned by mauke** 2024-11-13 21:20 UTC
Labels: Needs Triage, documentation
