### ISSUE TITLE
BBC: DANKOGAI/Unicode-Char-0.02.tar.gz fails since perl 5.31.10

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#17766] opened 2020-05-01 07:41 UTC
Overview of reports: http://matrix.cpantesters.org/?dist=Unicode-Char%200.02
A sample fail report: http://www.cpantesters.org/cpan/report/cfe68422-8a5e-11ea-a0ef-2c341f24ea8f

**Comment by jkeenan** [comment] 2020-05-01 13:20
> Overview of reports: http://matrix.cpantesters.org/?dist=Unicode-Char%200.02
> A sample fail report: http://www.cpantesters.org/cpan/report/cfe68422-8a5e-11ea-a0ef-2c341f24ea8f

Bisection:
```
perl Porting/bisect.pl --start=v5.31.9 --end=v5.31.10 --module=Unicode::Char
```
... points to:
```
b555069b72f93a232deba173dc7bf7892cfa5868 is the first bad commit
commit b555069b72f93a232deba173dc7bf7892cfa5868
Author: Karl Williamson <khw@cpan.org>
Date:   Thu Feb 13 09:04:41 2020 -0700

    Reformat lib/unicore/Name.pl
    
    This changes the format of this generated file so that it can more
    easily be used with the Unicode Name property in wildcard matching.
    
    Each line will now end with \n\n, and the \t characters are replaced by
    \n.  Thus an entry will look like
    
    00001\nSTART OF HEADING\n\n
    
    This makes matching of user-defined patterns using anchors work under
    /m, which commit 4829f32decd128e6a122bd8ce35fe944bd87f104 forces.  That
    commit also changed some anchors' defintions to make them match \n under
    /m with wildcards, so this makes it all transparent to user patterns.
    
    The double \n\n at the end of an entry is so that the code can
    distinguish between a line that contains a code point vs a name without
    relying on the content; it is a disambiguator, like the \t that used to
    be.
```
@khwilliamson, can you take a look?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment] 2020-05-01 13:41
On 5/1/20 7:20 AM, James E Keenan wrote:
>     Overview of reports:
>     http://matrix.cpantesters.org/?dist=Unicode-Char%200.02
>     A sample fail report:
>     http://www.cpantesters.org/cpan/report/cfe68422-8a5e-11ea-a0ef-2c341f24ea8f
> 
> Bisection:
> 
> |perl Porting/bisect.pl --start=v5.31.9 --end=v5.31.10 
> --module=Unicode::Char |
> 
> ... points to:
> 
> |b555069b72f93a232deba173dc7bf7892cfa5868 is the first bad commit commit 
> b555069b72f93a232deba173dc7bf7892cfa5868 Author: Karl Williamson 
> <khw@cpan.org> Date: Thu Feb 13 09:04:41 2020 -0700 Reformat 
> lib/unicore/Name.pl This changes the format of this generated file so 
> that it can more easily be used with the Unicode Name property in 
> wildcard matching. Each line will now end with \n\n, and the \t 
> characters are replaced by \n. Thus an entry will look like 00001\nSTART 
> OF HEADING\n\n This makes matching of user-defined patterns using 
> anchors work under /m, which commit 
> 4829f32decd128e6a122bd8ce35fe944bd87f104 forces. That commit also 
> changed some anchors' defintions to make them match \n under /m with 
> wildcards, so this makes it all transparent to user patterns. The double 
> \n\n at the end of an entry is so that the code can distinguish between 
> a line that contains a code point vs a name without relying on the 
> content; it is a disambiguator, like the \t that used to be. |
> 
> @khwilliamson <https://github.com/khwilliamson>, can you take a look?
> 

I have looked at it.  The file lib/Unicode/Char.pm contains the line

     my $name_pl = do 'unicore/Name.pl'; # famous cheat;

Name.pl has long contained the text:

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice. 
Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.

So, the module is using an internal-only file, which its comment 
indicates it shouldn't be.

**Comment by khwilliamson** [comment] 2020-05-01 15:25
> So, the module is using an internal-only file, which its comment
indicates it shouldn't be.

I should have said, the comment indicates the module is aware it shouldn't be doing this.
The proper way to do what the module wants is to use `Unicode::UCD::prop_invmap(),` available since 5.16.  The pod for that even has the complete recipe written out for this situation

>    Getting every available name
    Instead of reading the Unicode Database directly from files, as you were able to do for a long time, you are encouraged to use the supplied functions. So, instead of reading
    "Name.pl" - which may disappear without notice in the future - directly, as with

      my (%name, %cp);
      for (split m/\s*\n/ => do "unicore/Name.pl") {
          my ($cp, $name) = split m/\t/ => $_;
          $cp{$name} = $cp;
          $name{$cp} = $name unless $cp =~ m/ /;
      }

    You ought to use "prop_invmap()" like this:

      my (%name, %cp, %cps, $n);
      # All codepoints
      foreach my $cat (qw( Name Name_Alias )) {
          my ($codepoints, $names, $format, $default) = prop_invmap($cat);
          # $format => "n", $default => ""
          foreach my $i (0 .. @$codepoints - 2) {
              my ($cp, $n) = ($codepoints->[$i], $names->[$i]);
              # If $n is a ref, the same codepoint has multiple names
              foreach my $name (ref $n ? @$n : $n) {
                  $name{$cp} //= $name;
                  $cp{$name} //= $cp;
              }
          }
      }
      # Named sequences
      {   my %ns = namedseq();
          foreach my $name (sort { $ns{$a} cmp $ns{$b} } keys %ns) {
              $cp{$name} //= [ map { ord } split "" => $ns{$name} ];
          }
      }

**Comment by xsawyerx** [comment] 2020-05-11 06:43
I consider this a non-blocker. The module author should have seen the warning and has an alternative.

**Comment by jkeenan** [comment] 2022-03-12 21:39
I created the following ticket in Unicode-Char's bug tracker:
https://rt.cpan.org/Ticket/Display.html?id=141734

This is a non-blocker.

**Comment by dankogai** [comment] 2022-03-19 05:40
It is now fixed. 

https://github.com/dankogai/p5-unicode-char/commit/26cd17546bc34855f7d40122e395fb14cb5b4c99

I also resolved the corresponding RT.

**Comment by jkeenan** [comment] 2022-03-19 12:01
> It is now fixed.
> 
> [dankogai/p5-unicode-char@26cd175](https://github.com/dankogai/p5-unicode-char/commit/26cd17546bc34855f7d40122e395fb14cb5b4c99)
> 
> I also resolved the corresponding RT.

Confirmed.  Thanks for your investigation.

**Closed as completed by jkeenan** 2022-03-19 12:01 UTC
Labels: BBC
