### ISSUE TITLE
MacOS 11.3.1, -Duseshrplib -Dusesitecustomize results in a t/porting/libperl test failure

### ISSUE THREAD

**Issue by neilb** [Perl/perl5#18996] opened 2021-07-22 23:04 UTC
**Description**

I'm working on the 5.35.2 dev release. The release manager's guide (RMG) says to try various Configure options, so I ran:

    $ ./Configure -des -Dusedevel -Duseshrplib -Dusesitecustomize

This resulted in 1 failed test: t/porting/libperl

```
t/porting/libperl ................................................ porting/libperl.t: undefined current object: 000000000016d370 (__TEXT,__text) external _ASCII_TO_NEED at porting/libperl.t line 242, <$nm_fh> line 1.
FAILED--no leader found
```

This is on MacOS 11.3.1 (2.5 GHz Quad-Core Intel Core i7)

**Comment by jkeenan** [comment] 2021-07-23 00:58
On 7/22/21 7:04 PM, Neil Bowers wrote:
> *Description*
> 
> I'm working on the 5.35.2 dev release. The release manager's guide (RMG) 
> says to try various Configure options, so I ran:
> 
> |$ ./Configure -des -Dusedevel -Duseshrplib -Dusesitecustomize |
> 

Are you able to determine which of these options (or both) is associated 
with the test failure?

> This resulted in 1 failed test: t/porting/libperl
> 
> |t/porting/libperl ................................................ 
> porting/libperl.t: undefined current object: 000000000016d370 
> (__TEXT,__text) external _ASCII_TO_NEED at porting/libperl.t line 242, 
> <$nm_fh> line 1. FAILED--no leader found |
> 
> This is on MacOS 11.3.1
>

**Comment by jkeenan** [comment] 2021-07-23 01:12
> **Description**
> 
> I'm working on the 5.35.2 dev release. The release manager's guide (RMG) says to try various Configure options, so I ran:
> 
> ```
> $ ./Configure -des -Dusedevel -Duseshrplib -Dusesitecustomize
> ```
> 
> This resulted in 1 failed test: t/porting/libperl
> 
> ```
> t/porting/libperl ................................................ porting/libperl.t: undefined current object: 000000000016d370 (__TEXT,__text) external _ASCII_TO_NEED at porting/libperl.t line 242, <$nm_fh> line 1.
> FAILED--no leader found
> ```
> 
> This is on MacOS 11.3.1 (2.5 GHz Quad-Core Intel Core i7)

Caveat:  I've never configured with either `-Duseshrplib` or `-Dusesitecustomize` and couldn't define them for you (without looking them up in `INSTALL`).

I configured and built with those options on FreeBSD-12 and Debian Linux.  On both, `t/porting/libperl.t` is `skipped: no libperl.a`.  This is surprising, because it suggests that the test program should be run on both of those OSes.

**Comment by jkeenan** [comment] 2021-07-23 01:17
More data:  At blead on FreeBSD, I get:
```
$ ./perl -Ilib t/porting/libperl.t
ld-elf.so.1: /usr/home/jkeenan/gitwork/perl/perl: Undefined symbol "PL_exit_flags"
```
On Linux I get:
```
$ ./perl -Ilib t/porting/libperl.t
./perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory

```

**Comment by jkeenan** [comment] 2021-07-23 01:35
> More data: At blead on FreeBSD, I get:
> 
> ```
> $ ./perl -Ilib t/porting/libperl.t
> ld-elf.so.1: /usr/home/jkeenan/gitwork/perl/perl: Undefined symbol "PL_exit_flags"
> ```
> 
> On Linux I get:
> 
> ```
> $ ./perl -Ilib t/porting/libperl.t
> ./perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
> ```

On both FreeBSD and Linux, when I configure **with** those options at tag `v5.34.0`, I get the same bad behavior as at HEAD (v5.35.1-126-ga876973).

On FreeBSD, when I configure **without** those two options, `t/porting/libperl.t` does not crash and is well behaved, *i.e.,* it does a skip all cleanly.
```
$ ./perl -Ilib t/porting/libperl.t
# $^O = freebsd
# $Config{archname} = amd64-freebsd-thread-multi
# $Config{cc} = cc
# libperl = ../libperl.a
# nm = /usr/bin/nm
# nm_style = gnu
# nm_opt = 
1..0 # Skip no GNU nm
```
On Debian Linux, when I also configure **without** those two options, `t/porting/libperl.t` also is well behaved.
```
$ ./perl -Ilib t/porting/libperl.t
# $^O = linux
# $Config{archname} = x86_64-linux
# $Config{cc} = cc
# libperl = ../libperl.a
# nm = /usr/bin/nm
# nm_style = gnu
# nm_opt = 
# command: "/usr/bin/nm  ../libperl.a 2>libperl21468 |"
ok 1 - has object pp.o
ok 2 - has text Perl_peep
ok 3 - has text Perl_pp_uc in pp.o
ok 4 - has data const symbols
ok 5 - has PL_no_mem
# nocommon = 0
ok 6 - has PL_hash_seed_w
ok 7 - has PL_ppaddr
ok 8 - has undefined symbols
ok 9 - uses chmod (doio.o)
ok 10 - uses dlopen (DynaLoader.o)
ok 11 - uses exp (pp.o)
ok 12 - uses getenv (DynaLoader.o locale.o perl.o perlio.o regcomp.o toke.o util.o)
ok 13 - uses sigaction (mg.o util.o)
ok 14 - uses socket (doio.o)
ok 15 - uses time (perl.o pp_sys.o util.o)
ok 16 - uses no atoi ()
ok 17 - uses no atol ()
ok 18 - uses no atoll ()
ok 19 - uses no fgets ()
ok 20 - uses no gets ()
ok 21 - uses no sprintf ()
ok 22 - uses no strcat ()
ok 23 - uses no strcpy ()
ok 24 - uses no strncat ()
ok 25 - uses no strncpy ()
ok 26 - uses no strtol ()
ok 27 - uses no strtoq ()
ok 28 - uses no strtoul ()
ok 29 - uses no system ()
ok 30 - uses no tmpfile ()
ok 31 - uses no vsprintf ()
ok 32 - no S_ exports
1..32
```
So those two options (or their combination) is problematic regardless of OS and is not a recently introduced problem.

**Comment by Leont** [comment] 2021-07-23 07:50
Did you do a proper `git clean` before compiling this perl? A useshrplib is supposed to skip that test, but the skip check is actually on the presence of a static libperl.

**Comment by jkeenan** [comment] 2021-07-23 21:45
> More data: At blead on FreeBSD, I get:
> 
> ```
> $ ./perl -Ilib t/porting/libperl.t
> ld-elf.so.1: /usr/home/jkeenan/gitwork/perl/perl: Undefined symbol "PL_exit_flags"
> ```
> 
> On Linux I get:
> 
> ```
> $ ./perl -Ilib t/porting/libperl.t
> ./perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
> ```

On both FreeBSD and Linux, when I configure **with** those options at tag `v5.34.0`, I get the same bad behavior as at HEAD (v5.35.1-126-ga876973).

On FreeBSD, when I configure **without** those two options, `t/porting/libperl.t` does not crash and is well behaved, *i.e.,* it does a skip all cleanly.
```
$ ./perl -Ilib t/porting/libperl.t
# $^O = freebsd
# $Config{archname} = amd64-freebsd-thread-multi
# $Config{cc} = cc
# libperl = ../libperl.a
# nm = /usr/bin/nm
# nm_style = gnu
# nm_opt = 
1..0 # Skip no GNU nm
```
On Debian Linux, when I also configure **without** those two options, `t/porting/libperl.t` also is well behaved.
```
$ ./perl -Ilib t/porting/libperl.t
# $^O = linux
# $Config{archname} = x86_64-linux
# $Config{cc} = cc
# libperl = ../libperl.a
# nm = /usr/bin/nm
# nm_style = gnu
# nm_opt = 
# command: "/usr/bin/nm  ../libperl.a 2>libperl21468 |"
ok 1 - has object pp.o
ok 2 - has text Perl_peep
ok 3 - has text Perl_pp_uc in pp.o
ok 4 - has data const symbols
ok 5 - has PL_no_mem
# nocommon = 0
ok 6 - has PL_hash_seed_w
ok 7 - has PL_ppaddr
ok 8 - has undefined symbols
ok 9 - uses chmod (doio.o)
ok 10 - uses dlopen (DynaLoader.o)
ok 11 - uses exp (pp.o)
ok 12 - uses getenv (DynaLoader.o locale.o perl.o perlio.o regcomp.o toke.o util.o)
ok 13 - uses sigaction (mg.o util.o)
ok 14 - uses socket (doio.o)
ok 15 - uses time (perl.o pp_sys.o util.o)
ok 16 - uses no atoi ()
ok 17 - uses no atol ()
ok 18 - uses no atoll ()
ok 19 - uses no fgets ()
ok 20 - uses no gets ()
ok 21 - uses no sprintf ()
ok 22 - uses no strcat ()
ok 23 - uses no strcpy ()
ok 24 - uses no strncat ()
ok 25 - uses no strncpy ()
ok 26 - uses no strtol ()
ok 27 - uses no strtoq ()
ok 28 - uses no strtoul ()
ok 29 - uses no system ()
ok 30 - uses no tmpfile ()
ok 31 - uses no vsprintf ()
ok 32 - no S_ exports
1..32
```
So those two options (or their combination) is problematic regardless of OS and is not a recently introduced problem.

> Did you do a proper `git clean` before compiling this perl? A useshrplib is supposed to skip that test, but the skip check is actually on the presence of a static libperl.

It's not clear whom you were replying to, but ... yes, I did `git clean -dfx` between builds.

**Comment by jkeenan** [comment] 2021-07-23 23:11
> 
> So those two options (or their combination) is problematic regardless of OS and is not a recently introduced problem.

Further experimentation shows that `-Duseshrplib` is sufficient to generate the failures on each of FreeBSD and Linux, with the error messages previously reported.

**Comment by jkeenan** [comment] 2021-07-23 23:39
> > So those two options (or their combination) is problematic regardless of OS and is not a recently introduced problem.
> 
> Further experimentation shows that `-Duseshrplib` is sufficient to generate the failures on each of FreeBSD and Linux, with the error messages previously reported.

On Linux, I tested at various tags as far back as v5.16.0, configuring with:
```
$ ./Configure -des -Dusedevel -Duseshrplib && make test_prep; ./perl -Ilib t/porting/libperl.t
```
In each case I got:
```
./perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
```

**Comment by Leont** [comment] 2021-07-24 11:47
> ./perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory

That is not a bug, that is expected. `LD_LIBRARY_PATH=$(pwd) ./perl -Ilib t/porting/libperl.t` OTOH should work

**Comment by jkeenan** [comment] 2021-07-24 14:50
> > ./perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
> 
> That is not a bug, that is expected. `LD_LIBRARY_PATH=$(pwd) ./perl -Ilib t/porting/libperl.t` OTOH should work

Or:
```
$ LD_LIBRARY_PATH=`pwd` ./perl -Ilib t/porting/libperl.t
1..0 # Skip no libperl.a
```
So now that we've cleared up some confusion on builds on FreeBSD and Linux, are there any issues remaining for the OP's problem on MacOS?

@neilb ^^

Thank you very much.
Jim Keenan

**Comment by Leont** [comment] 2021-07-24 18:16
> So now that we've cleared up some confusion on builds on FreeBSD and Linux, are there any issues remaining for the OP's problem on MacOS?

I suspect that the problem here is that it can fail if one didn't clean properly before rebuilding. It should either skip on `-Duseshrplib`, or it should handle shared libperls properly

**Comment by jkeenan** [comment] 2021-09-01 22:04
> > So now that we've cleared up some confusion on builds on FreeBSD and Linux, are there any issues remaining for the OP's problem on MacOS?
> 
> I suspect that the problem here is that it can fail if one didn't clean properly before rebuilding. It should either skip on `-Duseshrplib`, or it should handle shared libperls properly

There's been no further discussion in this ticket in over a month, so I'm closing it now.

**Closed as completed by jkeenan** 2021-09-01 22:04 UTC
Labels: Closable?
