### ISSUE TITLE
BBC File-Find-utf8-0.013

### ISSUE THREAD

**Issue by andk** [Perl/perl5#19427] opened 2022-02-16 03:58 UTC
**Description**

File-Find-utf8-0.013 has started to fail, bisect leads to https://github.com/Perl/perl5/commit/c108140682f
I have reported to the author at https://github.com/HayoBaan/File-Find-utf8/issues/3# but I failed to come up with advice for the author. Could somebody please chime in?

**Steps to Reproduce**

cpan -i File::Find::utf8

**Expected behavior**

Green according to http://matrix.cpantesters.org/?dist=File-Find-utf8+0.013

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 35 subversion 2) configuration:
  Commit id: c108140682f8d0b0bc5c8b1987fe2a72dde61f42
  Platform:
    osname=linux
    osvers=5.15.0-2-amd64
    archname=x86_64-linux-thread-multi-ld
    uname='linux k93msid 5.15.0-2-amd64 #1 smp debian 5.15.5-2 (2021-12-18) x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.1-39-gc108140682/8854 -Dmyhostname=k93msid -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Duselongdouble -DEBUGGING=-g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.33.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Feb 15 2022 17:45:21
  @INC:
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.1-39-gc108140682/8854/lib/site_perl/5.35.2/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.1-39-gc108140682/8854/lib/site_perl/5.35.2
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.1-39-gc108140682/8854/lib/5.35.2/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.1-39-gc108140682/8854/lib/5.35.2
```

**Comment by jkeenan** [comment] 2022-02-16 12:54
The issue is being discussed upstream at https://github.com/HayoBaan/File-Find-utf8/issues/3.

**Comment by jkeenan** [comment] 2022-02-21 13:34
[File-Find-utf8-0.014](https://metacpan.org/dist/File-Find-utf8/changes) was released to CPAN on 2022-02-16 and [addresses the problem](http://matrix.cpantesters.org/?dist=File-Find-utf8+0.014) raised in this ticket. Closing.

**Closed as completed by jkeenan** 2022-02-21 13:34 UTC
Labels: BBC
