### ISSUE TITLE
Time::HiRes build error, 'clockid_t' redefined, Mac OS Darwin 19.6.0 

### ISSUE THREAD

**Issue by i-am-al-x** [Perl/perl5#20362] opened 2022-09-29 19:36 UTC
While attempting `install Time::HiRes` from CPAN command line, I got the following error:

    `HiRes.xs:95:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')`

I am running Mac OS Darwin Kernel Version 19.6.0

Problem occurs during: 
    `CPAN.pm: Building A/AT/ATOOMIC/Time-HiRes-1.9764.tar.gz`

Compilation args and error messages are:
```
/usr/bin/perl /System/Library/Perl/5.18/ExtUtils/xsubpp  -typemap /System/Library/Perl/5.18/ExtUtils/typemap -typemap typemap  HiRes.xs > HiRes.xsc && mv HiRes.xsc HiRes.c
cc -c   -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"1.9764\" -DXS_VERSION=\"1.9764\"  -iwithsysroot "/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"  -DTIME_HIRES_NANOSLEEP -DTIME_HIRES_CLOCK_GETTIME -DTIME_HIRES_CLOCK_GETTIME_EMULATION -DTIME_HIRES_CLOCK_GETRES -DTIME_HIRES_CLOCK_GETRES_EMULATION -DTIME_HIRES_CLOCK_NANOSLEEP -DTIME_HIRES_CLOCK_NANOSLEEP_EMULATION -DUSE_PPPORT_H HiRes.c
**HiRes.xs:95:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')**
typedef int clockid_t;
            ^
**/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/incl**ude/time.h:172:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
```

**Comment by jkeenan** [comment] 2022-09-29 19:47
> While attempting `install Time::HiRes` from CPAN command line, I got the following error:
> 
> ```
> `HiRes.xs:95:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')`
> ```
> 
> I am running Mac OS Darwin Kernel Version 19.6.0
> 
> Problem occurs during: `CPAN.pm: Building A/AT/ATOOMIC/Time-HiRes-1.9764.tar.gz`
> 
> Compilation args and error messages are:
> 
> ```
> /usr/bin/perl /System/Library/Perl/5.18/ExtUtils/xsubpp  -typemap /System/Library/Perl/5.18/ExtUtils/typemap -typemap typemap  HiRes.xs > HiRes.xsc && mv HiRes.xsc HiRes.c
> cc -c   -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"1.9764\" -DXS_VERSION=\"1.9764\"  -iwithsysroot "/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"  -DTIME_HIRES_NANOSLEEP -DTIME_HIRES_CLOCK_GETTIME -DTIME_HIRES_CLOCK_GETTIME_EMULATION -DTIME_HIRES_CLOCK_GETRES -DTIME_HIRES_CLOCK_GETRES_EMULATION -DTIME_HIRES_CLOCK_NANOSLEEP -DTIME_HIRES_CLOCK_NANOSLEEP_EMULATION -DUSE_PPPORT_H HiRes.c
> **HiRes.xs:95:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')**
> typedef int clockid_t;
>             ^
> **/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/incl**ude/time.h:172:3: note: previous definition is here
> } clockid_t;
>   ^
> 1 error generated.
> ```
Am I correct in assuming that you are trying to install Time-HiRes-1.9764 against the "system perl" (`/usr/bin/perl`) on your machine?

Can you issue the following commands in your Terminal and paste the output?
```
$ uname -mrs

$ /usr/bin/perl -v

$ /usr/bin/perl -V:config_args
```
@atoomic, can you take a look at this ticket?  Thanks.

**Comment by i-am-al-x** [comment] 2022-09-29 20:20
% **uname -mrs**
Darwin 19.6.0 x86_64

% **which perl**    
/usr/bin/perl

% **/usr/bin/perl -v**
This is perl 5, version 18, subversion 4 (v5.18.4) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

% **/usr/bin/perl -V:config_args**
config_args='-ds -e -Dprefix=/usr -Dccflags=-g  -pipe  -Dldflags= -Dman3ext=3pm -Duseithreads -Duseshrplib -Dinc_version_list=none -Dcc=cc';

%

**Comment by Leont** [comment] 2022-09-29 22:59
That code should only be active if `has_clockid_t` in Makefile.PL fails. So the question is now "why does that fail?"

**Comment by tonycoz** [comment] 2022-09-30 03:26
Could you please try running the Time::HiRes Makefile.PL with VERBOSE=1, eg:
```
$ VERBOSE=1 cpan
...
cpan> test Time::HiRes
```
and show us the output from the beginning.

This should show the results of the configuration probes.

**Comment by i-am-al-x** [comment] 2022-09-30 17:25
% echo $SHELL        
/bin/zsh

% sudo VERBOSE=1 cpan
Terminal does not support AddHistory.

cpan shell -- CPAN exploration and modules installation (v2.00)
Enter 'h' for help.

cpan[1]> test Time::HiRes 
Reading '/Users/adanel/.cpan/Metadata'
  Database was generated on Thu, 29 Sep 2022 16:55:45 GMT
Running test for module 'Time::HiRes'
Running make for A/AT/ATOOMIC/Time-HiRes-1.9764.tar.gz
Checksum for /Users/adanel/.cpan/sources/authors/id/A/AT/ATOOMIC/Time-HiRes-1.9764.tar.gz ok
Scanning cache /Users/adanel/.cpan/build for sizes
............................................................................DONE

  CPAN.pm: Building A/AT/ATOOMIC/Time-HiRes-1.9764.tar.gz

Configuring Time::HiRes...
Have syscall()... looking for syscall.h... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
Looking for gettimeofday()... found.
Looking for setitimer()... found.
Looking for getitimer()... found.
You have interval timers (both setitimer and getitimer).
Looking for ualarm()... found.
Looking for usleep()... found.
Looking for nanosleep()... testing... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
Running ./tmp10736...found.
You can mix subsecond sleeps with signals, if you want to.
(It's still not portable, though.)
Looking for clockid_t... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found, will use int.
Looking for clock_gettime()... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
found (via emulation).
Looking for clock_getres()... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
found (via emulation).
Looking for clock_nanosleep()... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
found (via emulation).
Looking for clock()... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
Looking for working futimens()... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
Looking for working utimensat()... cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
You do NOT seem to have subsecond timestamp setting.
Looking for stat() subsecond timestamps...
Trying struct stat st_atimespec.tv_nsec...cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
Trying struct stat st_atimensec...cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
Trying struct stat st_atime_n...cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
Trying struct stat st_atim.tv_nsec...cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
Trying struct stat st_uatime...cccmd = cc -o tmp10736  -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DPERL_NO_INLINE_FUNCTIONS tmp10736.c  
tmp10736.c:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
NOT found.
You do NOT seem to have subsecond timestamp reading.
Checking if your kit is complete...
Looks good
Writing Makefile for Time::HiRes
Writing MYMETA.yml and MYMETA.json
Now you may issue 'make'.  Do not forget also 'make test'.
cp HiRes.pm blib/lib/Time/HiRes.pm
/usr/bin/perl /System/Library/Perl/5.18/ExtUtils/xsubpp  -typemap /System/Library/Perl/5.18/ExtUtils/typemap -typemap typemap  HiRes.xs > HiRes.xsc && mv HiRes.xsc HiRes.c
cc -c   -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"1.9764\" -DXS_VERSION=\"1.9764\"  -iwithsysroot "/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"  -DTIME_HIRES_NANOSLEEP -DTIME_HIRES_CLOCK_GETTIME -DTIME_HIRES_CLOCK_GETTIME_EMULATION -DTIME_HIRES_CLOCK_GETRES -DTIME_HIRES_CLOCK_GETRES_EMULATION -DTIME_HIRES_CLOCK_NANOSLEEP -DTIME_HIRES_CLOCK_NANOSLEEP_EMULATION -DUSE_PPPORT_H HiRes.c
HiRes.xs:95:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/time.h:172:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
make: *** [HiRes.o] Error 1
  ATOOMIC/Time-HiRes-1.9764.tar.gz
  /usr/bin/make -- NOT OK
'YAML' not installed, will not store persistent state
Running make test
  Can't test without successful make
Failed during this command:
 ATOOMIC/Time-HiRes-1.9764.tar.gz             : make NO

cpan[2]> quit
Terminal does not support GetHistory.
Lockfile removed.

%

**Comment by tonycoz** [comment] 2022-09-30 21:24
Please provide the full output from `perl -V`

It looks like the probes are using incorrect compilation flags,

**Comment by i-am-al-x** [comment] 2022-10-04 01:11
**% echo $SHELL**
/bin/zsh

**% perl -V**
Summary of my perl5 (revision 5 version 18 subversion 4) configuration:
   
  Platform:
    osname=darwin, osvers=19.0, archname=darwin-thread-multi-2level
    uname='darwin osx397.sd.apple.com 19.0 darwin kernel version 18.0.0: tue jul 9 11:12:08 pdt 2019; root:xnu-4903.201.2.100.7~1release_x86_64 x86_64 '
    config_args='-ds -e -Dprefix=/usr -Dccflags=-g  -pipe  -Dldflags= -Dman3ext=3pm -Duseithreads -Duseshrplib -Dinc_version_list=none -Dcc=cc'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags =' -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector',
    optimize='-Os',
    cppflags='-g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector'
    ccversion='', gccversion='4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-selector-opts)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector'
    libpth=/usr/lib /usr/local/lib
    libs= 
    perllibs=
    libc=, so=dylib, useshrplib=true, libperl=libperl.dylib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -fstack-protector'


Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                        PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP
                        PERL_PRESERVE_IVUV PERL_SAWAMPERSAND USE_64_BIT_ALL
                        USE_64_BIT_INT USE_ITHREADS USE_LARGE_FILES
                        USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
                        USE_REENTRANT_API
  Locally applied patches:
	/Library/Perl/Updates/<version> comes before system perl directories
	installprivlib and installarchlib points to the Updates directory
  Built under darwin
  Compiled at Jun  5 2020 17:34:07
  @INC:
    /Library/Perl/5.18/darwin-thread-multi-2level
    /Library/Perl/5.18
    /Network/Library/Perl/5.18/darwin-thread-multi-2level
    /Network/Library/Perl/5.18
    /Library/Perl/Updates/5.18.4/darwin-thread-multi-2level
    /Library/Perl/Updates/5.18.4
    /System/Library/Perl/5.18/darwin-thread-multi-2level
    /System/Library/Perl/5.18
    /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level
    /System/Library/Perl/Extras/5.18
    .
**%**

**Comment by tonycoz** [comment] 2022-10-06 00:46
I think I see what's happening here.  On most systems, adding the `-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE` is correct, but for some reason the preprocessor doesn't search that directory for headers and the probes fail.

We know the header is there - the Time::HiRes `Makefile.PL` checks that it exists.

EU::MM replaces that `-I...` flag with `-iwithsysroot ...` (see https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/blob/master/lib/ExtUtils/MM_Unix.pm#L143 and a few other places) which allows the compilation of the module itself to find `EXTERN.h`, but then of course it fails later because of the mismatch between the probe results and reality.

I think we need to do two things to fix this and make sure it's fixed:
1. extend the dist-modules test to test against the system perl on macos, and hopefully duplicate the failure
2. adapt the logic from EU::MM into the Time::HiRes probes, and hopefully fix the failure from 1.

**Comment by tonycoz** [comment] 2022-10-11 03:17
I've reproduced the duplicate clockid_t definition in CI..

ExtUtils::ParseXS seems to have a similar problem in finding EXTERN.h

**Comment by tonycoz** [comment] 2022-10-24 04:43
Fixed in blead

**Closed as completed by tonycoz** 2022-10-24 04:43 UTC

**Comment by i-am-al-x** [comment] 2022-10-25 17:56
As of today, Oct 25, I did 'clean' and 'install' and still got the error.  What do I need to get the "blead" version, with the fix?  Should I just wait for it to hit regular distribution?

**Comment by tonycoz** [comment] 2022-10-26 04:46
You can wait for it to be released to CPAN, or you could clone blead (from here), and copy `dist/Time-HiRes` to a new directory and install from that.
