### ISSUE TITLE
lexical_subs: cannot use to build use parameter

### ISSUE THREAD

**Issue by happy-barney** [Perl/perl5#21289] opened 2023-07-25 17:08 UTC
Example:
```
BEGIN {
  use feature q (lexical_subs);
  my sub build (...) { ... }

  use constant FOO => build (q (foo));
}
```

**Description**
Mentioned example ends-up with error
```
Undefined subroutine &foo called at /home/brano/a.pl line 5.
BEGIN failed--compilation aborted at /home/brano/a.pl line 5.
```

**Expected behavior**
It should be possible to use lexical subs to initialize use parameters.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 36 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=5.4.0-113-generic
    archname=x86_64-linux
    uname='linux happy-barney 5.4.0-113-generic #127-ubuntu smp wed may 18 14:30:56 utc 2022 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/brano/.cache/perlbrew/perls/perl-5.36 -Aeval:scriptdir=/home/brano/.cache/perlbrew/perls/perl-5.36/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib /lib64 /usr/lib64
    libs=-lpthread -lnsl -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Jun  3 2022 11:55:40
    PERL5LIB="/home/brano/lib/perl5/:/home/brano/lib/perl5/:/home/brano/lib/perl5/"
    PERLBREW_HOME="/home/brano/.perlbrew"
    PERLBREW_MANPATH="/home/brano/.cache/perlbrew/perls/perl-5.36/man"
    PERLBREW_PATH="/home/brano/.cache/perlbrew/bin:/home/brano/.cache/perlbrew/perls/perl-5.36/bin"
    PERLBREW_PERL="perl-5.36"
    PERLBREW_ROOT="/home/brano/.cache/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.86"
    PERLBREW_VERSION="0.88"
  @INC:
    /home/brano/lib/perl5/
    /home/brano/lib/perl5/
    /home/brano/lib/perl5/
    /home/brano/.cache/perlbrew/perls/perl-5.36/lib/site_perl/5.36.0/x86_64-linux
    /home/brano/.cache/perlbrew/perls/perl-5.36/lib/site_perl/5.36.0
    /home/brano/.cache/perlbrew/perls/perl-5.36/lib/5.36.0/x86_64-linux
    /home/brano/.cache/perlbrew/perls/perl-5.36/lib/5.36.0
```

**Comment by tonycoz** [comment] 2023-07-26 00:43
Duplicate of https://github.com/Perl/perl5/issues/20408

**Closed as completed** 2023-07-26 13:24 UTC
Labels: Needs Triage
