### ISSUE TITLE
Bleadperl v5.31.5-48-g760fdf2808 breaks KRYDE/Filter-gunzip-7.tar.gz

### ISSUE THREAD

**Issue by andk** [Perl/perl5#17268] opened 2019-11-06 07:31 UTC
Breaking commit: https://github.com/Perl/perl5/commit/760fdf2808b7158c548dcb6208804ff8d4c97b30

Sample fail report: http://www.cpantesters.org/cpan/report/2bbf525a-f690-11e9-b861-b2173384a6e2

XRef: https://rt.cpan.org/Ticket/Display.html?id=130914

**Comment by jkeenan** [comment] 2019-11-06 12:53
> Breaking commit: [760fdf2](https://github.com/Perl/perl5/commit/760fdf2808b7158c548dcb6208804ff8d4c97b30)
> 
> Sample fail report: http://www.cpantesters.org/cpan/report/2bbf525a-f690-11e9-b861-b2173384a6e2
> 
> XRef: https://rt.cpan.org/Ticket/Display.html?id=130914

This is a failure in Filter-gunzip's test suite.  The test segfaults at a point where it has to ```require``` a file which appears to have been specifically crafted for testing purposes and includes binary (gzipped?) data.
```
main::(t/test2.t:37):	  my $result = eval {
  DB<1> 
main::(t/test2.t:38):	    local $SIG{'__WARN__'} = sub {}; # no warnings
  DB<1> 
main::(t/test2.t:39):	    require $filename;
  DB<1> 
Segmentation fault (core dumped)
```
Filter::gunzip's essential functionality is documented as:
```
    This filter uncompresses gzipped Perl code at run-time. It can be used
    from the command line to run a .pl.gz file,

        perl -MFilter::gunzip foo.pl.gz
```
This functionality appears to be intact.
```
$ cat hello.pl
print "Hello world!\n";
$ gzip -c hello.pl > hello.pl.gz
$ bleadperl -Iblib/lib -Iblib/arch/auto/Filter/gunzip -MFilter::gunzip hello.pl.gz 
Hello world!
```
So the breakage is some subtlety revealed only during the test.  @arc -- and anyone familiar with source filters or layers -- can you take a look?

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment] 2019-11-06 19:32
@jkeenan what commit id were your tests done at? It may be that the reinstatement of the retry label has fixed this.

**Comment by jkeenan** [comment] 2019-11-06 20:19
On 11/6/19 2:32 PM, Tony Cook wrote:
> @jkeenan <https://github.com/jkeenan> what commit id were your tests 
> done at? It may be that the reinstatement of the retry label has fixed this.
> 

$ bleadperl -v | head -2 | tail -1
This is perl 5, version 31, subversion 6 (v5.31.6 
(v5.31.5-163-ga6d5b8290f)) built for x86_64-linux

commit a6d5b8290f10eb709eb405ee94145c9620f8e5a2
Author:     Tony Cook <tony@develop-help.com>
AuthorDate: Tue Nov 5 08:00:25 2019 +1100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Mon Nov 4 23:36:13 2019 +0100

     enforce strict for barewords in multiconcat

**Comment by tonycoz** [comment] 2019-11-06 20:55
ok, that's after the retry label was restored

**Comment by tonycoz** [comment] 2019-11-06 21:21
@arc looks like we still have some deep recursion:
```
#0  0x00005555556fe3ae in Perl_sv_free2 (
    my_perl=<error reading variable: Cannot access memory at address 0x7fffff7fefe8>, 
    sv=<error reading variable: Cannot access memory at address 0x7fffff7fefe0>, rc=<error reading variable: Cannot access memory at address 0x7fffff7fefdc>)
    at sv.c:7088
#1  0x000055555573c3ad in Perl_SvREFCNT_dec (my_perl=0x555555b7a010, 
    sv=0x555555db78e0) at inline.h:227
#2  0x000055555573ec4b in Perl_leave_scope (my_perl=0x555555b7a010, base=98)
    at scope.c:927
#3  0x000055555573c950 in Perl_pop_scope (my_perl=0x555555b7a010)
    at scope.c:130
#4  0x00005555555fa19f in Perl_filter_read (my_perl=0x555555b7a010, idx=0, 
    buf_sv=0x555555b9df00, maxlen=0) at toke.c:4644
#5  0x00005555555fa1ff in S_filter_gets (my_perl=0x555555b7a010, 
    sv=0x555555b9df00, append=0) at toke.c:4661
#6  0x00005555555ef44b in Perl_lex_next_chunk (my_perl=0x555555b7a010, flags=0)
    at toke.c:1347
#7  0x0000555555607cf7 in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=true, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:6834
#8  0x0000555555613451 in yyl_try (my_perl=0x555555b7a010, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:8625
#9  0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
#10 0x0000555555613451 in yyl_try (my_perl=0x555555b7a010, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:8625
#11 0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
#12 0x0000555555613451 in yyl_try (my_perl=0x555555b7a010, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:8625
#13 0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
#14 0x0000555555613451 in yyl_try (my_perl=0x555555b7a010, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:8625
#15 0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
#16 0x0000555555613451 in yyl_try (my_perl=0x555555b7a010, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:8625
#17 0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
...
#13537 0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
#13538 0x0000555555613451 in yyl_try (my_perl=0x555555b7a010, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:8625
#13539 0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
#13540 0x0000555555613451 in yyl_try (my_perl=0x555555b7a010, 
    s=0x555555df1812 "lots of newlines which will run-length compress\n", 
    len=0) at toke.c:8625
#13541 0x0000555555608c0b in yyl_fake_eof (my_perl=0x555555b7a010, fake_eof=0, 
    bof=false, s=0x555555df1810 "\n", len=0) at toke.c:7082
...
gave up trying to find the bottom.
$ ~/perl/blead/bin/perl5.31.6 -v | grep 'This is'
This is perl 5, version 31, subversion 6 (v5.31.6 (v5.31.5-174-gcc8ba724cc)) built for x86_64-linux-thread-multi
```

**Comment by kryde** [comment] 2019-11-07 12:14
I uploaded a new version 8.  Its test1.t is my XS layer onto PL_rsfp method.  Its test2.t is my pure-perl Filter::Util::Call and Compress::Raw::Zlib fallback method.  So see how that goes (and problems with the XS likely me, or problems with the perl hopefully not :).  The pure-perl can be run explicitly by "perl -MFilter::gunzip::Filter foo.pl.gz" (notice the sub-module name).

My XS now doesn't try to dup PL_rsfp up to a perl level handle.  I didn't try to find out what was going wrong there, beyond presuming it a case of "don't do that".

**Comment by kryde** [comment] 2019-11-29 00:00
I got an OpenBSD Amd64 5.31.7 failing in my version 8 test2.t which is the pure-perl.

http://www.cpantesters.org/cpan/report/0efe3086-117b-11ea-972b-ef706694f557

**Comment by jkeenan** [comment] 2019-11-29 02:09
> I got an OpenBSD Amd64 5.31.7 failing in my version 8 test2.t which is the pure-perl.
> 
> http://www.cpantesters.org/cpan/report/0efe3086-117b-11ea-972b-ef706694f557

I can confirm this failure in the following environment:
```
$ ./bin/perl -Ilib -v | head -2 | tail -1
This is perl 5, version 31, subversion 7 (v5.31.7 (v5.31.6-65-g17ba3f1d5d)) 
built for OpenBSD.amd64-openbsd-thread-multi
$ uname -mrs
OpenBSD 6.4 amd64
```

**Comment by jkeenan** [comment] 2020-01-28 22:06
@arc @tonycoz Can we get an update on the status of this BBC ticket for Filter-gunzip?

Thank you very much.
Jim Keenan

**Comment by xsawyerx** [comment] 2020-04-01 09:50
@arc  @tonycoz ping.

**Comment by tonycoz** [comment] 2020-04-02 04:56
What appears to be happening here is that yyl_try() and yyl_fake_eof() are recursively calling each other for each comment or blank line of the filtered input.

For the test case the first non-(blank, comment) line is line 50019, and the typical stack won't handle that many recursion levels.

This was changed with the tokeniser re-work done around p5h.

I'm looking at a possible (moderately ugly) solution but hopefully @arc will speak up.

**Comment by tonycoz** [comment] 2020-04-15 05:47
The update rebases and fixes a comment and a commit message.

The Win32/cygwin test failures are due to chocolatey performing maintenance.

**Comment by xsawyerx** [comment] 2020-04-15 18:07
Can we consider this resolved?

**Comment by tonycoz** [comment] 2020-04-16 00:20
Only if the (or "a") fix is merged.

**Comment by xsawyerx** [comment] 2020-04-25 11:05
@tonycoz Let's merge it then. :)

**Comment by xsawyerx** [comment] 2020-04-30 06:44
Are we good to close it now?

**Comment by jkeenan** [comment] 2020-04-30 12:12
@tonycoz could you assemble the various commits into a smoke-me branch for testing?

Nothing in this ticket has made it into blead so far, so Filter-gunzip is still in a BBC state.

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment] 2020-05-03 23:56
I've pushed it to `smoke-me/tonyc/17268-yyl_try-recursion-test`

**Comment by jkeenan** [comment] 2020-05-04 00:47
> I've pushed it to `smoke-me/tonyc/17268-yyl_try-recursion-test`

Filter::gunzip has a new version on CPAN since the opening of this ticket.  From [Changes](https://metacpan.org/changes/distribution/Filter-gunzip):
```
Version 8, November 2019
    - XS and PerlIO::gzip optional
    - avoid trouble with perl 5.30 rsfp at script level
```
With Tony's branch and this new version, I get PASS on both Linux and FreeBSD.

Thank you very much.
Jim Keenan

**Comment by toddr** [comment] 2020-05-19 06:41
@xsawyerx #17696 is waiting your sign off.

**Comment by xsawyerx** [comment] 2020-05-20 21:46
Fix was merged!

**Closed as completed** 2020-05-20 21:46 UTC
Labels: BBC
