### ISSUE TITLE
perl-5.39.4+ breaks Promise::ES6

### ISSUE THREAD

**Issue by FGasper** [Perl/perl5#21747] opened 2023-12-23 01:18 UTC
Module: Promise::ES6

**Description**
CPAN Testers failures: http://matrix.cpantesters.org/?dist=Promise-ES6+0.28

**Steps to Reproduce**
Try to run the tests with 5.39.4 or up. (I tried with 5.39.5.)

The failing tests are:
- `t/race_async.t`
- `t/race_fail.t`
- `t/race_success.t`

**Expected behavior**
The tests should pass.

Instead they seem to fail, which appears to be a result of a DESTROY handler not being called (which Promise::ES6 interprets as a memory leak).

```
Summary of my perl5 (revision 5 version 39 subversion 5) configuration:

  Platform:
    osname=darwin
    osvers=23.2.0
    archname=darwin-2level
    uname='darwin m-hjr99w7wx5 23.2.0 darwin kernel version 23.2.0: wed nov 15 21:53:18 pst 2023; root:xnu-10002.61.3~2release_arm64_t6000 arm64 '
    config_args='-de -Dprefix=/Users/felipe/perl5/perlbrew/perls/perl-5.39.5 -Dusedevel -Aeval:scriptdir=/Users/felipe/perl5/perlbrew/perls/perl-5.39.5/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=14.2 -DNO_THREAD_SAFE_QUERYLOCALE -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/opt/local/include'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=14.2 -DNO_THREAD_SAFE_QUERYLOCALE -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/opt/local/include'
    ccversion=''
    gccversion='Apple LLVM 14.0.0 (clang-1400.0.29.202)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=8
    longdblkind=0
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=14.2 -fstack-protector-strong -L/usr/local/lib -L/opt/local/lib'
    libpth=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/lib /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/local/lib /opt/local/lib /usr/lib
    libs=-lgdbm
    perllibs=
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=14.2 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under darwin
  Compiled at Dec 22 2023 18:37:18
  %ENV:
    PERLBREW_HOME="/Users/felipe/.perlbrew"
    PERLBREW_ROOT="/Users/felipe/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.96"
  @INC:
    /Users/felipe/perl5/perlbrew/perls/perl-5.39.5/lib/site_perl/5.39.5/darwin-2level
    /Users/felipe/perl5/perlbrew/perls/perl-5.39.5/lib/site_perl/5.39.5
    /Users/felipe/perl5/perlbrew/perls/perl-5.39.5/lib/5.39.5/darwin-2level
    /Users/felipe/perl5/perlbrew/perls/perl-5.39.5/lib/5.39.5
```

**Comment by jkeenan** [comment] 2023-12-23 03:27
I've taken a **very preliminary** look at how 3 test files in Promise::ES6's test suite are failing.  Each is dealing with race conditions.  Would you be able to reduce the failure to a one-liner in a format like ... `perl -MPromise::ES6 -e '[something];'`

**Comment by mauke** [comment] 2023-12-23 09:29
Duplicate of #21524?

**Closed as completed** 2023-12-23 11:40 UTC
Labels: BBC, Needs Triage
