### ISSUE TITLE
GDBM_File: gdbm_nextkey: Item not found

### ISSUE THREAD

**Issue by slimlv** [Perl/perl5#19149] opened 2021-09-22 12:53 UTC
Module: GDBM_File

**Description**
GDBM_File used with tie breaks each() iteration

**Steps to Reproduce**
```
#!/usr/bin/perl
  use strict;
  use GDBM_File;
  my $db = tie (my %bb, 'GDBM_File', 'bb.db', &GDBM_WRCREAT, 0640) or die("error == $! == ");
  $bb{'AA'} = 'BB';

  while (my ($key,$val) = each %bb) {
     print "$key => $val\n";
  }
  print "HERE";
```

**Expected behavior**
```
AA => BB
HERE
```

**Actual result**
```
AA => BB
gdbm_nextkey: Item not found at ./test.pl line 7.
```

**gdbm version**
gdbm-1.20

**Perl configuration**
```
Summary of my perl5 (revision 5 version 34 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=5.10.27-gentoo.docker.20210526
    archname=x86_64-linux-thread-multi
    uname='linux localhost 5.10.27-gentoo.docker.20210526 #1 smp wed may 26 12:40:17 eest 2021 x86_64 intel(r) xeon(r) silver 4110 cpu @ 2.10ghz genuineintel gnulinux '
    config_args='-des -Dinstallprefix=/usr -Dinstallusrbinperl=n -Ui_xlocale -Ui_ndbm -Di_gdbm -Ui_db -Dusethreads -DDEBUGGING=none -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Dnoextensions=ODBM_File -Duseshrplib -Darchname=x86_64-linux-thread -Dcc=x86_64-pc-linux-gnu-gcc -Dar=x86_64-pc-linux-gnu-ar -Dnm=x86_64-pc-linux-gnu-nm -Dcpp=x86_64-pc-linux-gnu-gcc -E -Dranlib=x86_64-pc-linux-gnu-ranlib -Doptimize=-O2 -march=opteron-sse3 -pipe -fforce-addr -fomit-frame-pointer -Dldflags=-Wl,-O1 -Wl,--as-needed -Dprefix=/usr -Dsiteprefix=/usr/local -Dvendorprefix=/usr -Dscriptdir=/usr/bin -Dprivlib=/usr/lib64/perl5/5.34 -Darchlib=/usr/lib64/perl5/5.34/x86_64-linux-thread-multi -Dsitelib=/usr/local/lib64/perl5/5.34 -Dsitearch=/usr/local/lib64/perl5/5.34/x86_64-linux-thread-multi -Dvendorlib=/usr/lib64/perl5/vendor_perl/5.34 -Dvendorarch=/usr/lib64/perl5/vendor_perl/5.34/x86_64-linux-thread-multi -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dvendorman1dir=/usr/share/man/man1 -Dvendorman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3pm -Dlibperl=libperl.so.5.34.0 -Dlocincpth=/usr/include  -Dglibpth=/lib64 /usr/lib64  -Duselargefiles -Dd_semctl_semun -Dcf_by=Gentoo -Dmyhostname=localhost -Dperladmin=root@localhost -Ud_csh -Dsh=/bin/sh -Dtargetsh=/bin/sh -Uusenm -Ui_xlocale -Ui_ndbm -Di_gdbm -Ui_db -Dusethreads -DDEBUGGING=none -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Dnoextensions=ODBM_File'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='x86_64-pc-linux-gnu-gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -march=opteron-sse3 -pipe -fforce-addr -fomit-frame-pointer'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe'
    ccversion=''
    gccversion='10.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='x86_64-pc-linux-gnu-gcc'
    ldflags ='-Wl,-O1 -Wl,--as-needed'
    libpth=/usr/local/lib64 /lib64 /usr/lib64 /usr/lib /lib
    libs=-lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc -lgdbm_compat
    perllibs=-ldl -lm -lcrypt -lutil -lpthread -lc
    libc=libc-2.33.so
    so=so
    useshrplib=true
    libperl=libperl.so.5.34.0
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -march=opteron-sse3 -pipe -fforce-addr -fomit-frame-pointer -Wl,-O1 -Wl,--as-needed'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    0001-Fix-hpux-hints.patch
    - Fix hpux hints
    0002-aix-gcc-detection-and-shared-library-soname-support.patch
    - aix gcc detection and shared library soname support
    0003-cpan-ExtUtils-MakeMaker-drop-PORTAGE_TMPDIR-from-LD_.patch
    - cpan/ExtUtils-MakeMaker: drop $PORTAGE_TMPDIR from LD_RUN_PATH
    - Bug: https://bugs.gentoo.org/105054
    0004-Remove-rpath-and-append-LDFLAGS-to-lddlflags.patch
    - Remove -rpath and append LDFLAGS to lddlflags
    0005-Add-headers-for-opensolaris.patch
    - Add headers for opensolaris
    0006-List-packaged-patches-in-patchlevel.h.patch
    - List packaged patches for perl-5.34.0(perl-5.34.0-patches-1) in patchlevel.h
    - Bug: https://bugs.debian.org/567489
    0007-Cleanup-PATH-and-shrpenv.patch
    - Cleanup PATH and shrpenv
    0008-Tweak-enc2xs-to-follow-symlinks-and-ignore-missing-I.patch
    - Tweak enc2xs to follow symlinks and ignore missing @INC directories.
    - Bug: https://bugs.debian.org/290336
    0009-darwin-Use-CC-to-link.patch
    - darwin: Use $CC to link
    - Bug: https://bugs.gentoo.org/297751
    0010-Provide-a-sensible-INSTALLDIRS-default-for-modules-i.patch
    - Provide a sensible INSTALLDIRS default for modules installed from CPAN.
    0011-Fix-interix-hints.patch
    - Fix interix hints
    0012-Set-libperl-soname.patch
    - Set libperl soname
    - Bug: https://bugs.gentoo.org/286840
    0013-Add-etc-perl-to-INC.patch
    - Add /etc/perl to @INC
    0014-cpan-ExtUtils-MakeMaker-remove-targets-that-generate.patch
    - cpan/ExtUtils-MakeMaker: remove targets that generate perllocal.pod
    0015-Don-t-force-fstack-protector-on-everyone.patch
    - Don't force -fstack-protector on everyone
    - Bug: https://bugs.gentoo.org/348557
    0016-Do-not-set-custom-CFLAGS-in-cpan-Digest-SHA.patch
    - Do not set custom CFLAGS in cpan/Digest-SHA
    - Bug: https://bugs.gentoo.org/506818
    0017-Configure-Don-t-include-sources-in-usr-local-for-com.patch
    - Configure: Don't include sources in /usr/local/ for compiling perl
    0018-cpan-IO-Socket-IP-Disable-network-tests.patch
    - cpan/IO-Socket-IP: Disable network tests
    0019-Fix-EUMM-podlocal-tests.patch
    - Fix EUMM podlocal tests
    0020-Skip-auto-linking-nsl-and-cl.patch
    - Skip auto-linking nsl and cl
    - Bug: https://rt.perl.org/Public/Bug/Display.html?id=13148
    0021-Disable-porting-tests-which-create-fun-false-failure.patch
    - Disable porting tests which create fun false-failures all over travis
    0022-Disable-PathTools-tests-which-fails-under-sandboxing.patch
    - Disable PathTools tests which fails under sandboxing
    - Bug: https://bugs.gentoo.org/645084
    0023-Fix-CPAN-FirstTime-defaults-with-nonexisting-site-di.patch
    - Fix CPAN::FirstTime defaults with nonexisting site dirs if a parent is writable
    - Bug: https://bugs.debian.org/688842
    0024-Pass-LD-settings-through-to-subdirectories.patch
    - Pass LD settings through to subdirectories
    - Bug: https://bugs.debian.org/758471
    0025-Memoize-Storable-respect-nstore-option-not-respected.patch
    - Memoize::Storable: respect 'nstore' option not respected
    - Bug: https://bugs.debian.org/587650
    - Bug: https://rt.cpan.org/Public/Bug/Display.html?id=77790
    0026-Better-errors-for-man-pages-from-standard-input.patch
    - Better errors for man pages from standard input
    - Bug: https://bugs.debian.org/777405
    0027-Respect-umask-during-installation.patch
    - Respect umask during installation
    0028-Document-that-CCFLAGS-should-include-Config-ccflags.patch
    - Document that CCFLAGS should include $Config{ccflags}
    - Bug: https://bugs.debian.org/628522
    - Bug: https://rt.cpan.org/Public/Bug/Display.html?id=68613
    0029-Fix-parallel-building.patch
    - Fix parallel building
    0030-Add-support-for-Dgentoolibdirs.patch
    - Add support for -Dgentoolibdirs
  Built under linux
  Compiled at Sep  1 2021 14:09:49
  @INC:
    /etc/perl
    /usr/local/lib64/perl5/5.34/x86_64-linux-thread-multi
    /usr/local/lib64/perl5/5.34
    /usr/lib64/perl5/vendor_perl/5.34/x86_64-linux-thread-multi
    /usr/lib64/perl5/vendor_perl/5.34
    /usr/lib64/perl5/5.34/x86_64-linux-thread-multi
    /usr/lib64/perl5/5.34
```

**Comment by tonycoz** [comment] 2021-09-23 01:52
I think I see the problem.

Historical gdbm.h defined GDBM_ITEM_NOT_FOUND as a macro:

```
# define GDBM_ITEM_NOT_FOUND	        15
```

but current gdbm.h uses an enum to define the error code symbols:

```
enum
  {
    GDBM_NO_ERROR		 = 0,
    GDBM_MALLOC_ERROR	         = 1,
...
    GDBM_ITEM_NOT_FOUND	         = 15,
```

To support very old versions of GDBM, GDBM_File defines GDBM_ITEM_NOT_FOUND if it isn't already defined (as a macro):
```
#ifndef GDBM_ITEM_NOT_FOUND
# define GDBM_ITEM_NOT_FOUND GDBM_NO_ERROR
#endif
```

It is strange perl's tests pass here, each() is tested on a GDBM file from what I can see, so I would have expected a test failure.
which since GDBM_ITEM_NOT_FOUND is no longer a macro means the check for that value ends up comparing against GDBM_NO_ERROR instead of the correct value.

**Comment by tonycoz** [comment] 2021-09-23 05:03
This appears to have been fixed in blead in the set of changes by Sergey Poznyakoff in June.

I was able to reproduce the problem with perl 5.34.0, but not in blead.

**Comment by tonycoz** [comment] 2021-10-11 00:36
Closing, since it's fixed.

**Closed as completed by tonycoz** 2021-10-11 00:36 UTC
Labels: ext/GDBM_File
