### ISSUE TITLE
":utf8" new default in Perl 5.30.2 for sysopen?

### ISSUE THREAD

**Issue by M-Reimer** [Perl/perl5#17665] opened 2020-03-22 14:00 UTC
**Description**

I've written a small helper which converts MIDI messages arriving on a MIDI device to JSON for Firefox to read via the "native app" interface. The program is here:

https://github.com/M-Reimer/midiinputprovider/blob/master/nativeapp/midiinputprovider.pl

For me it works as expected but one user reported a problem that he gets a message

    sysread() isn't allowed on :utf8 handles at midiinputprovider.pl line 72

I open the device with "sysopen" and the documentation says that for POSIX systems ":raw" is always the default anyway so I don't know what is happening here. Using "binmode" seems to fix the problem but in my opinion it shouldn't be needed as "sysopen" should not open with ":utf8" by default...

**Steps to Reproduce**

Open a MIDI device (or probably any device) with sysopen and try to read a byte from it with sysread.

**Expected behavior**

sysopen should never ever open with ":utf8" by default. IMHO even "open" shouldn't but if you decide to make "open" more "UTF8-friendly" this is OK for me. But "sysopen" should work fine for opening devices and so should not interfere with the data.

**Perl configuration**

The author of the respective pull request stated that he rebuilt Perl 5.30.2 with default configuration.

https://github.com/M-Reimer/midiinputprovider/pull/2

**Comment by orivej** [comment] 2020-03-22 14:21
I'll provide more details after analysing the issue a bit further.

**Comment by Grinnz** [comment] 2020-03-22 15:49
sysopen will respect the value of the `${^OPEN}` variable, which can be affected by the `-C` option or `PERL_UNICODE` environment variable in main program scope, or the `open` pragma in any lexical scope. Also note that any `:encoding` layer will include `:utf8` in order to translate to Perl's internal upgraded encoding. sysopen is also affected by the `PERLIO` environment variable globally (setting this to `:utf8` is always a mistake).

**Comment by Grinnz** [comment] 2020-03-22 15:52
`binmode $fh or die "binmode failed: $!";` after opening should always restore the handle to a binary stream regardless of the environment it was opened in.

**Comment by orivej** [comment] 2020-03-22 15:58
Yes, this is caused by having `PERL_UNICODE=D`. (Actually I have `PERL_UNICODE=ADSL`. I did not remember that I had it.) This `D` (or `i` to be precise) is necessary for `git svn` to support non-ASCII names in its `svn.authorsfile` (which maps svn logins to git names and emails), otherwise `git svn rebase` writes something like double encoded UTF-8 names in git commit authors…

**Comment by Grinnz** [comment] 2020-03-22 16:16
I'd recommend including that PERL_UNICODE setting in an alias or script where it's needed since it can affect things like this that don't expect it although it is at least limited to the main program scope. The program in question can be defensive with the `binmode` invocation I mentioned against either PERL_UNICODE or -C, but also against the default `CRLF` translation on Windows if that may come up.

**Comment by Grinnz** [comment] 2020-03-22 16:18
It can also use: `open(my $fh, '<:raw', "/dev/snd/$device")` or `open(my $fh, '<:', "/dev/snd/$device")` (this will explicitly ignore `${^OPEN}`)

**Comment by M-Reimer** [comment] 2020-03-22 16:20
The ":raw" thing was what @orivej  suggested in his pull request.

TBH I don't know what the recommended way is to open a char device from Perl. I thought sysopen does what it says: Just invoke "open" without fiddling too much with the results.

**Comment by Grinnz** [comment] 2020-03-22 16:22
`sysopen` is, despite the name, not related in any way to `sysread` or `syswrite`, except that all are done using low level methods. Default layers are still applied the same way as an `open` call that does not specify layers. My recommendation would be specifying layers explicitly in `open`, or following with a `binmode` (more compatible with Perls before 5.14).

**Comment by Grinnz** [comment] 2020-03-22 16:24
The upcoming rewrite of the [PerlIO](https://perldoc.pl/5.31.10/PerlIO) docs may be helpful.

**Comment by Grinnz** [comment] 2020-03-22 16:30
Also note that `sysread` does bypass any layers, but due to unfortunate historical implementation, it used to consider the stream as Perl's internal upgraded encoding if `:utf8` was set, and this later became fatal.

**Comment by Grinnz** [comment] 2020-03-22 16:32
So the most straightforward method may be: open with `<:` so only the PerlIO defaults are applied (which will not include `:utf8` except if the user breaks their system by setting that in `PERLIO`), and `sysread` to ignore any such layers.

**Comment by M-Reimer** [comment] 2020-03-22 16:35
Actually my expectation, at least with the combination "sysopen" and "sysread" would be that I **always** read raw bytes. That's why I use the "sys*" variants. They should not apply any kind of "layers".

IMHO a file handle opened with "sysopen" shouldn't even accept any layers to be added to it. If someone tries with "binmode", just exit with a fatal error.

**Comment by Grinnz** [comment] 2020-03-22 16:38
I understand that's your expectation, but that's not what sysopen does (I will see if I can update the docs to make this clear). It arguably should be what sysread does, though, `:utf8` existing just violates that for unfortunate reasons.

**Comment by orivej** [comment] 2020-03-22 16:41
Thank you! I am going to unset PERL_UNICODE locally, and try to fix git-svn upstream: it opens the authors file [here](https://github.com/git/git/blob/v2.25.2/git-svn.perl#L1938). Maybe they need `use open ':locale';`?…

**Comment by Grinnz** [comment] 2020-03-22 16:47
I would normally recommend opening the handle with [PerlIO::locale](https://metacpan.org/pod/PerlIO::locale) over that pragma, but I would guess it can't easily depend on CPAN modules.

**Comment by Grinnz** [comment] 2020-03-22 21:08
I have opened https://github.com/Perl/perl5/pull/17666 to hopefully help explain this better in the documentation.

**Comment by jkeenan** [comment] 2020-03-23 18:56
> I have opened #17666 to hopefully help explain this better in the documentation.

That p.r. has been merged into Perl 5 blead.  Does that documentation improvement resolve this issue?

Thank you very much.
Jim Keenan

**Closed as completed** 2020-03-23 20:54 UTC
