### ISSUE TITLE
the pack/unpack @ operator doesn't seem to work, nor does the perlpacktut example

### ISSUE THREAD

**Issue by florian-pe** [Perl/perl5#20158] opened 2022-08-25 17:13 UTC
I'm trying to understand how pack/unpack work so I'm not exactly sure this is a bug but it sures looks like it.

This example comes from the section `The Alignment Pit`
```
$ perl -E 'print pack "cxs cxxx l!", 1, 2, 3, 4' | hexdump -C
00000000  01 00 02 00 03 00 00 00  04 00 00 00 00 00 00 00  |................|
00000010
```

which works as expected, but then, there is a different template which is supposed to do the exact same thing, and doesn't.

```
$ perl -E 'print pack "@0c @2s! @4c @8l!", 1, 2, 3, 4' | hexdump -C
00000000  01 02 00 03 04 00 00 00  00 00 00 00              |............|
0000000c
```

I tried playing around with `@` but each time it appears to do nothing.

For information, my machine is little-endian, and a long is 8 bytes.

```
Summary of my perl5 (revision 5 version 36 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=5.12.15-arch1-1
    archname=x86_64-linux-thread-multi
    uname='archlinux'
    config_args='-des -Dusethreads -Duseshrplib -Doptimize=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto -Dprefix=/usr -Dvendorprefix=/usr -Dprivlib=/usr/share/perl5/core_perl -Darchlib=/usr/lib/perl5/5.36/core_perl -Dsitelib=/usr/share/perl5/site_perl -Dsitearch=/usr/lib/perl5/5.36/site_perl -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib/perl5/5.36/vendor_perl -Dscriptdir=/usr/bin/core_perl -Dsitescript=/usr/bin/site_perl -Dvendorscript=/usr/bin/vendor_perl -Dinc_version_list=none -Dman1ext=1perl -Dman3ext=3perl -Dcccdlflags='-fPIC' -Dlddlflags=-shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto -Dldflags=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='12.1.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib
    libs=-lpthread -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib/libc.so.6
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE'
    cccdlflags='-fPIC'
    lddlflags='-shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at May 29 2022 08:49:34
  %ENV:
    PERL5LIB="/home/user/.my_configurations/perl_modules"
  @INC:
    /home/user/.my_configurations/perl_modules
    /usr/lib/perl5/5.36/site_perl
    /usr/share/perl5/site_perl
    /usr/lib/perl5/5.36/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/5.36/core_perl
    /usr/share/perl5/core_perl
```

**Comment by demerphq** [comment] 2022-08-26 06:58
This is not a bug. You are using the '@' inside of double quotes, which means the arrays are being interpolated, and unfortunately the code you wrote is accessing vars that technically do exist: `@0`. (You could argue we should complain that you did that, and I would agree.)

```
$ perl -MO=Deparse -E'print pack "@0c @2s! @4c @8l!", 1, 2, 3, 4'
use feature 'current_sub', 'bitwise', 'evalbytes', 'fc', 'postderef_qq', 'say', 'state', 'switch', 'unicode_strings', 'unicode_eval';
print pack("@{0}c @{2}s! @{4}c @{8}l!", 1, 2, 3, 4);
-e syntax OK

$ perl -MO=Deparse -E'print pack q"@0c @2s! @4c @8l!", 1, 2, 3, 4'
use feature 'current_sub', 'bitwise', 'evalbytes', 'fc', 'postderef_qq', 'say', 'state', 'switch', 'unicode_strings', 'unicode_eval';
print "\cA\000\cB\000\cC\000\000\000\cD\000\000\000\000\000\000\000";
-e syntax OK

$ perl -E 'print pack q"@0c @2s! @4c @8l!", 1, 2, 3, 4' | hexdump -C
00000000  01 00 02 00 03 00 00 00  04 00 00 00 00 00 00 00  |................|
00000010

$ perl -E 'print pack "cxs cxxx l!", 1, 2, 3, 4' | hexdump -C
00000000  01 00 02 00 03 00 00 00  04 00 00 00 00 00 00 00  |................|
00000010
```

Closing as not-a-bug.

**Closed as completed by demerphq** 2022-08-26 06:58 UTC
Labels: Not a Bug

**Comment by florian-pe** [comment] 2022-08-26 14:32
Oh right, that's a bit silly of me. I did remembered about this exact interpolation problem yesterday but it didn't compute somehow.

Templates of pack/unpack are so esoteric that we think we are writing in a completely different language. Well not as double quotes are concerned clearly.
