### ISSUE TITLE
GetShortPathName test failed on some windows 

### ISSUE THREAD

**Issue by xiaoyafeng** [Perl/perl5#17571] opened 2020-02-19 03:25 UTC
Module:  Core Win32 

**Description**

Win32::GetShortPathName return filename as 8dot3 way which is compatible for DOS. I found on some new windows( Win10 1910 afterwards or windows 2016 etc) the default 8dot3 mode is off which made GetShortPathName test fail.
**Steps to Reproduce**
you can reproduce this error by following steps:
open cmd,
fsutil behavior query disable8dot3
if the state is not 0, the .\cpan\Win32\t\GetShortPathName.t would fail.
you can run fsutil behavior set disable8dot3 0 to enable it ( as administrator)

**Expected behavior**

I suggest either drop this test, or check 8dot3 before testing.

Below is new GetShortPathName.t:

use strict;
#use Test;
use Win32;
use Test::More;
my $path = "Long Path $$";
unlink($path);
END { unlink $path }

Win32::CreateFile($path);
ok(-f $path);
my $short = Win32::GetShortPathName($path);
SKIP: {

skip "8dot3 is not supported!", 1 if `fsutil behavior query disable8dot3` !~ m/0/; 
ok($short, qr/^\S{1,8}(\.\S{1,3})?$/);

}
ok(-f $short);

unlink($path);
ok(!-f $path);
ok(!defined Win32::GetShortPathName($path));
done_testing();

**Perl configuration**

```
# perl -V output goes here
```

**Comment by xiaoyafeng** [comment] 2020-02-19 07:07
Besides,  I note many tests on Win32/Unicode.t called GetShortPathName function, So they would be also failed. you have to run fsutil behavior set disable8dot3 0 ( by administrator) in order to pass them.

**Comment by richardleach** [comment] 2020-02-19 07:14
Looks like a duplicate of #16804. 

Change needed in https://github.com/perl-libwin32/win32, which has a PR for GetShortPathName.t, but looks like some work still needed on that ( https://github.com/perl-libwin32/win32/pull/12 ) 

I meant to look into the Unicode.t tests previously but forgot. :-(

@xiaoyafeng - are you building on C:\ or some other drive?

**Comment by xiaoyafeng** [comment] 2020-02-19 09:13
@richardleach  I built it on D:\

**Comment by tonycoz** [comment] 2020-03-01 22:55
This was reported upstream in 2015 as https://rt.cpan.org/Ticket/Display.html?id=103983 so we'll likely have to fix this ourselves.

**Comment by richardleach** [comment] 2020-03-02 14:02
@tonycoz - I'm happy to draft a PR based on https://github.com/perl-libwin32/win32/pull/12 and its discussion. Should I send that PR to upstream and prod Jan to take another look at it, or send it here?

**Comment by tonycoz** [comment] 2020-03-04 04:12
@richardleach try upstream, but if Jan is slow to respond we might need to include it in blead.

**Comment by richardleach** [comment] 2020-03-17 23:49
An updated PR sent upstream: https://github.com/perl-libwin32/win32/pull/23

**Comment by richardleach** [comment] 2020-10-14 21:04
Currently known test failures due to 8dot3filename support being disabled should be fixed in the next stable perl release via:
* https://github.com/Perl/perl5/commit/2b8fc250cda86dddcc8e7c8418c67d5bb24036c8 for Win32's GetShortPathName.t and Unicode.t
* When EUMM v7.49_04 (or a later build) is pulled in (assuming this happens prior to blead freeze) for EUMM's 02-dynamic.t.

**Closed as completed** 2020-10-14 23:05 UTC
Labels: distro-mswin32, Closable?
