### ISSUE TITLE
5.32 fails to install in focal fossa

### ISSUE THREAD

**Issue by JJ** [Perl/perl5#18110] opened 2020-09-03 09:16 UTC
There's this failing test in perl 5.32.0 downloades using perlbrew

```
# Failed test 21 - [perl \#128020] long body lines are wrapped: maxlen 1551 at ../lib/perlbug.t line 154
```

This is 

```
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and

```
5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by richardleach** [comment] 2020-09-03 21:04
@JJ Please could you:

- comment out or delete the following line in perlbug.t
`unlink $testreport, $body, $attachment;`
- rerun the test
- attach to this issue the _attached.txt_, _body.txt_, and _test.rep_ files that should be created when the test is run

(The _test.rep_ file is the one that's leading to the test failure. It should incorporate the contents of the other two files, as well as some boilerplate and the output of `perl -V`.)

**Comment by hakonhagland** [comment] 2020-10-24 07:49
Same problem on Ubuntu 20.04. Commenting out [line 141](https://github.com/Perl/perl5/blob/blead/lib/perlbug.t#L141) does not help. Rerunning the test now gives:
```
$ perl -I../lib TEST ../lib/perlbug.t 
t/../lib/perlbug ... # Failed test 21 - [perl \#128020] long body lines are wrapped: maxlen 1189 at ../lib/perlbug.t line 156
FAILED at test 21
Failed 1 test out of 1, 0.00% okay.
	../lib/perlbug.t
### Since not all tests were successful, you may want to run some of
### them individually and examine any diagnostic messages they produce.
### See the INSTALL document's section on "make test".
Elapsed: 1 sec
u=0.00  s=0.00  cu=0.80  cs=0.11  scripts=1  tests=25
```
I tried add two lines below line 153:
```
diag($maxlen1);
diag($maxlen2);
```
Rerunning the test now shows that `$maxlen1` is 1189 and `$maxlen2` is 1200.

**Comment by richardleach** [comment] 2020-10-25 00:38
@hakonhagland Commenting out line 141 wasn't supposed to fix the problem, it was to stop deletion of the generated _attached.txt_, _body.txt_, and _test.rep_ files so that they can be attached to this issue to (potentially) help find the cause of this test failure.

**Comment by richardleach** [comment] 2020-10-26 02:21
I installed a fresh Ubuntu 20.04.01 LTS (focal fossa) server instance in a VM and could not reproduce this issue either with a manual build from the 5.32.0 git tag or via _perlbrew_.

This OS release is subtly different from the version in the original report:
```
gcc 9.3.0-17ubuntu~20.04
5.4.0-52-generic #57-Ubuntu SMP blah blah
```
..but I'm not sure if that's relevant.

It might help for @JJ or @hakonhagland to:
* attach the _attached.txt_, _body.txt_, and _test.rep_ files, as covered earlier in this issue
* confirm if the problem still happens with Ubuntu 20.04.01 LTS
* share the output of the `locale` command (all properties were `en_US.UTF-8` on my test VM)

**Comment by xenu** [comment] 2020-10-26 03:08
This is probably a duplicate of #15544

**Comment by richardleach** [comment] 2020-10-26 19:00
Thanks @xenu. I'm going to assume it is unless there's indication otherwise.

**Comment by jkeenan** [comment] 2021-02-11 01:39
Closing, as this appears to be a duplicate of https://github.com/Perl/perl5/issues/15544

**Closed as completed by jkeenan** 2021-02-11 01:39 UTC
