### ISSUE TITLE
BBC: Blead breaks MOB/Signals-XSIG-0.15.tar.gz

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#19535] opened 2022-03-13 15:24 UTC
t/11-local.t started to fail with "Out of memory!" or similar errors, beginning with perl 5.35.1.
First bug report on CPAN Testers: http://www.cpantesters.org/cpan/report/38f6381e-ca68-11eb-8547-9cbd9f1ff94e
Overview of test reports: http://matrix.cpantesters.org/?dist=Signals-XSIG+0.15
Note that there are some test failures with older perl versions, but it seems that these failures are caused by other test scripts.

Somehow localizing `%SIG` seems to be the problem --- with the following diff the problem does not happen anymore:
```
--- i/t/11-local.t
+++ w/t/11-local.t
@@ -61,7 +61,7 @@ ok($restored, "hash val restored after local \$SIG{...}");
 
   %z = %SIG;
   SKIP: {
-    local %SIG;
+#    local %SIG;
     $SIG{$s} = 'IGNORE';
     ok($SIG{$s} eq 'IGNORE', 'set $SIG{sig}');
 
```

**Comment by hvds** [comment] 2022-03-17 16:52
Manual bisection pinpoints 55f5e765689, logically enough. @Leont could you take a look?

Test case can be reduced to `perl -e 'use Signals::XSIG; { local %SIG }'`, the hang occurs on scope exit.

If I correctly understand the implementation, both `%SIG` and its elements are tied, so I guess `Perl_magic_setsigall` will need to handle a bit more magic.

**Comment by Leont** [comment] 2022-03-17 17:54
> so I guess Perl_magic_setsigall will need to handle a bit more magic.

Yeah, I'm guessing that the `if (PL_localizing == 2)` should also trigger when `PL_localizing == 1`

**Comment by Leont** [comment] 2022-03-26 15:15
> > so I guess Perl_magic_setsigall will need to handle a bit more magic.
> 
> Yeah, I'm guessing that the `if (PL_localizing == 2)` should also trigger when `PL_localizing == 1`

That's not the problem.

The problem is that this module is actually [tie()ing `%SIG`](https://metacpan.org/release/MOB/Signals-XSIG-0.15/source/lib/Signals/XSIG.pm#L80), which unsurprisingly turns out to be highly fragile.

I think this is a them problem and not an us problem.

**Comment by hvds** [comment] 2022-03-26 15:39
> The problem is that this module is actually [tie()ing `%SIG`](https://metacpan.org/release/MOB/Signals-XSIG-0.15/source/lib/Signals/XSIG.pm#L80), which unsurprisingly turns out to be highly fragile.
> 
> I think this is a them problem and not an us problem.

Could you expand on that? It seems to have worked ok (at the level of passing its tests) up until now.

**Comment by Leont** [comment] 2022-03-26 18:28
> Could you expand on that? It seems to have worked ok (at the level of passing its tests) up until now.

On every write to an element, this module will untie, write and then retie `%SIG`. That means that any writing iteration will infinitely loop. My code happens to do exactly that: loop and call setmagic.

This code was always broken, it just didn't have a test showing the broken behavior.

**Comment by rjbs** [comment] 2022-04-02 20:17
Do we think the underlying library can be salvaged?

**Comment by Leont** [comment] 2022-04-02 20:38
> Do we think the underlying library can be salvaged?

Probably, but I suspect it will be more work that I'm willing to put into it.

The obvious approach is to moving %SIG to another name, and then redefining %SIG to be a hash with the new magic. That way the new magic doesn't have to untie itself to access the old magic.

**Comment by rjbs** [comment] 2022-04-17 14:32
@Leont Could you please file an RT on Signals-XSIG describing the problem for the author/maintainer?  Then I'll mark this not-blocking-v5.36

(I'm not 100% sure I followed the key parts, and I'm a bit under the weather today, so hoping to go lie down 😉)

**Comment by Leont** [comment] 2022-05-02 12:17
> @Leont Could you please file an RT on Signals-XSIG describing the problem for the author/maintainer? Then I'll mark this not-blocking-v5.36

Done https://rt.cpan.org/Ticket/Display.html?id=142501

**Comment by Leont** [comment] 2022-05-04 19:10
This should be fixed in the new release

**Closed as completed by Leont** 2022-05-04 19:10 UTC
Labels: BBC
