### ISSUE TITLE
BBC: Blead Breaks NOVOZHILV/App-SimpleBackuper-0.2.24.tar.gz

### ISSUE THREAD

**Issue by andk** [Perl/perl5#19475] opened 2022-03-01 04:26 UTC
**Description**

The distribution's test suite started to fail with perl 5.35.9

Bisect leads to v5.35.8-120-g3d1a4f0672 (https://github.com/perl/perl5/commit/3d1a4f0672)

Sample fail report: http://www.cpantesters.org/cpan/report/86f5c994-983f-11ec-aa0b-dce1df4e2aba

Matrix: http://matrix.cpantesters.org/?dist=App-SimpleBackuper+0.2.24

**Steps to Reproduce**

cpan -i NOVOZHILV/App-SimpleBackuper-0.2.24.tar.gz

**Expected behavior**

Should successfully test and install the module

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 35 subversion 10) configuration:
  Commit id: 64f0d0d96084c25955864f7be0672b173a25fb1e
  Platform:
    osname=linux
    osvers=5.15.0-2-amd64
    archname=x86_64-linux-thread-multi-ld
    uname='linux k93msid 5.15.0-2-amd64 #1 smp debian 5.15.5-2 (2021-12-18) x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-20-g64f0d0d960/ac75 -Dmyhostname=k93msid -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Duselongdouble -DEBUGGING=both'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.33.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Feb 26 2022 10:47:59
  %ENV:
    PERL5LIB=""
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="2810526"
    PERL5_CPAN_IS_RUNNING="2810526"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-20-g64f0d0d960/ac75/lib/site_perl/5.35.10/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-20-g64f0d0d960/ac75/lib/site_perl/5.35.10
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-20-g64f0d0d960/ac75/lib/5.35.10/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-20-g64f0d0d960/ac75/lib/5.35.10
    .
```

**Comment by haarg** [comment] 2022-03-01 06:24
This dist has code that always enables the latest feature bundle. And one of the modules uses prototypes. So the code breaks now that signatures are part of the latest feature bundle.

I've filed a PR to fix the code to use a stable feature bundle:
dmitry-novozhilov/simple-backuper#1

**Comment by jkeenan** [comment] 2022-03-01 13:17
> This dist has code that always enables the latest feature bundle. And one of the modules uses prototypes. So the code breaks now that signatures are part of the latest feature bundle.
> 
> I've filed a PR to fix the code to use a stable feature bundle: [dmitry-novozhilov/simple-backuper#1](https://github.com/dmitry-novozhilov/simple-backuper/pull/1)

I can confirm that upstream p.r. gets tests to pass.

**Comment by eserte** [comment] 2022-03-13 15:48
It looks like ZARABOZO/Perlmazing-1.2816.tar.gz has the same problem (enabling all features + using prototypes).
I filed a bug report: https://rt.cpan.org/Ticket/Display.html?id=141747

**Comment by dmitry-novozhilov** [comment] 2022-03-27 16:37
I've merged a @haarg's pull request which fixes the problem.
(Big thanks to @haarg)

**Comment by jkeenan** [comment] 2022-03-27 17:01
> I've merged a @haarg's pull request which fixes the problem. (Big thanks to @haarg)

Confirmed.  I've installed App-SimpleBackuper-0.2.25 against a blead built two days ago.  Thanks for your investigation.  Closing this ticket.

**Closed as completed by jkeenan** 2022-03-27 17:01 UTC
Labels: BBC, sendToCPAN
