### ISSUE TITLE
[doc] contributions documentation is not directly visible in GitHub 

### ISSUE THREAD

**Issue by michaelkaye** [Perl/perl5#21913] opened 2024-01-30 15:55 UTC
**Where**

.GitHub/contributing.pod

**Description**

When coming to GitHub and attempting to view the contributing link as below:

![Screenshot_20240130-155048](https://github.com/Perl/perl5/assets/1917473/ea711444-5c0a-49a9-9b11-ef1f02f4d6d7)

I get to this page, not the contributing guidelines:
![Screenshot_20240130-155055](https://github.com/Perl/perl5/assets/1917473/2b1e3485-5372-4e46-9efa-264c30bb0674)

I don't think you can use symlinks here.

**Comment by haarg** [comment] 2024-01-31 02:11
This is a duplicate of #21806

**Closed as completed by haarg** 2024-01-31 02:11 UTC
Labels: Needs Triage, documentation
