### ISSUE TITLE
The readme file is not up to the standard [doc] 

### ISSUE THREAD

**Issue by wphtech** [Perl/perl5#18965] opened 2021-07-06 17:51 UTC
**Where**

https://github.com/Perl/perl5/blob/blead/README

**Description**

I think it should be redone with proper markdown styling since it is the face of the perl5 language. Please take a look at

https://github.com/rakudo/rakudo

https://github.com/rust-lang/rust

https://github.com/golang/go

**Comment by Grinnz** [comment] 2021-07-06 17:56
Duplicate of https://github.com/Perl/perl5/issues/17227

**Closed as completed** 2021-07-06 17:57 UTC
Labels: Needs Triage, documentation
