### ISSUE TITLE
exec() leaks SV internals

### ISSUE THREAD

**Issue by FGasper** [Perl/perl5#18603] opened 2021-02-23 17:06 UTC
Module: (core)

**Description**
```
> perl -e'my $foo = "épée"; utf8::upgrade($foo); exec "echo", $foo'
Ã©pÃ©e
```
`exec()` is taking the SV’s internals rather than its downgraded form, which is what Perl usually does (e.g., print/syswrite/etc.)

**Steps to Reproduce**
```
> perl -E'my $foo = "épée"; utf8::upgrade($foo); say $foo; exec "echo", $foo'
épée
Ã©pÃ©e
```

**Expected behavior**
I should see the same output on both lines from the one-liner; instead I see mojibake on the 2nd line.

**Perl configuration**

```
> perl5.30 -V
Summary of my perl5 (revision 5 version 30 subversion 3) configuration:

  Platform:
    osname=darwin
    osvers=18.7.0
    archname=darwin-thread-multi-2level
    uname='darwin mojave.internal.macports.net 18.7.0 darwin kernel version 18.7.0: mon apr 27 20:09:39 pdt 2020; root:xnu-4903.278.35~1release_x86_64 x86_64 '
    config_args='-des -Dprefix=/opt/local -Dscriptdir=/opt/local/bin -Dvendorprefix=/opt/local -Dusemultiplicity=y -Dusethreads -Duseshrplib -Dcc=/usr/bin/clang -Dman1ext=1pm -Dman3ext=3pm -Dinstallstyle=lib/perl5 -Dman1dir=/opt/local/share/man/man1p -Dman3dir=/opt/local/share/man/man3p -Dsitebin=/opt/local/libexec/perl5.30/sitebin -Dsiteman1dir=/opt/local/share/perl5.30/siteman/man1 -Dsiteman3dir=/opt/local/share/perl5.30/siteman/man3 -Dvendorbin=/opt/local/libexec/perl5.30 -Dvendorman1dir=/opt/local/share/perl5.30/man/man1 -Dvendorman3dir=/opt/local/share/perl5.30/man/man3 -Dpager=/usr/bin/less -sR -Dperlpath=/opt/local/bin/perl5.30 -Dstartperl=#!/opt/local/bin/perl5.30 -Acppflags=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Accflags=-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -Alddlflags=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -Aldflags=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk '
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='/usr/bin/clang'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -fno-strict-aliasing -fstack-protector-strong -I/opt/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3'
    cppflags='-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -fno-strict-aliasing -fstack-protector-strong -I/opt/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='/usr/bin/clang'
    ldflags =' -mmacosx-version-min=10.14 -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -fstack-protector-strong'
    libpth=/opt/local/lib /Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/lib /Library/Developer/CommandLineTools/usr/lib /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib /usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=true
    libperl=libperl.dylib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.14 -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under darwin
  Compiled at Jun  3 2020 08:21:46
  %ENV:
    PERLBREW_HOME="/Users/felipe/.perlbrew"
    PERLBREW_ROOT="/Users/felipe/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.88"
  @INC:
    /opt/local/lib/perl5/site_perl/5.30/darwin-thread-multi-2level
    /opt/local/lib/perl5/site_perl/5.30
    /opt/local/lib/perl5/vendor_perl/5.30/darwin-thread-multi-2level
    /opt/local/lib/perl5/vendor_perl/5.30
    /opt/local/lib/perl5/5.30/darwin-thread-multi-2level
    /opt/local/lib/perl5/5.30
```

**Comment by Grinnz** [comment] 2021-02-23 17:43
This is pretty much a duplicate of https://github.com/Perl/perl5/issues/10623 which mentions many such affected functions.

**Comment by FGasper** [comment] 2021-02-23 18:12
Agreed. Closing. Sorry for the noise, and thank you.

**Closed as completed** 2021-02-25 02:28 UTC
Labels: Unicode and System Calls
