### ISSUE TITLE
Origin-based install using -R,'$$ORIGIN/../lib'

### ISSUE THREAD

**Issue by noloader** [Perl/perl5#17534] opened 2020-02-06 00:41 UTC
**Description**
I'm building Perl 5.30.1 from the release tarball. My `LDFLAGS` include `-L<prefix>/lib -Wl,-R,'$$ORIGIN/../lib' -Wl,-R,<prefix>/lib -Wl,--enable-new-dtags`. They are passed to `Configure` using `-Aldflags`.

The `$$ORIGIN` is used to safely pass the dollar sign through a makefile. The double dollar sign is the way to escape the dollar sign in make.

It appears Perl munges the origin-based runpath. When I inspect the resulting binary:

```
$ objdump -x ./perl | grep -i -E 'RPATH|RUNPATH'
  RUNPATH              15530ORIGIN/../lib:/home/jwalton/tmp/build-test/lib
```

If I use a single dollar sign, `-L<prefix>/lib -Wl,-R,'$ORIGIN/../lib' -Wl,-R,<prefix>/lib -Wl,--enable-new-dtags`, then it looks like `$ORIGIN` gets lopped off:

```
$ objdump -x ./perl | grep -i -E 'RPATH|RUNPATH'
  RUNPATH              /../lib:/home/jwalton/tmp/build-test/lib
```

**Steps to Reproduce**
```
./Configure \
     -Dprefix="/tmp/ok_to_delete" \
     -Dlibdir="/tmp/ok_to_delete/lib" \
    -Aldflags="-L/tmp/ok_to_delete/lib -Wl,-R,'$$ORIGIN/../lib' -Wl,-R,/tmp/ok_to_delete/lib -Wl,--enable-new-dtags"
```
**Expected behavior**
The runpath should look something like:

```
$ objdump -x /home/jwalton/tmp/ok_to_delete/bin/bzip2 | grep -i -E 'RPATH|RUNPATH'
  RUNPATH              $ORIGIN/../lib:/home/jwalton/tmp/ok_to_delete/lib
```

And to be clear... If invoking GCC directly, then use `-Wl,-R,'$ORIGIN/../lib'`. If using a makefile, then use `-Wl,-R,'$$ORIGIN/../lib'` to escape the dollar sign in the makefile.

**Perl configuration**
```
$ PERL5LIB=lib:$PERL5LIB ./perl -V
Summary of my perl5 (revision 5 version 30 subversion 1) configuration:
   
  Platform:
    osname=linux
    osvers=4.19.80-0-vanilla
    archname=x86_64-linux
    uname='linux alpine3-x64 4.19.80-0-vanilla #1-alpine smp fri oct 18 11:27:53 utc 2019 x86_64 linux '
    config_args='-des -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dpkgconfig=/usr/local/lib/pkgconfig -Dcc=gcc -Acppflags=-I/usr/local/include -DNDEBUG -Accflags=-g2 -O2 -march=native -fPIC -pthread -Aldflags=-L/usr/local/lib -Wl,-R,'$$ORIGIN/../lib' -Wl,-R,/usr/local/lib -Wl,--enable-new-dtags -Dextras=Text::Template Test::More'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-g2 -O2 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-I/usr/local/include -DNDEBUG -g2 -O2 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -L/usr/local/lib -Wl,-R,11928ORIGIN/../lib -Wl,-R,/usr/local/lib -Wl,--enable-new-dtags -fstack-protector-strong'
    libpth=/usr/local/lib /usr/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -Wl,-R,11928ORIGIN/../lib -Wl,-R,/usr/local/lib -fstack-protector-strong'

Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Feb  4 2020 10:32:16
  %ENV:
    PERL5LIB="lib:"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.30.1/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.30.1
    /usr/local/lib/perl5/5.30.1/x86_64-linux
    /usr/local/lib/perl5/5.30.1
```

**Comment by noloader** [comment] 2020-02-06 01:26
For now here is what my Perl recipe looks like...

```
PERL_PKGCONFIG="${BUILD_PKGCONFIG[*]}"
PERL_CPPFLAGS="${BUILD_CPPFLAGS[*]}"
PERL_CFLAGS="${BUILD_CFLAGS[*]}"
PERL_LDFLAGS="${BUILD_LDFLAGS[*]}"
PERL_CC="${CC}"

# Perl munges -Wl,-R,$$ORIGIN/../lib. Set it to XXORIGIN so we
# can fix it later after Perl produces the makefiles.
# Also see https://github.com/Perl/perl5/issues/17534
PERL_LDFLAGS=$(echo -n "${PERL_LDFLAGS}" | sed 's/\$\$ORIGIN/XXORIGIN/g')

if ! ./Configure -des \
     -Dprefix="$INSTX_PREFIX" \
     -Dlibdir="$INSTX_LIBDIR" \
     -Dpkgconfig="$PERL_PKGCONFIG" \
     -Dcc="$PERL_CC" \
     -Acppflags="$PERL_CPPFLAGS" \
     -Accflags="$PERL_CFLAGS" \
     -Aldflags="$PERL_LDFLAGS" \
     -Dextras="Text::Template Test::More"
then
    echo "Failed to configure Perl"
    exit 1
fi

# Fix -Wl,-R,$$ORIGIN/../lib
echo "Patching Makefiles"
for file in $(find "$PWD" -iname 'Makefile')
do
    chmod +w "$file"
    sed 's|XXORIGIN|\$\$ORIGIN|g' "$file" > "$file.fixed"
    mv "$file.fixed" "$file"
    chmod -w "$file"
done
```

**Comment by doughera88** [comment] 2020-02-12 15:52
This is tricky.  In addition to worrying about what the Makefile will do with $ORIGIN, you have to pass that value through a 25,000 line Configure shell script, and then have it interpreted again by the Makefile.SH script that generates the main Makefile.  You are ultimately trying to pass through two special characters, ' and $, through an unknown number of layers of shell parsing.  The single quotes are especially tricky because you can't embed single quotes within a single quote string in Bourne shell.  


Something like the following trick, using a 'config.over' file, might do what you want.  (See the INSTALL file.)  That is, instead of using 

> ./Configure \
>      -Dprefix="/tmp/ok_to_delete" \
>      -Dlibdir="/tmp/ok_to_delete/lib" \
>     -Aldflags="-L/tmp/ok_to_delete/lib -Wl,-R,'$$ORIGIN/../lib' -Wl,-R,/tmp/ok_to_delete/lib -Wl,--enable-new-dtags"

Try something like

```
cat > config.over<<'EOSH'
ldflags=' -fstack-protector-strong -L/usr/local/lib -L/tmp/ok_to_delete/lib -Wl,-R,'"'"'"'"'"'"'"'"'$$ORIGIN/../lib'"'"'"'"'"'"'"'"' -Wl,-R,/tmp/ok_to_delete/lib -Wl,--enable-new-dtags'
EOSH

sh ./Configure -Dusedevel -des  \
     -Dprefix="/tmp/ok_to_delete" \
     -Dlibdir="/tmp/ok_to_delete/lib" 


```
That should make the ldflags variable in config.sh contain $$ORIGIN, which, when included in a Makefile, will ultimately give you a plain $ORIGIN.  However, if anything ever uses that ldflags outside of a Makefile context, then the double dollar signs might cause a problem.  (I'm imagining things built with Module::Build, for example, though I certainly haven't tested anything.)

Another trick would be to generate config.sh and makefile with a plain ORIGIN (without any $ signs or quotes at all) but then run a separate script to edit them to put the quotes and $ signs in where you want them.  Then run 'make'.  That might actually be simplest in the end.

**Comment by doughera88** [comment] 2020-02-26 15:47
Realistically, I don't see any clean way to change Configure to accommodate this use case.  I agree it's a limitation, but I'm inclined to close this.  I'm not sure of the most useful label -- perhaps "Won't fix" is appropriate.

**Comment by drhpc** [comment] 2020-07-20 14:32
So would it perhaps make sense to add this as an option to the build? To handle $ORIGIN explicitly? So not a bug, but a feature request …

**Comment by jkeenan** [comment] 2020-09-01 00:41
> So would it perhaps make sense to add this as an option to the build? To handle $ORIGIN explicitly? So not a bug, but a feature request …

Given the difficulties which @doughera88 described we would encounter trying to implement this, I would say no -- unless you yourself came up with a patch.

Closing this ticket.  Please open a new ticket if you develop a solution.

Thank you very much.
Jim Keenan

**Closed as completed by jkeenan** 2020-09-01 00:41 UTC
Labels: type-configure, wontfix
