### ISSUE TITLE
Declaring and assigning a lexical variable conditionnaly actually produces a weird state variable...

### ISSUE THREAD

**Issue by Yaribz** [Perl/perl5#20802] opened 2023-02-11 23:16 UTC
Running this code:
```perl
use warnings;
use strict;

sub bug {
  my $var=1 if(0);
  die "var is defined !\n" if(defined $var);
  print "var is NOT defined \n";
  $var=1;
}

bug();
bug();
```

produces this output:
```
var is NOT defined
var is defined !
```

I don't think this is the expected behavior (tested on multiple Perl versions... 5.28, 5.32... on Linux and Windows).

**Comment by Grinnz** [comment] 2023-02-12 00:14
This is a very well known issue, duplicate of #15764

**Closed as completed by Grinnz** 2023-02-12 00:14 UTC
Labels: my-in-false-conditional

**Comment by Yaribz** [comment] 2023-02-12 07:09
Wow indeed, this issue is actually known since 2004 at least and it has been decided to keep this behavior, that is really crazy...

I guess it's time to parse all my code to remove all the usages of this construct which produce buggy behaviors (and which are incredibly time-consuming to debug), this will take time...

I genuinely though Perl was handling this construct in the intuitive way (i.e. declare a lexical variable, and then if the condition is true assign a value, else the variable stays undefined). The fact that it's building a persistent state variables on purpose for obscure reasons in this case is really counter-intuitive.

**Comment by Yaribz** [comment] 2023-02-12 07:46
Wow indeed, this issue is actually known since 2004 at least and it has been decided to keep this behavior, that is really crazy...
Thanks !

**Comment by Grinnz** [comment] 2023-02-12 08:40
It's not decided to keep this behavior, some usages have been deprecated in preparation for changing it (but it's complicated).
