### ISSUE TITLE
Fails to install 5.14.4 on macOS 13.1: clang: error: invalid arch name '-arch -mmacosx-version-min=13.1'

### ISSUE THREAD

**Issue by hakonhagland** [Perl/perl5#21512] opened 2023-09-23 11:24 UTC
On macOS 13.1:
```
$ wget https://www.cpan.org/src/5.0/perl-5.14.4.tar.bz2
$ tar zxvf perl-5.14.4.tar.bz2
$ cd perl-5.14.4
$ patchperl
Auto-guessed '5.14.4'
Patching 'hints/darwin.sh'
patching Configure
No such line 25150 in input file, ignoring
patching ext/Errno/Errno_pm.PL
patching Configure
patching utils/h2ph.PL
patching lib/h2ph.t
patching cpan/Time-Local/t/Local.t
patching pp.c
patching Configure
patching ext/DynaLoader/DynaLoader_pm.PL
patching cpan/ExtUtils-MakeMaker/lib/ExtUtils/Liblist/Kid.pm
patching make_ext.pl
$ sh Configure -de '-Duseshrplib' '-Dusethreads' '-Duse64bitall'
grep: empty (sub)expression

Beginning of configuration questions for perl5.

Checking echo to see how to suppress newlines...
...using \c
The star should be here-->*

First let's make sure your kit is complete.  Checking...
Looks good...


This installation shell script will examine your system and ask you questions
to determine how the perl5 package should be installed. If you get
stuck on a question, you may use a ! shell escape to start a subshell or
execute a command.  Many of the questions will have default answers in square
brackets; typing carriage return will give you the default.

On some of the questions which ask for file or directory names you are allowed
to use the ~name construct to specify the login directory belonging to "name",
even if you don't have a shell which knows about that.  Questions where this is
allowed will be marked "(~name ok)".

[Type carriage return to continue]

The prompter used in this script allows you to use shell variables and
backticks in your answers.  You may use $1, $2, etc...  to refer to the words
in the default answer, as if the default line was a set of arguments given to a
script shell.  This means you may also use $* to repeat the whole default line,
so you do not have to re-type everything to add something to the default.

Every time there is a substitution, you will have to confirm.  If there is an
error (e.g. an unmatched backtick), the default answer will remain unchanged
and you will be prompted again.

If you are in a hurry, you may run 'Configure -d'.  This will bypass nearly all
the questions and use the computed defaults (or the previous answers if there
was already a config.sh file). Type 'Configure -h' for a list of options.
You may also start interactively and then answer '& -d' at any prompt to turn
on the non-interactive behaviour for the remainder of the execution.

[Type carriage return to continue]

Much effort has been expended to ensure that this shell script will run on any
Unix system.  If despite that it blows up on yours, your best bet is to edit
Configure and run it again.  If you can't run Configure for some reason,
you'll have to generate a config.sh file by hand.  Whatever problems you
have, let me (perlbug@perl.org) know how I blew it.

This installation script affects things in two ways:

1) it may do direct variable substitutions on some of the files included
   in this kit.
2) it builds a config.h file for inclusion in C programs.  You may edit
   any of these files as the need arises after running this script.

If you make a mistake on a question, there is no easy way to back up to it
currently.  The easiest thing to do is to edit config.sh and rerun all the SH
files.  Configure will offer to let you do this before it runs the SH files.

[Type carriage return to continue]

Locating common programs...
awk is in /usr/bin/awk.
cat is in /bin/cat.
chmod is in /bin/chmod.
comm is in /usr/bin/comm.
cp is in /bin/cp.
echo is in /bin/echo.
expr is in /bin/expr.
grep is in /usr/bin/grep.
ls is in /bin/ls.
mkdir is in /bin/mkdir.
rm is in /bin/rm.
sed is in /usr/bin/sed.
sort is in /usr/bin/sort.
touch is in /usr/bin/touch.
tr is in /usr/bin/tr.
uniq is in /usr/bin/uniq.

Don't worry if any of the following aren't found...
ar is in /usr/bin/ar.
bison is in /usr/bin/bison.
I don't see byacc out there, offhand.
cpp is in /usr/bin/cpp.
csh is in /bin/csh.
date is in /bin/date.
egrep is in /usr/bin/egrep.
I don't see gmake out there, either.
gzip is in /usr/bin/gzip.
less is in /usr/bin/less.
ln is in /bin/ln.
make is in /usr/bin/make.
more is in /usr/bin/more.
nm is in /usr/bin/nm.
I don't see nroff out there, either.
perl is in /Users/hakonhaegland/perl5/perlbrew/perls/perl-5.34.0/bin/perl.
I don't see pg out there, either.
test is in /bin/test.
uname is in /usr/bin/uname.
zip is in /usr/bin/zip.
Substituting less -R for less.
Using the test built into your sh.

Checking compatibility between /bin/echo and builtin echo (if any)...
They are compatible.  In fact, they may be identical.
The following message is sponsored by

  Dresden.pm<--The stars should be here.

Dear Perl user, system administrator or package
maintainer, the Perl community sends greetings to
you. Do you (emblematical) greet back [Y/n]? n


Symbolic links are supported.

Checking how to test for symbolic links...
You can test for symbolic links with 'test -h'.


Good, your tr supports [:lower:] and [:upper:] to convert case.
Using [:upper:] and [:lower:] to convert case.

First time through, eh?  I have some defaults handy for some systems
that need some extra help getting the Configure answers right:

3b1   		dragonfly   	irix_6_0   	opus   		super-ux
aix   		dynix   	irix_6_1   	os2   		svr4
aix_3   	dynixptx   	isc   		os390   	svr5
aix_4   	epix   		isc_2   	os400   	ti1500
altos486   	esix4   	linux   	posix-bc   	titanos
amigaos   	fps   		lynxos   	powerux   	ultrix_4
atheos   	freebsd   	midnightbsd   	qnx   		umips
aux_3   	genix   	mips   		rhapsody   	unicos
beos   		gnu   		mirbsd   	riscos   	unicosmk
bsdos   	gnukfreebsd   	mpc   		sco   		unisysdynix
catamount   	gnuknetbsd   	mpeix   	sco_2_3_0   	utekv
convexos   	greenhills   	ncr_tower   	sco_2_3_1   	uts
cxux   		haiku   	netbsd   	sco_2_3_2   	uwin
cygwin   	hpux   		newsos4   	sco_2_3_3   	vmesa
darwin   	i386   		next_3   	sco_2_3_4   	vos
dcosx   	interix   	next_3_0   	solaris_2
dec_osf   	irix_4   	next_4   	stellar
dgux   		irix_5   	nonstopux   	sunos_4_0
dos_djgpp   	irix_6   	openbsd   	sunos_4_1

You may give one or more space-separated answers, or "none" if appropriate.
If you have a handcrafted Policy.sh file or a Policy.sh file generated by a
previous run of Configure, you may specify it as well as or instead of
OS-specific hints.  If hints are provided for your OS, you should use them:
although Perl can probably be built without hints on many platforms, using
hints often improve performance and may enable features that Configure can't
set up on its own. If there are no hints that match your OS, specify "none";
DO NOT give a wrong version or a wrong OS.

Which of these apply, if any? [darwin]
Adding -mmacosx-version-min=13.1 to ccflags
Adding -mmacosx-version-min=13.1 to ldflags

*** Don't recognize processor, can't specify 64 bit compilation.


Configure uses the operating system name and version to set some defaults.
The default value is probably right if the name rings a bell. Otherwise,
since spelling matters for me, either accept the default or answer "none"
to leave it blank.

Operating system name? [darwin]

Operating system version? [22.2.0]

By default, perl5 will be installed in /usr/local/bin, manual pages
under /usr/local/man, etc..., i.e. with /usr/local as prefix for all
installation directories. Typically this is something like /usr/local.
If you wish to have binaries under /usr/bin but other parts of the
installation under /usr/local, that's ok: you will be prompted
separately for each of the installation directories, the prefix being
only used to set the defaults.

Installation prefix to use? (~name ok) [/usr/local]

AFS does not seem to be running...

In some special cases, particularly when building perl5 for distribution,
it is convenient to distinguish the directory in which files should be
installed from the directory (/usr/local) in which they will
eventually reside.  For most users, these two directories are the same.

What installation prefix should I use for installing files? (~name ok)
[/usr/local]

Perl can be built to use the SOCKS proxy protocol library.  To do so,
Configure must be run with -Dusesocks.  If you use SOCKS you also need
to use the PerlIO abstraction layer, this will be implicitly selected.

If this doesn't make any sense to you, just accept the default 'n'.
Build Perl for SOCKS? [n]

Previous version of perl5 used the standard IO mechanisms as
defined in <stdio.h>.  Versions 5.003_02 and later of perl5 allow
alternate IO mechanisms via the PerlIO abstraction layer, but the
stdio mechanism is still available if needed.  The abstraction layer
can use AT&T's sfio (if you already have sfio installed) or regular stdio.
Using PerlIO with sfio may cause problems with some extension modules.

If this doesn't make any sense to you, just accept the default 'y'.
Use the PerlIO abstraction layer? [y]

Getting the current patchlevel...
(You have perl5 version 14 subversion 4.)

Perl can be built to take advantage of threads on some systems.
To do so, Configure can be run with -Dusethreads.

Note that Perl built with threading support runs slightly slower
and uses more memory than plain Perl. The current implementation
is believed to be stable, but it is fairly new, and so should be
treated with caution.

If this doesn't make any sense to you, just accept the default 'y'.
Build a threading Perl? [y]
(Your platform does not have any specific hints for threaded builds.
 Assuming POSIX threads, then.)

Perl can be built so that multiple Perl interpreters can coexist
within the same Perl executable.
This multiple interpreter support is required for interpreter-based threads.

Use which C compiler? [cc]
clang: error: invalid arch name '-arch -mmacosx-version-min=13.1'
clang: error: invalid arch name '-arch try.c'
clang: error: no input files
Uh-oh, the C compiler 'cc' doesn't seem to be working.

You seem to have a working gcc, though.
Would you like to use it? [y]
clang: error: invalid arch name '-arch try.c'
clang: error: no input files
You need to find a working C compiler.
Either (purchase and) install the C compiler supplied by your OS vendor,
or for a free C compiler try http://gcc.gnu.org/
I cannot continue any further, aborting.
```

See also https://stackoverflow.com/q/77161089/2173773

**Comment by iabyn** [comment] 2023-09-23 13:04
On Sat, Sep 23, 2023 at 04:24:31AM -0700, Håkon Hægland wrote:
> On macOS 13.1:
> ```
> $ wget https://www.cpan.org/src/5.0/perl-5.14.4.tar.bz2

Given that 5.14.4 was released 10 years ago, shouldn't this ticket have
been raised against App-perlbrew, rather than perl?

-- 
You never really learn to swear until you learn to drive.

**Comment by jkeenan** [comment] 2023-09-23 14:46
> On Sat, Sep 23, 2023 at 04:24:31AM -0700, Håkon Hægland wrote: On macOS 13.1: ``` $ wget https://www.cpan.org/src/5.0/perl-5.14.4.tar.bz2
> Given that 5.14.4 was released 10 years ago, shouldn't this ticket have been raised against App-perlbrew, rather than perl?
> […](#)
> -- You never really learn to swear until you learn to drive.

I agree with @iabyn that this is not something which needs to be solved by perl5-porters or resolved in our Issues queue.  Just now I managed to use perlbrew to install perl-5.14.4 on Ubuntu Linux 22.04.  No problems configuring, building or testing.  So the problem is probably specific to the combination of operating system, C compiler, and the way a 10+-year-old version of `./Configure` identifies the C compiler.  I agree that you should first contact the perlbrew maintainers.

**Closed as completed by jkeenan** 2023-09-23 14:46 UTC
Labels: Needs Triage

**Comment by hakonhagland** [comment] 2023-09-23 18:00
> agree that you should first contact the perlbrew maintainers.

@jkeenan and @iabyn Thanks for your comments. Seems like this issue has already been reported there: https://github.com/gugod/App-perlbrew/issues/768
