### ISSUE TITLE
[doc] sysread is deprecated

### ISSUE THREAD

**Issue by iddq** [Perl/perl5#17885] opened 2020-06-25 07:27 UTC
**Where**
perl5/pod/perldeprecation.pod

**Description**
Can you please extend the documentation what are recommended instead of the deprecated sysread(), recv(), syswrite() or send() ?

Thank you.

**Comment by Grinnz** [comment] 2020-06-25 14:21
These functions are not deprecated. They cannot be used on handles with encoding layers since this was fundamentally broken.

**Comment by karenetheridge** [comment] 2020-06-25 19:02
Specifically, `perldeprecation` says:

>  Reading/writing bytes from/to :utf8 handles.
>  
> The sysread(), recv(), syswrite() and send() operators are deprecated on handles that have the ":utf8" layer, either explicitly, or implicitly, eg., with the ":encoding(UTF-16LE)" layer.

https://perldoc.pl/perldeprecation#Reading/writing-bytes-from/to-:utf8-handles.

**Comment by Leont** [comment] 2020-06-25 20:15
> The sysread(), recv(), syswrite() and send() operators are deprecated on handles that have the ":utf8" layer, either explicitly, or implicitly, eg., with the ":encoding(UTF-16LE)" layer.

Yeah, so if you really need to do utf-8, you should either use buffered IO, or decode your data yourself.

**Comment by iddq** [comment] 2020-06-25 21:05
Thank you. What is the problem with it? I used sysread/utf8/perl 5.28 without any problem. ps. there is no warning with IO::Handle->sysread

**Comment by Grinnz** [comment] 2020-06-25 21:10
The problem is that it assumes the byte stream will be in Perl's internal upgraded encoding (`:utf8`, which is kind of like UTF-8 but not quite), but ignores any other layers on the handle which could be really important, like an `:encoding` layer that actually translates that internal encoding to a completely different encoding, or a `:crlf` you might then expect to be noticed. So in the case of non-UTF-8 encodings it was actually completely broken, and when you only mean to use it for UTF-8 it is risky (like using `:utf8` in general for input), so in 5.30 it is an error.

It's kind of unfortunate because having the ability for unbuffered I/O to still recognize translation layers would be functionally useful, but I'm not sure whether that is possible with how layers work.

**Comment by Leont** [comment] 2020-06-25 21:12
> What is the problem with it? I used sysread/utf8/perl 5.28 without any problem. ps. there is no warning with IO::Handle->sysread

Several, actually. The first was that it didn't always use the right encoding (it always used utf-8, even when it was actually utf-16). The second was that it could do multiple reads/writes, when the whole point of sysread/syswrite is doing exactly one read/write.

**Closed as completed** 2020-07-07 11:22 UTC
Labels: documentation, Closable?
