### ISSUE TITLE
visual 2019 test failures in perl 5.30 on windows 2016

### ISSUE THREAD

**Issue by xiaoyafeng** [Perl/perl5#17332] opened 2019-11-28 02:19 UTC
Subject: visual 2019 can't build perl 5.30 on windows 2016
To: perlbug@perl.org
From: xyf.xiao@outlook.com
Reply-To: xyf.xiao@outlook.com
Message-Id: <5.30.0_28460_1574906984@WIN-4P02OPRJS9H>

This is a bug report for perl from xyf.xiao@outlook.com,
generated with the help of perlbug 1.41 running under perl 5.30.0.

-----------------------------------------------------------------
[Please describe your issue here]
I've tried to build perl 5.30 with visual studio 2019. It can be compiled successfully but some tests failed when running nmake test

```
../ext/POSIX/t/time.t .............................................. 1/19
#   Failed test 'strftime() can handle unicode chars in the format string'
#   at t/time.t line 65.
Wide character in print at ../../lib/Test2/Formatter/TAP.pm line 124.
#	   got: '1970&#65533;?m&#65533;?d&#65533;?'
#     expected: '1970&#24180;01&#26376;16&#26085;'

#   Failed test 'strftime() can handle unicode chars in the format string'
#   at t/time.t line 68.
Wide character in print at ../../lib/Test2/Formatter/TAP.pm line 124.
#	   got: '1970&#65533;?m&#65533;?d&#65533;?'
#     expected: '1970&#24180;01&#26376;16&#26085;'

#   Failed test 'Format string has correct character'
#   at t/time.t line 74.
#	   got: '63'
#     expected: '223'

#   Failed test 'Format string has correct character'
#   at t/time.t line 76.
#	   got: '63'
#     expected: '223'
# Looks like you failed 4 tests of 19.
....
....
../lib/locale.t .................................................... 1/? Use of uninitialized value $Config{"d_has_C_UTF8"} in string eq at ./loc_tools.pl line 343.
Use of uninitialized value $Config{"d_has_C_UTF8"} in string eq at ./loc_tools.pl line 343, <DATA> line 47.
....
....

Test Summary Report
-------------------
op/magic.t							 (Wstat: 0 Tests: 195 Failed: 2)
	  Failed tests:  178, 181
	  uni/gv.t							   (Wstat: 0 Tests: 206 Failed: 1)
	  Failed test:	78
	  ../ext/IPC-Open3/t/IPC-Open3.t				   (Wstat: 0 Tests: 45 Failed: 0)
	  TODO passed:	 25
	  ../ext/POSIX/t/time.t 					   (Wstat: 1024 Tests: 19 Failed: 4)
	  Failed tests:  9-10, 12-13
	    Non-zero exit status: 4
		Files=2661, Tests=1149180, 1837 wallclock secs (98.95 usr +  7.03 sys = 105.98 CPU)
	Result: FAIL
	NMAKE : fatal error U1077: '.\perl.exe' : return code '0x7'
	Stop.
```

```
[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=install
    severity=medium
---
Site configuration information for perl 5.30.0:

Configured by strawberry-perl at Thu May 23 12:21:57 2019.

Summary of my perl5 (revision 5 version 30 subversion 0) configuration:
   
  Platform:
    osname=MSWin32
    osvers=10.0.17763.529
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.30.0.1 #1 Thu May 23 12:20:46 2019 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++.exe'
    ldflags ='-s -L"C:\perl\perl\lib\CORE" -L"C:\perl\c\lib"'
    libpth=C:\perl\c\lib C:\perl\c\x86_64-w64-mingw32\lib C:\perl\c\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl530.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\perl\perl\lib\CORE" -L"C:\perl\c\lib"'


---
@INC for perl 5.30.0:
    C:/perl/perl/site/lib/MSWin32-x64-multi-thread
    C:/perl/perl/site/lib
    C:/perl/perl/vendor/lib
    C:/perl/perl/lib

---
Environment for perl 5.30.0:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual
Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\Common7\Tools\;E:\software\WINDOWS.X64_193000_db_home\jdk\bin;E:\software\WINDOWS.X64_193000_db_home\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\perl\perl\bin;C:\perl\perl\site\bin;C:\perl\c\bin;d:\C300\Tomcat\jdk\bin;d:\C300\Tomcat\jdk\jre\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    PERL_BADLANG (unset)
    SHELL (unset)
```

**Comment by khwilliamson** [comment] 2019-11-28 05:44
We came up with a possible fix for this.  If you could try building the current development release of Perl and see if this problem persists or goes, away, we'd appreciate it.  You can find it at
https://github.com/Perl/perl5.git, or go here:

https://github.com/Perl/perl5

and click on the 'Clone or download button' and then select download.

**Comment by xiaoyafeng** [comment] 2019-11-28 07:04
The problems seems persists, and more. ;)

```
op/magic.t ......................................................... 155/195 # Failed test 178 - ENV store downgrades utf8 in setenv at op/magic.t line 78
#      got 'foo=eh zero ?PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX64\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\VC\\VCPackages;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\bin\\Roslyn;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools\\x64\\;C:\\Program Files (x86)\\HTML Help Workshop;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\\\MSBuild\\Current\\Bin;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\;E:\\software\\WINDOWS.X64_193000_db_home\\jdk\\bin;E:\\software\\WINDOWS.X64_193000_db_home\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\perl\\perl\\bin;C:\\perl\\perl\\site\\bin;C:\\perl\\c\\bin;d:\\C300\\Tomcat\\jdk\\bin;d:\\C300\\Tomcat\\jdk\\jre\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\cmd;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja\n'
# expected /(?^:^(?:foo=)?eh\ zero\ \�$)/
# Failed test 181 - ENV store encodes high utf8 in SV at op/magic.t line 78
#      got 'foo=X-Day \x{e1}\x{a6}?PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX64\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\VC\\VCPackages;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\bin\\Roslyn;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools\\x64\\;C:\\Program Files (x86)\\HTML Help Workshop;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\\\MSBuild\\Current\\Bin;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\;E:\\software\\WINDOWS.X64_193000_db_home\\jdk\\bin;E:\\software\\WINDOWS.X64_193000_db_home\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\perl\\perl\\bin;C:\\perl\\perl\\site\\bin;C:\\perl\\c\\bin;d:\\C300\\Tomcat\\jdk\\bin;d:\\C300\\Tomcat\\jdk\\jre\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\cmd;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja\n'
# expected /(?^:^(?:foo=)?X\-Day\ \�\�\�$)/
op/magic.t ......................................................... Failed 2/195 subtests
        (less 10 skipped subtests: 183 okay)

uni/greek.t ........................................................ skipped: encoding.pm is no longer supported by the perl core
uni/gv.t ........................................................... 1/206 Malformed UTF-8 character: \xe1\xb4\x3f (unexpected non-continuation byte 0x3f, 2 bytes after start byte 0xe1; need 3 bytes, got 2) at -e line 3.
Malformed UTF-8 character (fatal) at -e line 3.
# Failed test 78 - DESTROY was called at uni/gv.t line 319
#      got ''
# expected /(?^u:^Farewell ᴹ=SCALAR)/
uni/gv.t ........................................................... Failed 1/206 subtests

../cpan/ExtUtils-MakeMaker/t/dir_target.t .......................... ok
../cpan/ExtUtils-MakeMaker/t/echo.t ................................ Use of uninitialized value in concatenation (.) or string at C:\perl\perl5-blead\lib/ExtUtils/MM_Win32.pm line 146.
Use of uninitialized value in concatenation (.) or string at C:\perl\perl5-blead\lib/ExtUtils/MM_Win32.pm line 146.
../cpan/ExtUtils-MakeMaker/t/echo.t ................................ ok

../ext/POSIX/t/termios.t ........................................... skipped: POSIX::termios not implemented on this architecture at (eval 8) line 1.
../ext/POSIX/t/time.t .............................................. 1/19
#   Failed test 'strftime() can handle unicode chars in the format string'
#   at t/time.t line 70.
Wide character in print at ../../lib/Test2/Formatter/TAP.pm line 125.
#          got: '1970�?m�?d�?'
#     expected: '1970年01月16日'

#   Failed test 'strftime() can handle unicode chars in the format string'
#   at t/time.t line 73.
Wide character in print at ../../lib/Test2/Formatter/TAP.pm line 125.
#          got: '1970�?m�?d�?'
#     expected: '1970年01月16日'

#   Failed test 'Format string has correct character'
#   at t/time.t line 79.
#          got: '63'
#     expected: '223'

#   Failed test 'Format string has correct character'
#   at t/time.t line 81.
#          got: '63'
#     expected: '223'
# Looks like you failed 4 tests of 19.
../ext/POSIX/t/time.t .............................................. Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/19 subtests
        (less 2 skipped subtests: 13 okay)

Test Summary Report
-------------------
op/magic.t                                                       (Wstat: 0 Tests: 195 Failed: 2)
  Failed tests:  178, 181
uni/gv.t                                                         (Wstat: 0 Tests: 206 Failed: 1)
  Failed test:  78
../ext/IPC-Open3/t/IPC-Open3.t                                   (Wstat: 0 Tests: 45 Failed: 0)
  TODO passed:   25
../ext/POSIX/t/time.t                                            (Wstat: 1024 Tests: 19 Failed: 4)
  Failed tests:  9-10, 12-13
  Non-zero exit status: 4
Files=2664, Tests=1139096, 2253 wallclock secs (97.81 usr +  7.06 sys = 104.88 CPU)
Result: FAIL
NMAKE : fatal error U1077: '.\perl.exe' : return code '0x7'
Stop.
```

**Comment by sisyphus** [comment] 2019-11-30 03:18
Are you set up to build the same perl on the same Windows 2016 machine using a mingw-w64 port of gcc ?
Doing so would help clarify whether the problem lies with Visual Studio 2019 or with the Windows 2016 system.

If the gcc build is fine, then we'll know that the problem is related to your version of Visual Studio.
If the gcc build presents the same test failures then it would seem likely that the problem is related to something in that Windows OS.

Cheers,
Rob

**Comment by xsawyerx** [comment] 2019-12-27 18:50
I updated the comments to improve formatting. It was difficult to view. (You can do this by adding three backticks on an empty line - to begin - and three backticks on an empty line - to end.)

**Comment by xiaoyafeng** [comment] 2020-02-19 09:19
@sisyphus , I've dig this issue recently, the failure of the tests is because newer windows set 8dot3 mode disable.  after running fsutil behavior set disable8dot3 0 ( by administrator), all tests pass.
Please refer to #17571  and #16804 as @richardleach point out.

**Comment by sisyphus** [comment] 2020-02-19 11:06
Thanks for the update @xiaoyafeng

Cheers,
Rob

**Comment by richardleach** [comment] 2020-10-14 21:08
Currently known test failures due to 8dot3filename support being disabled should be fixed in the next stable perl release via:
* https://github.com/Perl/perl5/commit/2b8fc250cda86dddcc8e7c8418c67d5bb24036c8 for Win32's GetShortPathName.t and Unicode.t
* When EUMM v7.49_04 (or a later build) is pulled in (assuming this happens prior to blead freeze) for EUMM's 02-dynamic.t.

I'm unsure whether some of the test failures earlier in this issue (e.g. magic.t, gv.t, time.t) will still remain and also require looking into.

**Closed as completed** 2020-10-14 23:05 UTC
Labels: Needs Triage, distro-mswin32
