### ISSUE TITLE
[5.31.5] -Dusequadmath build fails cpan/Math-BigInt/t/to_ieee754-mbf.t

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#17203] opened 2019-10-22 04:14 UTC
Module:
Math::BigFloat
**Description**

$ perl ~/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t
snip
ok 47
#
# smallest positive normal number (k = 128)
#
Negative repeat count does nothing at /home/sisyphus/blead-5.31.5-q/lib/perl5/5.31.5/Math/BigFloat.pm line 4517.
not ok 48
#   Failed test at /home/sisyphus/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t line 204.
#          got: '\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
#     expected: '\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
#
# largest normal number (k = 128)
#
ok 49
snip

Affects only the -Dusequadmath build.

**Steps to Reproduce**

**Expected behavior**

**Perl configuration**

```
Summary of my perl5 (revision 5 version 31 subversion 5) configuration:

  Platform:
    osname=linux
    osvers=4.15.0-65-generic
    archname=x86_64-linux-quadmath
    uname='linux sisyphus5-desktop 4.15.0-65-generic #74-ubuntu smp tue sep 17 17:06:04 utc 2019 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Duse64bitall -Uversiononly -Dusedevel -Dprefix=/home/sisyphus/blead-5.31.5-q -Dusequadmath'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='7.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='__float128'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -lquadmath
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -lquadmath
    libc=libc-2.27.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.27'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_QUADMATH
  Built under linux
  Compiled at Oct 21 2019 22:43:43
  @INC:
    /home/sisyphus/blead-5.31.5-q/lib/perl5/site_perl/5.31.5/x86_64-linux-quadmath
    /home/sisyphus/blead-5.31.5-q/lib/perl5/site_perl/5.31.5
    /home/sisyphus/blead-5.31.5-q/lib/perl5/5.31.5/x86_64-linux-quadmath
    /home/sisyphus/blead-5.31.5-q/lib/perl5/5.31.5

```

**Comment by jkeenan** [comment] 2019-10-28 10:37
> Module:
> Math::BigFloat
> **Description**
> 
> $ perl ~/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t
> snip
> ok 47
> # smallest positive normal number (k = 128)
> 
> Negative repeat count does nothing at /home/sisyphus/blead-5.31.5-q/lib/perl5/5.31.5/Math/BigFloat.pm line 4517.
> not ok 48
> # Failed test at /home/sisyphus/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t line 204.
> # got: '\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
> # expected: '\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
> # largest normal number (k = 128)
> 
> ok 49
> snip
> 
> Affects only the -Dusequadmath build.
> 
[snip]


This failure is appearing in many smoke-test reports on quadmath builds on Linux.  See:
http://perl5.test-smoke.org/submatrix?test=../cpan/Math-BigInt/t/to_ieee754-mbf.t&pversion=5.31.6

**Comment by jkeenan** [comment] 2019-10-28 10:44
> > Module:
> > Math::BigFloat
> > **Description**
> > $ perl ~/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t
> > snip
> > ok 47
> > \# smallest positive normal number (k = 128)
> > Negative repeat count does nothing at /home/sisyphus/blead-5.31.5-q/lib/perl5/5.31.5/Math/BigFloat.pm line 4517.
> > not ok 48
> > \# Failed test at /home/sisyphus/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t line 204.
> > \# got: '\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
> > \# expected: '\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
> > \# largest normal number (k = 128)
> > ok 49
> > snip
> > Affects only the -Dusequadmath build.
> 
> [snip]
> 
> This failure is appearing in many smoke-test reports on quadmath builds on Linux. See:
> http://perl5.test-smoke.org/submatrix?test=../cpan/Math-BigInt/t/to_ieee754-mbf.t&pversion=5.31.6

Sisyphus:  I was unable to reproduce this today in a quadmath build on Linux.  However, I noticed that in the past day Steve Hay upgraded blead to use Math::BigInt version 1.999818 (commit 83cfb917431918a5da88bf23c217d7ff06af8f1d).  Does that solve the problem for you?

If it does *not* solve the problem, would you be able to bisect the failure?  According to Carlos Guevara's smoke-test reports, this failure started to emerge after commit a578d0f3e3.  (See http://perl5.test-smoke.org/report/96425.)

Thank you very much.
Jim Keenan

**Comment by sisyphus** [comment] 2019-10-28 12:45
Thanks Jim.
1.999818 tests fine.

IMO, this ticket can be closed.

Cheers,
Rob

**Comment by jkeenan** [comment] 2019-10-28 13:03
> On Mon, Oct 28, 2019 at 9:44 PM James E Keenan <notifications@github.com>
> wrote:
> 
>  > Module:
>  > Math::BigFloat
>  > *Description*
>  > $ perl ~/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t
>  > snip
>  > ok 47
>  > # smallest positive normal number (k = 128)
>  > Negative repeat count does nothing at
>  > /home/sisyphus/blead-5.31.5-q/lib/perl5/5.31.5/Math/BigFloat.pm line 
> 4517.
>  > not ok 48
>  > # Failed test at
>  > /home/sisyphus/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t line
>  > 204.
>  > # got:
>  > '\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>  > # expected:
>  > '\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>  > # largest normal number (k = 128)
>  > ok 49
>  > snip
>  > Affects only the -Dusequadmath build.
>  >
>  > [snip]
>  >
>  > This failure is appearing in many smoke-test reports on quadmath 
> builds on
>  > Linux. See:
>  >
>  > 
> http://perl5.test-smoke.org/submatrix?test=../cpan/Math-BigInt/t/to_ieee754-mbf.t&pversion=5.31.6
>  >
>  > Sisyphus: I was unable to reproduce this today in a quadmath build on
>  > Linux. However, I noticed that in the past day Steve Hay upgraded 
> blead to
>  > use Math::BigInt version 1.999818 (commit 83cfb91
>  > 
> <https://github.com/Perl/perl5/commit/83cfb917431918a5da88bf23c217d7ff06af8f1d>).
>  > Does that solve the problem for you?
>  >
>  > If it does *not* solve the problem, would you be able to bisect the
>  > failure? According to Carlos Guevara's smoke-test reports, this failure
>  > started to emerge after commit a578d0f
>  > 
> <https://github.com/Perl/perl5/commit/a578d0f3e37a8500429796cdeeba96dbba029778>.
>  > (See http://perl5.test-smoke.org/report/96425.)
>  >
>  > Thank you very much.
>  > Jim Keenan
>  >

On 10/28/19 8:45 AM, sisyphus wrote:> Thanks Jim.
 > 1.999818 tests fine.
 >
 > IMO, this ticket can be closed.
 >
 > Cheers,
 > Rob
 >
 >

Thanks, I will do so once we see passing smoke tests.

**Comment by jkeenan** [comment] 2019-11-01 11:55
> On Mon, Oct 28, 2019 at 9:44 PM James E Keenan ***@***.***> wrote: > Module: > Math::BigFloat > *Description* > $ perl ~/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t > snip > ok 47 > # smallest positive normal number (k = 128) > Negative repeat count does nothing at > /home/sisyphus/blead-5.31.5-q/lib/perl5/5.31.5/Math/BigFloat.pm line 4517. > not ok 48 > # Failed test at > /home/sisyphus/comp/perl-5.31.5/cpan/Math-BigInt/t/to_ieee754-mbf.t line > 204. > # got: > '\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > # expected: > '\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > # largest normal number (k = 128) > ok 49 > snip > Affects only the -Dusequadmath build. > > [snip] > > This failure is appearing in many smoke-test reports on quadmath builds on > Linux. See: > > http://perl5.test-smoke.org/submatrix?test=../cpan/Math-BigInt/t/to_ieee754-mbf.t&pversion=5.31.6 > > Sisyphus: I was unable to reproduce this today in a quadmath build on > Linux. However, I noticed that in the past day Steve Hay upgraded blead to > use Math::BigInt version 1.999818 (commit [83cfb91](https://github.com/Perl/perl5/commit/83cfb917431918a5da88bf23c217d7ff06af8f1d) > <[83cfb91](https://github.com/Perl/perl5/commit/83cfb917431918a5da88bf23c217d7ff06af8f1d)>). > Does that solve the problem for you? > > If it does *not* solve the problem, would you be able to bisect the > failure? According to Carlos Guevara's smoke-test reports, this failure > started to emerge after commit a578d0f > <[a578d0f](https://github.com/Perl/perl5/commit/a578d0f3e37a8500429796cdeeba96dbba029778)>. > (See http://perl5.test-smoke.org/report/96425.) > > Thank you very much. > Jim Keenan >
> On 10/28/19 8:45 AM, sisyphus wrote:> Thanks Jim. 1.999818 tests fine. IMO, this ticket can be closed. Cheers, Rob Thanks, I will do so once we see passing smoke tests.

Smoke tests look good, e.g., [this one](http://perl5.test-smoke.org/report/98096).  Closing issue.

Thank you very much.
Jim Keenan

**Closed as completed by jkeenan** 2019-11-01 11:55 UTC
Labels: Bug, distro-Linux, type-library
