### ISSUE TITLE
[doc] perlapi and perlxs are missing

### ISSUE THREAD

**Issue by robrwo** [Perl/perl5#20418] opened 2022-10-20 08:48 UTC
There used to be `perlapi` and `perlxs` documents. `perlguts` still links to them, but they seem to be missing.

Have they been renamed?

**Comment by haarg** [comment] 2022-10-20 09:17
These still exist, but they are generated at install time rather than existing in the tarball as individual files. This prevents them from being viewable on MetaCPAN, but they can be viewed on [perldoc.perl.org](https://perldoc.perl.org/perlapi).

**Comment by Grinnz** [comment] 2022-10-20 09:40
Duplicate of https://github.com/Perl/perl5/issues/13415

**Closed as completed by Grinnz** 2022-10-20 09:40 UTC
Labels: Needs Triage, documentation

**Comment by Grinnz** [comment] 2022-10-20 09:41
this is probably about viewing them on github, which has a similar issue to viewing them on metacpan. perlxs is not generated, but its source is in the ExtUtils::ParseXS dist: https://github.com/Perl/perl5/blob/blead/dist/ExtUtils-ParseXS/lib/perlxs.pod
