### ISSUE TITLE
perl-5.34.0 build error with test failed

### ISSUE THREAD

**Issue by yangmingtai** [Perl/perl5#20295] opened 2022-09-13 08:55 UTC
Module: Sys-Syslog、File/stat.t

**Description**

I get two error on test stage , we have log， but it is hard to reproduce it.
log: http://117.78.1.88:82/obs_build_log/openEuler:22.09/aarch64/perl/
1.
![image](https://user-images.githubusercontent.com/17870505/189857800-f9723318-8148-470c-a4de-dcf85db75c2e.png)
2.
![image](https://user-images.githubusercontent.com/17870505/189857619-8eb74935-04c6-4307-9309-6765371b1bae.png)

**Steps to Reproduce**

**Expected behavior**

**Perl configuration**

```
# perl -V output goes here
```

**Comment by yangmingtai** [comment] 2022-09-13 08:56
Summary of my perl5 (revision 5 version 34 subversion 0) configuration:

  Platform:
    osname=linux
    osvers=
    archname=aarch64-linux-thread-multi
    uname='linux '
    config_args='-des -Doptimize=none -Dccflags=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -Dldflags=-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld -Dccdlflags=-Wl,--enable-new-dtags -Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld -Dlddlflags=-shared -Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld -Dshrpdir=/usr/lib64 -DDEBUGGING=-g -Dversion=5.34.0 -Dmyhostname=localhost -Dperladmin=root@localhost -Dcc=gcc -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl5 -Dprivlib=/usr/share/perl5 -Dsitearch=/usr/local/lib64/perl5 -Dvendorlib=/usr/share/perl5/vendor_perl -Darchlib=/usr/lib64/perl5 -Dvendorarch=/usr/lib64/perl5/vendor_perl -Darchname=aarch64-linux-thread-multi -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Duseshrplib -Dusethreads -Duseithreads -Ui_ndbm -Di_gdbm -Dusedtrace=/usr/bin/dtrace -Ubincompat5005 -Dusesitecustomize -Duselargefiles -Dd_semctl_semun -Di_db -Duse64bitint -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dscriptdir=/usr/bin -Dinstallusrbinperl=n -Uversiononly -Dpager=/usr/bin/less -isr -Dd_gethostent_r_proto -Ud_endhostent_r_proto -Ud_sethostent_r_proto -Ud_endprotoent_r_proto -Ud_setprotoent_r_proto -Ud_endservent_r_proto -Ud_setservent_r_proto'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='  -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -fwrapv -fno-strict-aliasing -I/usr/local/include'
    ccversion=''
    gccversion='10.3.1'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=1
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags ='-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib64 /lib64 /usr/lib64 /usr/local/lib /usr/lib
    libs=-lpthread -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version='2.34'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld'
    cccdlflags='-fPIC'
    lddlflags='-shared -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_SITECUSTOMIZE
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Aug  6 2022 09:00:36
  @INC:
    /usr/local/lib64/perl5
    /usr/local/share/perl5
    /usr/lib64/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib64/perl5
    /usr/share/perl5

**Comment by yangmingtai** [comment] 2022-09-13 08:58
It may be the cause of system overload

**Comment by jkeenan** [comment] 2022-09-13 12:30
You are attempting to compile perl with a very large number of command-line switches to `./Configure`.  Your next task is to configure with the minimum number of command-line switches, build and run the test suite, and observe whether you reproduce these two test failures.  Example:
```
sh ./Configure -des -Dusedevel
```
If you get failures with such a simple configuration, then the cause of those failures is likely to be in your local environment -- not in perl, as `perl-5.34` has been built and tested on Linux many thousands of times by many people.

If you don't get failures, re-configure adding command-line switches until failures appear.  Report that data to us.

**Comment by tonycoz** [comment] 2022-09-14 01:25
> It may be the cause of system overload

I can see either of these tests failing under heavy load.

`lib/File/stat.t` could wait for the clock to tick over to the new second, but that would require a busy loop.

**Comment by jkeenan** [comment] 2022-09-16 19:37
> > It may be the cause of system overload
> 
> I can see either of these tests failing under heavy load.
> 
> `lib/File/stat.t` could wait for the clock to tick over to the new second, but that would require a busy loop.

I'm going to self-assign this ticket for the purpose of closing it within 7 days unless we hear back from @yangmingtai.

**Comment by jkeenan** [comment] 2022-09-24 21:12
> 
> I'm going to self-assign this ticket for the purpose of closing it within 7 days unless we hear back from @yangmingtai.

No response from O.P.  Closing as per schedule.

**Closed as completed by jkeenan** 2022-09-24 21:12 UTC
