### ISSUE TITLE
json_pp with no args warns 'Duplicate specification "V" for option "v"'

### ISSUE THREAD

**Issue by ahmogit** [Perl/perl5#22616] opened 2024-09-21 16:48 UTC
**Description**
Running json_pp with no args issues (harmless) diagnostic from Getopt::Long:

    Duplicate specification "V" for option "v"

Looks like it may be missing the "no_ignore_case" configuration option, i.e.

`   Getopt::Long::Configure('no_ignore_case');`

**Steps to Reproduce**
     $ json_pp

**Expected behavior**
    No diagnostic should issue, it should just wait for stdin.

**Perl configuration**

See attached output from perl -V.

[perl-V.txt](https://github.com/user-attachments/files/17085062/perl-V.txt)

**Comment by mauke** [comment] 2024-09-21 16:50
Duplicate of https://github.com/makamaka/JSON-PP/issues/88.

**Comment by ahmogit** [comment] 2024-09-21 16:57
OK, sorry for the noise. 

Before filing this report, I did search for "json_pp" in both open and closed issues in the perl/perl5 repo, but didn't see it listed. What was the right way to have searched for it in order to find that it had already been reported?

**Comment by mauke** [comment] 2024-09-21 17:02
The way I did it: I first looked where in the repo the `json_pp` file is located. I found it in `cpan/JSON-PP/bin`, which tells me it is maintained on CPAN in the JSON-PP distribution (everything under `cpan/` is maintained elsewhere and only imported into perl). JSON::PP is on metacpan as https://metacpan.org/pod/JSON::PP and has an "Issues" link (left sidebar) that leads to https://github.com/makamaka/JSON-PP/issues. There are only 7 open issues, so it was easy to find the report about "duplicate specification".

**Comment by ahmogit** [comment] 2024-09-21 17:16
OK, thanks for that info. 

The reasoning that led me to file the issue on the perl/perl5 tracker was simply that the json_pp executable is provided in the perl-5.40.0 distro package. I did not realize that perl5 pulled it, in turn, from cpan, so thanks for educating me on that.

**Closed as completed** 2024-09-21 17:50 UTC
Labels: Needs Triage
