### ISSUE TITLE
unable to set :isa in class declared with version

### ISSUE THREAD

**Issue by garu** [Perl/perl5#21283] opened 2023-07-23 02:51 UTC
**Description**

The `class` token support a `NAME VERSION` format, and handles inheritance via the `:isa()` attribute. However, one cannot use them together.

**Steps to Reproduce**

```perl
class A {} 
class B :isa(A) 1.0  { }
```

    > Invalid separator character '1' in attribute list

If the version is omitted (`class B :isa(A) { }`), it works fine.

**Expected behavior**

I understand how _"everything after the colon is an attribute"_ prevents the version number from being parsed. I believe this limitation should be explicitly documented in both `perlclass` and `perldoc -f class` including a workaround, or it should be possible to write it version-first, e.g.: ```class B 1.0 :isa(A) { ... }```. Right now this also yields an error:

    > Invalid version format (non-numeric data)

But I think that could be considered a parsing issue maybe?

Another workaround could be the addition of a `:version()` attribute, but I don't think it's necessary if the version can come first.

**Comment by haarg** [comment] 2023-07-23 03:35
Duplicate of #20891

**Closed as completed by haarg** 2023-07-23 03:35 UTC
Labels: Needs Triage
