### ISSUE TITLE
weird behaviour of `my` with assignment in false conditional 

### ISSUE THREAD

**Issue by dakkar** [Perl/perl5#21154] opened 2023-06-14 14:25 UTC
**Description**

The construct `my @a = 1 if $something` inside a sub, has surprising effects.
 

**Steps to Reproduce**

```perl
sub one {
    my @a = 1 if @_;
    return \@a
}

print one,"\n",one(1,2),"\n";
```

prints two identical lines.

See also https://gist.github.com/dakkar/bbfeb8514d8dbdf5208ecd99b699c2e2 for a test file.

**Expected behavior**

The script should either error out, prohibiting the construct, or it should print two different arrayrefs.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 38 subversion 0) configuration:
  Snapshot of: b263f63493f4649c2ac69e2dd054bc5b1ed87f6e
  Platform:
    osname=linux
    osvers=6.1.12-gentoo-x86_64
    archname=x86_64-linux-thread-multi
    uname='linux exelion 6.1.12-gentoo-x86_64 #2 smp preempt_dynamic sat feb 18 13:19:43 gmt 2023 x86_64 11th gen intel(r) core(tm) i7-1185g7 @ 3.00ghz genuineintel gnulinux '
    config_args='-de -Dprefix=/home/dakkar/perl5/perlbrew/perls/perl-blead -Dusethreads -Dusedevel -Aeval:scriptdir=/home/dakkar/perl5/perlbrew/perls/perl-blead/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='12.2.1 20230428'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /lib64 /usr/lib64 /lib /usr/local/lib64
    libs=-lpthread -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.36'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    RC0
  Built under linux
  Compiled at Jun 14 2023 14:48:18
  %ENV:
    PERLBREW_HOME="/home/dakkar/.perlbrew"
    PERLBREW_MANPATH="/home/dakkar/perl5/perlbrew/perls/perl-blead/man"
    PERLBREW_PATH="/home/dakkar/perl5/perlbrew/bin:/home/dakkar/perl5/perlbrew/perls/perl-blead/bin"
    PERLBREW_PERL="perl-blead"
    PERLBREW_ROOT="/home/dakkar/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.88"
    PERLBREW_VERSION="0.88"
    PERLDOC="-MPod::Text::Color::Delight"
  @INC:
    /home/dakkar/perl5/perlbrew/perls/perl-blead/lib/site_perl/5.38.0/x86_64-linux-thread-multi
    /home/dakkar/perl5/perlbrew/perls/perl-blead/lib/site_perl/5.38.0
    /home/dakkar/perl5/perlbrew/perls/perl-blead/lib/5.38.0/x86_64-linux-thread-multi
    /home/dakkar/perl5/perlbrew/perls/perl-blead/lib/5.38.0
```

**Comment by Grinnz** [comment] 2023-06-14 16:56
Duplicate of https://github.com/Perl/perl5/issues/15764 etc.

**Closed as completed by Grinnz** 2023-06-14 16:56 UTC
Labels: my-in-false-conditional
