### ISSUE TITLE
macOS Big Sur: failed test : array should contain one result or more: libc => () at t/DynaLoader.t

### ISSUE THREAD

**Issue by hakonhagland** [Perl/perl5#18406] opened 2020-12-17 14:12 UTC
When trying to install perl version 5.32.0 on macOS Big Sur I get a failed test:

```
perlbrew install perl-5.32.0
[...]
./ext/B/t/sv_stash.t .............................................. ok
../ext/B/t/terse.t ................................................. ok
../ext/B/t/walkoptree.t ............................................ ok
../ext/B/t/xref.t .................................................. ok
../ext/Devel-Peek/t/Peek.t ......................................... ok
# Failed test 20 - array should contain one result or more: libc => () at t/DynaLoader.t line 127
#      got "0"
# expected >= "1"
../ext/DynaLoader/t/DynaLoader.t ...................................
Failed 1/44 subtests
	(less 6 skipped subtests: 37 okay)
../ext/Errno/t/Errno.t ............................................. ok
../ext/Fcntl/t/autoload.t .......................................... ok
```
The issue was first reported [here]( https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/381). The issue seems to be that `Dynaloader::dl_findfile("c")` cannot find the path to `libc`, see https://github.com/Perl/perl5/blob/blead/ext/DynaLoader/t/DynaLoader.t#L114. This is because the file does not exist, see https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes :

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache.

**Comment by Leont** [comment] 2020-12-17 16:11
Can you try if #18407 fixes the issue?

**Comment by Leont** [comment] 2020-12-17 17:03
I have an experimental branch (#18407) to fix this, but given I'm not a mac user I can't easily verify if it works or not (though I might get the CI working on Big Sur)

**Comment by Leont** [comment] 2020-12-23 17:57
This has been fixed in d296ead16762852ec34d173616a271c856711f77 :-)

**Closed as completed by Leont** 2020-12-23 17:57 UTC
Labels: distro-darwin, type-OS-interaction

**Comment by dseddah** [comment] 2021-05-25 09:48
Hi,
on what Perl version is this fixed ? Do I need to install a special branch or something?

**Comment by Leont** [comment] 2021-05-25 16:00
> Hi,
> on what Perl version is this fixed ? Do I need to install a special branch or something?

5.32.1/5.34.0 fixed this

**Comment by aero** [comment] 2021-10-12 06:04
Hi,
I tried to install perl 5.32.1 on MacOS BigSur 11.6

```
$ perlbrew install perl-5.32.1 --as perl-5.32 --thread --noman
.
.
.
Result: FAIL
make: *** [test_harness] Error 1
##### Brew Failed #####
```
5.32.1 really fixed ?

**Comment by sdondley** [comment] 2022-01-06 21:53
Broken for me on monterey:

```
Test Summary Report
-------------------
op/fork.t                                                          (Wstat: 0 Tests: 28 Failed: 1)
  Failed test:  13
op/incfilter.t                                                     (Wstat: 0 Tests: 151 Failed: 0)
  Parse errors: Bad plan.  You planned 153 tests but ran 151.
../cpan/IPC-Cmd/t/03_run-forked.t                                  (Wstat: 256 Tests: 114 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
../dist/IO/t/io_pipe.t                                             (Wstat: 0 Tests: 9 Failed: 0)
  Parse errors: Tests out of sequence.  Found (9) but expected (8)
                Tests out of sequence.  Found (10) but expected (9)
                Bad plan.  You planned 10 tests but ran 9.
../ext/DynaLoader/t/DynaLoader.t                                   (Wstat: 0 Tests: 44 Failed: 1)
  Failed test:  20
Files=2668, Tests=1185036, 802 wallclock secs (61.89 usr 19.50 sys + 440.93 cusr 94.78 csys = 617.10 CPU)
Result: FAIL
make: *** [test_harness] Error 3
##### Brew Failed #####
```

And looking at the `etc/DynaLoader/DynaLoader.pm file`, it has the the https://github.com/Perl/perl5/commit/d296ead16762852ec34d173616a271c856711f77 patch.

**Comment by hakonhagland** [comment] 2022-01-06 22:30
@sdondley Did you run `perlbrew install-patchperl` first? See [this](https://stackoverflow.com/a/65332241/2173773) answer on stackoverflow

**Comment by sdondley** [comment] 2022-01-06 23:17
@hakonhagland yes. updated perlbrew and patchperl.

**Comment by sdondley** [comment] 2022-01-07 18:33
OK, the problem was due to my total idiocy having a script named `echo` in ~/bin. Disregard.

**Comment by zetalog** [comment] 2023-06-02 03:16
This still fails even when the patch is there.
Also I can see that the following code succeeds in a standalone script:

```
#!/usr/bin/perl -wT

use strict;
use Config;
use Test::More;

    my @files = ();
    eval { @files = DynaLoader::dl_findfile("c") };
    is( $@, '', "calling dl_findfile()" );
    # Some platforms are known to not have a "libc"
    # (not at least by that name) that the dl_findfile()
    # could find.
    skip "dl_findfile test not appropriate on $^O", 1
        if $^O =~ /(win32|vms|openbsd|cygwin)/i;
    # Play safe and only try this test if this system
    # looks pretty much Unix-like.
    skip "dl_findfile test not appropriate on $^O", 1
        unless -d '/usr' && -f '/bin/ls';
    cmp_ok( scalar @files, '>=', 1, "array should contain one result result or more: libc => (@files)" );
```
So this bug doesn't look root caused.
I encountered the problem in Windows WSL2.
```
Linux SurfaceBook2-B 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
This failure may be due to a wrongly detection of the unix system type.
And I can notice that this file is wrongly built during the build process:
```
NetWare/testnlm/echo/echo.c
```
