### ISSUE TITLE
op/exec.t failed test

### ISSUE THREAD

**Issue by aduitsis** [Perl/perl5#17515] opened 2020-01-31 22:22 UTC
Perl 5.30.1 fails test in macosx Mojave.

(first go to t/)
./perl op/exec.t

which returns
```
not ok 17
# Failed test 17 - at op/exec.t line 114
# $! eq 20, 'Not a directory'


```**Expected behavior**
Should pass the test.

**Perl configuration**

```
Cannot run perl -V, because it's not installed yet. Basically This is perl 5, version 30, subversion 1 (v5.30.1) built for darwin-2level
(with 1 registered patch, see perl -V for more detail)
```

**Comment by jkeenan** [comment] 2020-01-31 22:39
> Perl 5.30.1 fails test in macosx Mojave.
> 
> (first go to t/)
> ./perl op/exec.t
> 
> which returns
> 
> ```
> not ok 17
> # Failed test 17 - at op/exec.t line 114
> # $! eq 20, 'Not a directory'
> 
> 
> ```**Expected behavior**
> Should pass the test.
> 
> **Perl configuration**
> ```
> 
> Cannot run perl -V, because it's not installed yet. Basically This is perl 5, version 30, subversion 1 (v5.30.1) built for darwin-2level
> (with 1 registered patch, see perl -V for more detail)

If you got as far as the test suite (i.e., you ran `make test_prep` successfully), then you have an uninstalled `perl` in the top-level of your source tree.  What do you get for:
```
./perl -Ilib -V
```

**Comment by aduitsis** [comment] 2020-02-02 23:15
Here goes:

[perl version.txt](https://github.com/Perl/perl5/files/4145684/perl.version.txt)

**Comment by Leont** [comment] 2020-02-03 14:34
That is an odd error for not being able to execute a command, but it wouldn't be the first time mac gave us a odd error.

**Comment by aduitsis** [comment] 2020-02-03 15:48
Hey @Leont, extactly! Obviously I can extend the expected outcomes and pass the test. But I'd like to help improve. There is a strange command that does the test, `$rc = system { "lskdfj" } "lskdfj";`. What's the part inside the curly braces do? Perldoc is not too specific on using the curly braces with system.

**Comment by Leont** [comment] 2020-02-03 17:12
That passes the inner string as the zeroth argument to the command. It's not commonly used but occasionally useful. I would expect one would get the same error without it.

**Comment by aduitsis** [comment] 2020-02-03 20:35
Right, yes: 
`perl -E '$rc = system  "llll llll"; say $!'`
`Not a directory`

**Comment by aduitsis** [comment] 2020-02-04 18:47
Basically, this problem breaks a clean test under Mojave, so the typical cycle of e.g. Perlbrew breaks and cannot install Perl. I'm a little puzzled this hasn't popped up before. If this is not some peculiarity with my mac (shouldn't), I'd say we must fix it.

**Comment by PhilipSharman** [comment] 2020-04-09 02:11
For what it's worth, I'm getting the same error using Perlbrew to install 5.30.2 on OS X 10.13.6 (High Sierra).

**Comment by ilmari** [comment] 2020-04-09 15:44
I can reproduce this on Linux by appending an existent non-directory to `$PATH`, e.g. `$PWD/harness`. This makes sense, since `exec` calls `execve("$_/foo",...)` for each entry in `$PATH`, and that gives "not a directory" if a prefix of the path exists but is not a directory.

```
~/src/perl/t (blead)$ PATH=$PATH:$PWD/harness ./TEST op/exec.t 
t/op/exec ... # Failed test 17 - at op/exec.t line 114
# $! eq 20, 'Not a directory'
FAILED at test 17
```

**Comment by khwilliamson** [comment] 2020-04-09 18:13
You can try out https://github.com/Perl/perl5/pull/17704 for this problem

**Comment by khwilliamson** [comment] 2020-04-09 18:14
In the meantime, clean up your PATH, and things should work

**Comment by khwilliamson** [comment] 2020-05-28 01:06
This should now be fixed in blead.  Please verify.

**Comment by tonycoz** [comment] 2023-04-27 05:06
This fixes the linux test case for me, closing.

**Closed as completed by tonycoz** 2023-04-27 05:06 UTC
Labels: Closable?, Stalled
