### ISSUE TITLE
BBC: Blead Breaks RIBASUSHI/DBIx-Class-0.082842.tar.gz

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#19452] opened 2022-02-22 21:13 UTC
t/53lean_startup.t started to fail with perl 5.35.9:
```
#   Failed test 'Unexpected require of 'MRO::Compat' by DBIx::Class::Componentised (/usr/home/cpansand/.cpan/build/2022022220/DBIx-Class-0.082842-0/blib/lib/DBIx/Class/Componentised.pm line 7)'
#   at t/53lean_startup.t line 58.
# Looks like you failed 1 test of 7.
t/53lean_startup.t .................................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/7 subtests 
```

@ribasushi FYI

**Comment by haarg** [comment] 2022-02-22 22:04
This is caused by #19415, and was an expected failure after merging.

@Leont has provided [a patch for DBIx-Class](https://www.nntp.perl.org/group/perl.perl5.porters/2022/01/msg262394.html) which should fix this.

**Comment by Leont** [comment] 2022-02-22 22:09
I pull requested this as [#143](https://github.com/Perl5/DBIx-Class/pull/143)

**Comment by ribasushi** [comment] 2022-02-22 23:18
@eserte known, DBIC workaround will be shipped in couple weeks or so.

**Comment by rjbs** [comment] 2022-04-17 14:36
@ribasushi 👋🏽  perl 5.36.0 is notionally about 33 days away.  "Find out that new DBIx-Class shipped" is currently high up on the todos, and I can't quite todo it myself!  So this is my nudge for you about it.

**Comment by ribasushi** [comment] 2022-05-17 10:53
@rjbs workaround shipped to CPAN.

**Comment by jkeenan** [comment] 2022-05-17 17:26
> @rjbs workaround shipped to CPAN.

I was able to install this version against blead on both FreeBSD-12 and -13.  From -12:
```
$ ./bin/perl -v | head -2 | tail -1
This is perl 5, version 35, subversion 12 (v5.35.12 (v5.35.11-199-g5c201a0933)) built for amd64-freebsd-thread-multi
$ ./bin/perl -MDBIx::Class -E 'say $DBIx::Class::VERSION;'
0.082843
```

**Comment by jkeenan** [comment] 2022-06-09 01:42
> > @rjbs workaround shipped to CPAN.
> 
> I was able to install this version against blead on both FreeBSD-12 and -13. From -12:
> 
> ```
> $ ./bin/perl -v | head -2 | tail -1
> This is perl 5, version 35, subversion 12 (v5.35.12 (v5.35.11-199-g5c201a0933)) built for amd64-freebsd-thread-multi
> $ ./bin/perl -MDBIx::Class -E 'say $DBIx::Class::VERSION;'
> 0.082843
> ```

CPANtesters results good, e.g., http://matrix.cpantesters.org/?dist=DBIx-Class%200.082843;perl=5.37.1;reports=1

Closing.

**Closed as completed by jkeenan** 2022-06-09 01:42 UTC
Labels: BBC, sendToCPAN
