### ISSUE TITLE
aes.c: loadable library and perl binaries are mismatched (got handshake key 0x8140080, needed 0x8e80080)

### ISSUE THREAD

**Issue by SureshNadar1993** [Perl/perl5#19470] opened 2022-02-28 07:40 UTC
Hi All,

  We are trying to update the perl version from 5.28 to 5.32.1.

ENV Details
Oracle Linux Server release 7.9
NAME="Oracle Linux Server"
VERSION="7.9"
Red Hat Enterprise Linux Server release 7.9 (Maipo)

Steps Followed for installing perl.

export -n PATH
export -n LD_LIBRARY_PATH
export PATH=/usr/bin:/usr/local/bin:/bin

wget https://www.cpan.org/src/5.0/perl-5.32.1.tar.gz --no-check-certificate
tar -xzf perl-5.32.1.tar.gz
cd perl-5.32.1
./Configure -des -Dcc="gcc -m32" -Dusethreads -Duserelocatableinc -Dprefix=/scratch/ri-user-1/opt/perl-5.32.1/ 
make
make test
make install
export PATH=/scratch/ri-user-1/opt/perl-5.32.1/bin:$PATH
 
ISSUE DETAILS

Post Installation 
perl -v :- depicts perl 5.32.1
But while executing perl from application we get the below error.
aes.c: loadable library and perl binaries are mismatched (got handshake key 0x8140080, needed 0x8e80080)

Tried many suggestions online some being to unset PERL5LIB which didnt work .
After unsetting PERL5LIB we receive another error.
Can't locate aes.pm in @inc (you may need to install the aes module) (@inc contains: /scratch/ri-user-1/opt/perl-5.32.1/lib/site_perl/5.32.1/x86_64-linux-thread-multi /scratch/ri-user-1/opt/perl-5.32.1/lib/site_perl/5.32.1 /scratch/ri-user-1/opt/perl-5.32.1/lib/5.34.0/x86_64-linux-thread-multi /scratch/ri-user-1/opt/perl-5.32.1/lib/5.34.0) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

**Comment by Corion** [comment] 2022-02-28 08:55
The error message points to the problem that you are mixing Perl major versions. This is not supported by Perl.

You talk about Perl 5.28 and Perl 5.32, but the Perl you invoke is Perl 5.34:

    /scratch/ri-user-1/opt/perl-5.34.0/lib/site_perl/5.34.0

You can have multiple versions of Perl installed by using `-Dprefix`, but you need to make sure that they do install modules into different directories. For scripts that manage building, installing and invoking different Perl versions for you, see:

https://metacpan.org/dist/App-perlbrew

https://metacpan.org/dist/App-plx

https://github.com/tokuhirom/plenv

This seems to be not a bug in Perl but a bug with your specific installation.

**Edit**: Removed the word "not" from "do ~~not~~ install modules into different directories". Installing modules for different Perl versions into different directories is very important.

**Comment by demerphq** [comment] 2022-02-28 09:07
On Mon, 28 Feb 2022, 15:40 SureshNadar1993, ***@***.***>
wrote:

> Hi All,
>
> We are trying to update the perl version from 5.28 to 5.32.1.
>
> ENV Details
> Oracle Linux Server release 7.9
> NAME="Oracle Linux Server"
> VERSION="7.9"
> Red Hat Enterprise Linux Server release 7.9 (Maipo)
>
> Steps Followed for installing perl.
>
> export -n PATH
> export -n LD_LIBRARY_PATH
> export PATH=/usr/bin:/usr/local/bin:/bin
>
> wget https://www.cpan.org/src/5.0/perl-5.32.1.tar.gz
> --no-check-certificate
> tar -xzf perl-5.32.1.tar.gz
> cd perl-5.32.1
> ./Configure -des -Dcc="gcc -m32" -Dusethreads -Duserelocatableinc
> -Dprefix=/scratch/ri-user-1/opt/perl-5.32.1/
> make
> make test
> make install
> export PATH=/scratch/ri-user-1/opt/perl-5.32.1/bin:$PATH
>
> ISSUE DETAILS
>
> Post Installation
> perl -v :- depicts perl 5.32.1
> But while executing perl from application we get the below error.
> aes.c: loadable library and perl binaries are mismatched (got handshake
> key 0x8140080, needed 0x8e80080)
>
> Tried many suggestions online some being to unset PERL5LIB which didnt
> work .
> After unsetting PERL5LIB we receive another error.
> Can't locate aes.pm in @inc <https://github.com/inc> (you may need to
> install the aes module) ***@***.*** <https://github.com/inc> contains:
> /scratch/ri-user-1/opt/perl-5.34.0/lib/site_perl/5.34.0/x86_64-linux-thread-multi
> /scratch/ri-user-1/opt/perl-5.34.0/lib/site_perl/5.34.0
> /scratch/ri-user-1/opt/perl-5.34.0/lib/5.34.0/x86_64-linux-thread-multi
> /scratch/ri-user-1/opt/perl-5.34.0/lib/5.34.0) at -e line 1.
> BEGIN failed--compilation aborted at -e line 1
>
What was your perl5lib before you unset it?

Likely you need to rebuild whatever XS code is involved now that you have
upgraded. Off the top of my head I don't recognize aes.pm, cpan modules
usually don't look like that. Likely this is custom code that needs to
rebuilt against your new perl.

Also listen to Max maischeine, he has given some good advice.

Yves

>

**Comment by demerphq** [comment] 2022-02-28 09:09
On Mon, 28 Feb 2022, 16:56 Max Maischein, ***@***.***> wrote:

> The error message points to the problem that you are mixing Perl major
> versions. This is not supported by Perl.
>
> You talk about Perl 5.28 and Perl 5.32, but the Perl you invoke is Perl
> 5.34:
>
> /scratch/ri-user-1/opt/perl-5.34.0/lib/site_perl/5.34.0
>
> You can have multiple versions of Perl installed by using -Dprefix, but
> you need to make sure that they do not install modules into different
> directories.
>

I think that should either read "make sure they don't share/install into
the same directories" or "make sure the install into different directories"

Yves
Ps: Hi max, long time no talk!

>

**Comment by SureshNadar1993** [comment] 2022-02-28 10:45
Hi Team,
 
  There was a wrong info actual error post unsetting PERL5LIB is
After unsetting PERL5LIB we receive another error.
Can't locate aes.pm in @inc (you may need to install the aes module) (@inc contains: /scratch/ri-user-1/opt/perl-5.32.1/lib/site_perl/5.32.1/x86_64-linux-thread-multi /scratch/ri-user-1/opt/perl-5.32.1/lib/site_perl/5.32.1 /scratch/ri-user-1/opt/perl-5.32.1/lib/5.34.0/x86_64-linux-thread-multi /scratch/ri-user-1/opt/perl-5.32.1/lib/5.34.0) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

The perl versions are not mismatching and moreover the old version of perl is installed in a different directory 
/scratch/ri-user-1/opt/perl-5.28.0 we tried removing the directory as well.

Regards
Suresh

**Comment by Corion** [comment] 2022-02-28 10:50
This is not a bug with Perl but a bug with your installation. Did you install `aes.pm` with the correct version of Perl? You can verify that `aes.pm` is installed by running

find . -name 'aes.pm' /scratch/ri-user-1/opt/perl-5.32.1/lib/5.34.0

Your setup is very weird, mixing Perl version names:

```
/scratch/ri-user-1/opt/perl-5.32.1/lib/site_perl/5.32.1 
/scratch/ri-user-1/opt/perl-5.32.1/lib/5.34.0/x86_64-linux-thread-multi 
```

Mixing version numbers in the library directories is not recommended.

This is not a bug with Perl but with your setup. If you continue to have problems, consider moving this discussion to [https://perlmonks.org] or StackOverflow for further discussion.

**Closed as completed by Corion** 2022-02-28 10:50 UTC

**Comment by SureshNadar1993** [comment] 2022-02-28 11:05
Na
