### ISSUE TITLE
BBC: Blead Breaks Return::MultiLevel

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#18057] opened 2020-08-12 04:20 UTC
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.33.1.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Return::MultiLevel

Please see http://fast-matrix.cpantesters.org/?dist=Return-MultiLevel

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.33.1:

Configured by cpan at Sun Aug  9 22:09:21 EDT 2020.

Summary of my perl5 (revision 5 version 33 subversion 1) configuration:
  Commit id: 55507ac1d99efa7f407df8ebcf9f6683532679f8
  Platform:
    osname=openbsd
    osvers=6.7
    archname=OpenBSD.amd64-openbsd
    uname='openbsd cjg-openbsd6 6.7 generic#5 amd64 '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible OpenBSD Clang 8.0.1 (tags/RELEASE_801/final)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-Wl,-E  -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lpthread -lm -lutil -lc
    perllibs=-lpthread -lm -lutil -lc
    libc=/usr/lib/libc.so.96.0
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags='-DPIC -fPIC '
    lddlflags='-shared -fPIC  -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.33.1:
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.1/OpenBSD.amd64-openbsd
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.1
    /home/cpan/bin/perl-blead/lib/5.33.1/OpenBSD.amd64-openbsd
    /home/cpan/bin/perl-blead/lib/5.33.1

---
Environment for perl 5.33.1:
    HOME=/home/cpan
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/home/cpan/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

**Comment by atoomic** [comment] 2020-08-12 14:59
extract from http://www.cpantesters.org/cpan/report/adfff670-da10-11ea-bc97-01b83032318f
at first glance it seems that regexp fail due to a missing ` \bducks\b`, need to investigate

```
------------------------------
PROGRAM OUTPUT
------------------------------

Output from '/usr/bin/make test':

PERL_DL_NONLAZY=1 "/tmp/basesmoker-reloperl-Npp3/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
# Testing Return::MultiLevel 0.05 (XS), Perl 5.033001, /tmp/basesmoker-reloperl-Npp3/bin/perl
t/00-load.t .. ok
t/basic.t .... ok

#   Failed test at t/debug.t line 36.
#                   'Captured stack:
# Original call to with_return at t/debug.t line 14.
# 	main::foo() called at t/debug.t line 19
# 	main::bar() called at t/debug.t line 27
# 
# Attempt to re-enter dead call frame at /tmp/loop_over_bdir-1644221-AKT23o/Return-MultiLevel-0.05-0/blib/lib/Return/MultiLevel.pm line 27.
# 	Return::MultiLevel::__ANON__(...) called at t/debug.t line 24
# 	main::baz(...) called at t/debug.t line 28
# 	main::__ANON__(...) called at /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.33.0-217-g55507ac1d9/af11/lib/site_perl/5.33.1/Test/Fatal.pm line 158
# 	Test::Fatal::try {...} (...) called at /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.33.0-217-g55507ac1d9/af11/lib/site_perl/5.33.1/Try/Tiny.pm line 100
# 	eval {...} called at /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.33.0-217-g55507ac1d9/af11/lib/site_perl/5.33.1/Try/Tiny.pm line 93
# 	Try::Tiny::try(...) called at /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.33.0-217-g55507ac1d9/af11/lib/site_perl/5.33.1/Test/Fatal.pm line 165
# 	Test::Fatal::exception(...) called at t/debug.t line 28
# '
#     doesn't match '(?^x:
#     .* \bReturn::MultiLevel\b .* \bducks\b .* t\/debug\.t .* \b 24 \b .* \n
#     .* \bbaz\b                .* \bducks\b .* t\/debug\.t .* \b 28 \b .* \n
# )'
# Looks like you failed 1 test of 2.
t/debug.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
t/nested.t ... ok

Test Summary Report
-------------------
t/debug.t  (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=4, Tests=9,  1 wallclock secs ( 0.02 usr  0.02 sys +  0.15 cusr  0.07 csys =  0.26 CPU)
Result: FAIL
Failed 1/4 test programs. 1/9 subtests failed.
make: *** [Makefile:898: test_dynamic] Error 255
```

**Comment by jkeenan** [comment] 2020-09-01 00:30
I tried bisecting this using invocations like this:
```
perl Porting/bisect.pl --start=v5.32.0 \
--end=1af90cb1357f01e9a14be20028c45c6af8313690 \
--module=Return::MultiLevel
```
But I ended with output like this:
```
Test Summary Report
-------------------
t/debug.t  (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=4, Tests=9,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.32 cusr  0.02 csys =  0.38 CPU)
Result: FAIL
Failed 1/4 test programs. 1/9 subtests failed.
Makefile:899: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
  MAUKE/Return-MultiLevel-0.05.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MAUKE/Return-MultiLevel-0.05.tar.gz
Died at -e line 2.
HEAD is now at 0cf01644e9 add new release to perlhist
bad - non-zero exit from /tmp/b9NiEATlFi/bin/perl -I /home/jkeenan/.cpan -MCPAN::MyConfig -MCPAN -e $CPAN::Config->{build_dir}=q{/tmp/yOuytqYDOu}; -e install('Return::MultiLevel'); die unless CPAN::Shell->expand(Module => 'Return::MultiLevel')->uptodate;
Runner returned 256, not 0 for start revision at Porting/bisect.pl line 240.
```
In my experience, that message, `Runner returned 256, not 0 for start revision at Porting/bisect.pl line 240.`, usually means that I didn't go far enough back into the past to get a value for `--start`.  However, in this case, the value for `--start` precedes all those listed in [these published smoke-test reports](http://matrix.cpantesters.org/?dist=Return-MultiLevel;os=linux;perl=5.33.1;reports=1).  Moreover, using `cpanm` I can install Return::MultiLevel against perl-5.32.0.

So I haven't been able to identify a first bad commit.

Thank you very much.
Jim Keenan

**Comment by hvds** [comment] 2020-09-01 01:35
> I tried bisecting [...]
> So I haven't been able to identify a first bad commit.

I'll try to look at this tomorrow if nobody gets there first.

Hugo

**Comment by hvds** [comment] 2020-09-01 17:01
> > I tried bisecting [...]
> > So I haven't been able to identify a first bad commit.
> 
> I'll try to look at this tomorrow if nobody gets there first.

Well I tried, but have not so far managed to get it to fail, I just get:
```
t/00-load.t .. 1/1 # Testing Return::MultiLevel 0.05 (PP), Perl 5.033002, /opt/scratch/bin/perl
t/00-load.t .. ok   
t/basic.t .... ok   
t/debug.t .... ok   
t/nested.t ... ok   
All tests successful.
Files=4, Tests=9,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.11 cusr  0.00 csys =  0.13 CPU)
Result: PASS
```

That's with a default perl build, similar to a linux failure from the test matrix (http://www.cpantesters.org/cpan/report/4e43594c-e588-11ea-8360-236559b55d5b), and then installing Try-Tiny-0.30, Test-Fatal-0.014, Test-Warnings-0.026, Data-Munge-0.097 before attempting to build Return-MultiLevel - not necessarily latest versions, but what I have handy.

Looking at @atoomic's output, the issue appears to be down to whether the stack trace shows arguments to calls or just `...`, the `$exc` when I run the test file is:
```
Original call to with_return at t/debug.t line 14.
        main::foo() called at t/debug.t line 19
        main::bar() called at t/debug.t line 27

Attempt to re-enter dead call frame at /src/perl/Return-MultiLevel-0.05/blib/lib/Return/MultiLevel.pm line 86.
        Return::MultiLevel::__ANON__("ducks") called at t/debug.t line 24
        main::baz(CODE(0x55fffabde3e0), "ducks") called at t/debug.t line 28
        main::__ANON__() called at /opt/scratch/lib/perl5/site_perl/5.33.2/Test/Fatal.pm line 129
        Test::Fatal::try {...} () called at /opt/scratch/lib/perl5/site_perl/5.33.2/Try/Tiny.pm line 100
        eval {...} called at /opt/scratch/lib/perl5/site_perl/5.33.2/Try/Tiny.pm line 93
        Try::Tiny::try(CODE(0x55fffa50d008), Try::Tiny::Catch=REF(0x55fffab7a868)) called at /opt/scratch/lib/perl5/site_perl/5.33.2/Test/Fatal.pm line 136
        Test::Fatal::exception(CODE(0x55fffa50d020)) called at t/debug.t line 28
```

It might be worth somebody that can reproduce it experimenting with `$Carp::MaxArgLen = $Carp::MaxArgNums = 0` just in case something is going screwy there - I assume Carp::caller_info is where we're diverging.

**Comment by pghmcfc** [comment] 2020-09-03 19:19
Does mauke/Return-MultiLevel/pull/1 fix this?

**Comment by hvds** [comment] 2020-09-03 21:57
> Does [mauke/Return-MultiLevel/pull/1](https://github.com/mauke/Return-MultiLevel/pull/1) fix this?

Ah, from the description it sounds highly likely that it will - note that in my failed attempt to reproduce I had Test-Fatal-0.14.

**Comment by jkeenan** [comment] 2021-02-11 02:32
> > Does [mauke/Return-MultiLevel/pull/1](https://github.com/mauke/Return-MultiLevel/pull/1) fix this?
> 
> Ah, from the description it sounds highly likely that it will - note that in my failed attempt to reproduce I had Test-Fatal-0.14.

Since the problem is upstream and two different pull requests have been submitted to the upstream maintainer, I think we can close this ticket.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment] 2021-02-20 02:41
> > > Does [mauke/Return-MultiLevel/pull/1](https://github.com/mauke/Return-MultiLevel/pull/1) fix this?
> > 
> > 
> > Ah, from the description it sounds highly likely that it will - note that in my failed attempt to reproduce I had Test-Fatal-0.14.
> 
> Since the problem is upstream and two different pull requests have been submitted to the upstream maintainer, I think we can close this ticket.
> 
> Thank you very much.
> Jim Keenan

No one has offered a reason to keep this ticket open, so I am closing it now.

**Closed as completed by jkeenan** 2021-02-20 02:41 UTC
Labels: BBC, sendToCPAN
