### ISSUE TITLE
NetBSD 8.1 and failure in "Updating 'mktables.lst'"

### ISSUE THREAD

**Issue by noloader** [Perl/perl5#17541] opened 2020-02-07 03:17 UTC
**Description**
I'm working on NetBSD 8.1 x86_64. I'm building the 5.30.1 release tarball. I'm encountering the issue discussed in [Intermittent failures in 'make' at "Updating 'mktables.lst'"](https://www.nntp.perl.org/group/perl.perl5.porters/2016/09/msg239501.html). It looks [fairly popular](https://www.google.com/search?q=perl+fail+Updating+'mktables.lst') for the folks who encounter it.

**Steps to Reproduce**
```
./Configure des ...
make -j 4
```

You may need to install `gmake` and set `MAKE=gmake`. I always use GNU Make if available, and it is installed on this NetBSD box:

```
$ command -v gmake
/usr/pkg/bin/gmake
```

**Expected behavior**
A quick build with `make -j 4` :)

Dropping back to `make -j 1` clears the issue.

**Some analysis**
I've experienced this issue with GNU Make in the past. It manifests itself like this in the Makefile:

```
some_recipe:
    ./update-mktables-pre.sh
    ./update-mktables.sh
    ./update-mktables-post.sh
```

Make will start all three update scripts at once. Sometimes `update-mktables.sh` runs before `update-mktables-pre.sh`, sometimes `update-mktables-post.sh` runs earlier then expected.

The way to fix it is unrolling the recipe:

```
some_recipe: update-mktables-post

update-mktables-post: update-mktables
    ./update-mktables-post.sh

update-mktables: update-mktables-pre
    ./update-mktables.sh

update-mktables-pre:
    ./update-mktables-pre.sh
```

I suspect (but don't know) the race has something to do with filesystem I/O. I first encountered it in a recipe like:

```
install:
    mkdir -p $(PREFIX)/bin $(PREFIX)/lib $(PREFIX)/include
    cp *.h $(PREFIX)/include
    cp *.so $(PREFIX)/lib
    cp *.exe $(PREFIX)/bin
    ...
```

The problem (in my case) was the `cp *.h` was running before the `mkdir -p` created `$(PREFIX)/include`, which caused the recipe to fail. The fix was:

```
install: install_dirs
    cp *.h $(PREFIX)/include
    cp *.so $(PREFIX)/lib
    cp *.exe $(PREFIX)/bin
    ...

install_dirs:
    mkdir -p $(PREFIX)/bin $(PREFIX)/lib $(PREFIX)/include
```

Perl devs may be able to troubleshoot the issue by setting `SHELL = /bin/bash -x` in the makefile. Bash should trace the calls which reveal the race. That's how I learned `cp *.h $(PREFIX)/include` was running before `mkdir -p`.

If you are on a BSD machine, be sure to check the location of bash before hard-coding a path like `/bin/bash`:

```
$ command -v bash
/usr/pkg/bin/bash
```

**Perl configuration**
Not yet available. Using the release tarball.

**Comment by doughera88** [comment] 2020-02-13 01:46
What are the actual errors you are seeing in the make output?  It's not obvious that this has anything to do with mktables.  To give a specific example, I introduced an error in cpan/Time-Piece/Piece.xs so that it wouldn't compile correctly.  I then ran a parallel make (using Berkeley make) and the last few lines of the output were:

> Finishing processing Unicode properties
> Compiling Perl properties
> Creating Perl synonyms
> Writing tables
> Making pod file
> Making test script
> Updating 'mktables.lst'
> 8 errors

Since mktables takes a long time to run, it was the last command to finish, but the errors actually happened much earlier in the process.  The '8 errors' report is a report from "make", not a report from the mktables program.

In order to make further progress, we'll need to know what errors were reported earlier in the make process.

**Comment by doughera88** [comment] 2020-02-26 15:43
Absent further information, I'm inclined to mark this issue as stalled.  The actual issue likely has nothing to to with mktables.  There may well be issues with parallel builds, but I have been unable to reproduce them and there is insufficient information here to do anything further.

**Comment by noloader** [comment] 2020-02-26 15:46
> but I have been unable to reproduce them and there is insufficient information here to do anything further

For completeness, I provided all the information I have.

Did you setup a NetBSD VM and try to run `make -j 4` with `MAKE=gmake`?

**Comment by doughera88** [comment] 2020-02-26 18:29
On Wed, Feb 26, 2020 at 07:46:27AM -0800, Jeffrey Walton wrote:
> > but I have been unable to reproduce them and there is insufficient information here to do anything further
> 
> For completeness, I provided all the information I have.

That information did not include any actual errors.  We can not
guess what command might have failed or what the actual error might
have been.

> Did you setup a NetBSD VM and try to run `make -j 4` with `MAKE=gmake`?

Almost.  I did run "make -j 4" on a NetBSD system.  I did not add
'MAKE=gmake' because it might be a bad idea to mix BSD and GNU make that
way.  A command like

    make -j 4 MAKE=gmake

would start the process with BSD make, but might use gmake for subsequent
invocations.  That can lead to problems since the two are not completely
compatible.  See issue #17543 for an example.

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Perl/perl5/issues/17541#issuecomment-591494315

-- 
    Andy Dougherty		doughera@lafayette.edu

**Comment by tonycoz** [comment] 2020-02-27 00:21
> I've experienced this issue with GNU Make in the past. It manifests itself like this in the Makefile:
> 
> ```
> some_recipe:
>     ./update-mktables-pre.sh
>     ./update-mktables.sh
>     ./update-mktables-post.sh
> ```
> 
> Make will start all three update scripts at once. Sometimes `update-mktables.sh` runs before `update-mktables-pre.sh`, sometimes `update-mktables-post.sh` runs earlier then expected.

From the GNU make documentation:

````
The recipe of a rule consists of one or more shell command lines to be
executed, one at a time, in the order they appear.  Typically, the
result of executing these commands is that the target of the rule is
brought up to date.
````

Your problem isn't caused by the commands in the rule being executed out of order, your ticket is the first time I've ever heard such a claim for any make, let alone GNU make.

**Comment by doughera88** [comment] 2020-03-05 12:44
On Wed, Feb 26, 2020 at 04:21:06PM -0800, Tony Cook wrote:

> Your problem isn't caused by the commands in the rule being executed out of order, your ticket is the first time I've ever heard such a claim for any make, let alone GNU make.
> 

Correct.  There is no multi-line recipe like this for mktables.  Also,
guessing from the linked bug report, the process was probably run by BSD make,
not GNU make.  Finally, the error probably has nothing to do with mktables
anyway.  The error message, "1 error",  merely indicates that 1 error
occurred somewhere earlier in the build. It doesn't tell you what it was.

There was some problem somewhere, but we don't know what it was.
I recommend we close this issue.  If the problem recurs, a new issue
should be opened with the text of the actual error message.

-- 
    Andy Dougherty		doughera@lafayette.edu

**Closed as completed** 2020-03-05 14:38 UTC
