### ISSUE TITLE
Recent commit be8790133a0 breaks quadmath support on Cygwin

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17708] opened 2020-04-10 19:00 UTC
_[Transferred from p5p mailing list; submitted by Peter John Acklam.]_

Hi everyone,

Because of a recent commit, I am no longer able to build Perl with
quadmath support on Cygwin. Version 5.31.9 builds just fine, so after a
"git bisect", I found the bad commit. I have little idea about what
it does, so I have no idea why it causes "make" to fail, but anyway,
here is the bad commit:
```
    be8790133a0ce8fc67454e55e7849a47a0858d32 Allow more debugging in re_comp.c
```
Below is the end of the output from "make":
```
cp ../../dquote.c dquote.c
gcc -c   -DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_FORTIFY_SOURCE=2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -Wno-format -DUSEIMPORTLIB -O3   -DVERSION=\"0.38\" -DXS_VERSION=\"0.38\"  "-I../.."  -DPERL_EXT_RE_BUILD -DPERL_EXT_RE_DEBUG -DPERL_EXT re_comp.c
"../../miniperl.exe" "-I../../lib" "../../lib/ExtUtils/xsubpp" -noprototypes -typemap '/cygdrive/c/share/repos/public/github.com/Perl/20200302T184521Z-be8790133a/src/ext/re/../../lib/ExtUtils/typemap'  re.xs > re.xsc
mv re.xsc re.c
gcc -c   -DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_FORTIFY_SOURCE=2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -Wno-format -DUSEIMPORTLIB -O3   -DVERSION=\"0.38\" -DXS_VERSION=\"0.38\"  "-I../.."  -DPERL_EXT_RE_BUILD -DPERL_EXT_RE_DEBUG -DPERL_EXT re.c
rm -f ../../lib/auto/re/re.dll
g++  --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -L/usr/local/lib  re_exec.o re_comp.o re.o  -o ../../lib/auto/re/re.dll  \
  ../../cygperl5_31_10.dll    \

/usr/bin/ld: re_comp.o:re_comp.c:(.text+0x2d9e4): undefined reference to `ceilq'
re_comp.o:re_comp.c:(.text+0x2d9e4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ceilq'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:479: ../../lib/auto/re/re.dll] Error 1
make[1]: Leaving directory '/cygdrive/c/share/repos/public/github.com/Perl/20200302T184521Z-be8790133a/src/ext/re'
make[1]: Entering directory '/cygdrive/c/share/repos/public/github.com/Perl/20200302T184521Z-be8790133a/src/ext/re'
/cygdrive/c/share/repos/public/github.com/Perl/20200302T184521Z-be8790133a/src/ext/re/../../miniperl.exe "-I../../lib" -MExtUtils::Command::MM -e 'cp_nonempty' -- re.bs ../../lib/auto/re/re.bs 644
rm -f ../../lib/auto/re/re.dll
g++  --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -L/usr/local/lib  re_exec.o re_comp.o re.o  -o ../../lib/auto/re/re.dll  \
  ../../cygperl5_31_10.dll    \

/usr/bin/ld: re_comp.o:re_comp.c:(.text+0x2d9e4): undefined reference to `ceilq'
re_comp.o:re_comp.c:(.text+0x2d9e4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ceilq'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:479: ../../lib/auto/re/re.dll] Error 1
make[1]: Leaving directory '/cygdrive/c/share/repos/public/github.com/Perl/20200302T184521Z-be8790133a/src/ext/re'
Unsuccessful make(ext/re): code=512 at make_ext.pl line 587.
make: *** [GNUmakefile:579: lib/auto/re/re.dll] Error 2
```

**Comment by jkeenan** [comment] 2020-04-10 19:03
@pjacklam : made this a git issue.

**Comment by hvds** [comment] 2020-04-11 10:49
> be8790133a0ce8fc67454e55e7849a47a0858d32 Allow more debugging in re_comp.c

How very strange: the reference to Perl_ceil has been in regcomp.c since 2018 (cef721997e), this commit just remove the `#ifndef PERL_IN_XSUB_RE` around it so it is now _also_ compiled in re_comp.c.

**Comment by pjacklam** [comment] 2020-04-11 16:50
I got a tip from @sisyphus about what was wrong, so I was able to patch the sources so that Perl again builds on Cygwin with quadmath support.

Note that this patch is essentially the same as 291c057a714c4bb419e91e8b00039d61390c42f9. Because of this, I have a feeling that these two patches reveal an underlying problem related to Perl not including the quadmath library everywhere it should, but I don't know enough about libraries and linking and the Perl build process to be certain. Anway, the "make" step succeeds with this patch.

[0001-Add-quadmath-to-list-of-libraries.txt](https://github.com/Perl/perl5/files/4464943/0001-Add-quadmath-to-list-of-libraries.txt)

**Comment by jkeenan** [comment] 2020-04-11 17:11
> I got a tip from @sisyphus about what was wrong, so I was able to patch the sources so that Perl again builds on Cygwin with quadmath support.
> 
> Note that this patch is essentially the same as [291c057](https://github.com/Perl/perl5/commit/291c057a714c4bb419e91e8b00039d61390c42f9). Because of this, I have a feeling that these two patches reveal an underlying problem related to Perl not including the quadmath library everywhere it should, but I don't know enough about libraries and linking and the Perl build process to be certain. Anway, the "make" step succeeds with this patch.
> 
> [0001-Add-quadmath-to-list-of-libraries.txt](https://github.com/Perl/perl5/files/4464943/0001-Add-quadmath-to-list-of-libraries.txt)

So, if we stepped back and tried to formulate a generalized version of this problem, would the following be accurate?

_"In one particular environment (the Cygwin simulation of Unix on MSWin32), when we attempt to do a "quadmath build" -- `-Dusequadmath` -- we have to add the `quadmath` library to the list of libraries in the `Makefile.PL` for two specific extensions under `ext/` -- but not to other Makefile.PL instances."_

Which leads me to wonder:

* If so, why **only** the Makefile.PLs for ext/re/ and ext/POSIX/?  After all, there are over 60 Makefile.PLs in the core distribution?
* Would the patch in 291c057 and the one @pjacklam has suggested above be better off in `hints/cygwin.sh`?

**Comment by sisyphus** [comment] 2020-04-12 03:34
I speculate that ext/re and ext/POSIX are the only two extensions in ext that contain symbols that need to be resolved by libquadmath - and that other extensions therefore have no need to link to libquadmath.

The thing that puzzled me is that this need for ext/re to explicitly link to libquadmath arises only when we get to perl-5.31.10.
Yet, in both, 5.31.9 and 5.31.10, re_comp.c is making the same call to "Perl_ceil" (which is defined to "ceilq" on quadmath builds).
So why has this change to the Makefile.PL become necessary only with the arrival of 5.31.10 ?

WRT 5.31.9, I concluded that either:
a) Perl_ceil was defined to something other than ceilq;
or
b) the Perl_ceil call in re_comp.c was not visible to the -Dusequadmath build on Cygwin;
or
c) the link to libquadmath was being provided by some other means.

IIUC, Karl's comment above tells us that b) is the case - ie that the Perl_ceil call in ext/re/re_comp.c does not become visible until perl-5.31.10.

If that's so then it makes sense that there is now a need to provide the explicit libquadmath link in ext/re/Makefile.PL for Cygwin.
If POSIX needs that explicit link to resolve it's quadmath functions then it's not surprising that other modules in ext would need that same explicit link if they also contain one or more quadmath functions.

Cheers,
Rob

**Comment by xsawyerx** [comment] 2020-04-15 18:29
@hvds Do you agree with the assessment above? Should we just update the Makefile.PL?

**Comment by jkeenan** [comment] 2020-04-15 18:33
> @hvds Do you agree with the assessment above? Should we just update the Makefile.PL?

Also, @khwilliamson have you had a chance to look at this one?

Thank you very much.
Jim Keenan

**Comment by hvds** [comment] 2020-04-15 19:02
> @hvds Do you agree with the assessment above? Should we just update the Makefile.PL?

What changed is that an #ifdef around the relevant code in regcomp.c changed, so that now it is compiled as part of re_comp.c where before it was #ifdef'd out.

I don't know anything about how libraries are included for modules - I had assumed they'd all be built with the same libs as perl itself. I expect @tonycoz would know more about that, but if the Makefile.PL update works that's probably the correct thing to do.

**Comment by tonycoz** [comment] 2020-04-16 00:18
I've had a go at reproducing this, but wasn't able to get Configure to detect the quadmath library on two different machines, though building a simple test file with `-lquadmath` works fine.

I'll have another go at this today.

**Comment by tonycoz** [comment] 2020-04-16 01:54
I think is the real fix is for EU::MM to include $Config{libs} when linking extensions, just as Win32 does.

This would allow POSIX, re, and any other CPAN XS code that blindly calls ceil(), floor() etc to link correctly with a quadmath build.

If Cygwin had a separate -lm this would be a much more obvious problem since such calls would have failed for default builds, but it doesn't, so the problem was hidden.

I could see issues if someone were to link in a debug malloc library for example, since the perl executable/shared library would be linked to the library, while extensions would use the default cygwin implementation.

On Linux the extensions will resolve symbols from already loaded libraries, and since perl (or libperl.so) links to libquadmath the symbols are properly resolved, on Win32 the symbols have to be resolved at link time, which$^O eq MSWin32 builds do, but Cygwin builds don't.

**Comment by pjacklam** [comment] 2020-04-16 13:16
@tonycoz wrote
> I've had a go at reproducing this, but wasn't able to get Configure to detect the quadmath library on two different machines, though building a simple test file with `-lquadmath` works fine.

I've had the same experience. Configure has never been able to detect the quadmath library, when I use Cygwin's standard compiler. My solution is to build gcc from source and use the resulting compiler.

Comparing the standard Cygwin compiler with the one I built from source, I see that they both include the following quadmath-related files
```
PREFIX/bin/cygquadmath-0.dll
PREFIX/lib/gcc/x86_64-pc-cygwin/9.3.0/include/quadmath.h
PREFIX/lib/gcc/x86_64-pc-cygwin/9.3.0/include/quadmath_weak.h
```
but the following files are only in the compiler I built from source, not in Cygwin's standard compiler:
```
PREFIX/lib/libquadmath.a
PREFIX/lib/libquadmath.dll.a
PREFIX/lib/libquadmath.la
```
I am no expert on this, but I assume this is related to the issue with Configure not detecting the quadmath library on Cygwin,

**Comment by tonycoz** [comment] 2020-04-17 03:39
I ended up getting it to build with:
```
./Configure -des -Dusedevel -Dusequadmath -Dloclibpth=/usr/lib/gcc/x86_64-pc-cygwin/9.3.0
```
well, configure, the build failed as described in the OP.

**Comment by jkeenan** [comment] 2020-04-17 11:06
On 4/16/20 11:39 PM, Tony Cook wrote:
> I ended up getting it to build with:
> 
> |./Configure -des -Dusedevel -Dusequadmath 
> -Dloclibpth=/usr/lib/gcc/x86_64-pc-cygwin/9.3.0 |
> 

'loclibpth' is found in many of the hints/*.sh files, but not in cygwin's.

#####
[perl] $ ack loclibpth hints/cygwin.sh
[perl] $
#####

So that might be the place to make a fix.

**Comment by khwilliamson** [comment] 2020-04-25 13:34
What are we waiting for?

**Comment by xsawyerx** [comment] 2020-04-26 06:32
I'm also not sure.

**Comment by pjacklam** [comment] 2020-04-26 08:00
I attached a working patch to a posting earlier in this discussion. Perhaps
it could be used at least until someone comes up with a better fix.

>

**Comment by khwilliamson** [comment] 2020-04-26 15:06
I think the answer is the hints file  But do we want a specific version in the file? @tonycoz

**Comment by tonycoz** [comment] 2020-05-12 04:04
There's been two issues discussed in this ticket:

1. the issue reported in the OP, that re isn't linking to quadmath resulting in link time errors, even when Configure is convinced it exists.
2. that Configure doesn't find quadmath by default on cygwin.

I'll open a new ticket for the second.

Given we want to release 5.32 soonish I think we should apply @pjacklam's patch and remove this as a blocker, but not close it.

I think the final fix needs to be in EU::MM, similar to the second commit in #17708 (but not the first commit, which is a bad fix for 2. above), but I'm hesitant to apply that this late in the release process.

**Comment by xsawyerx** [comment] 2020-05-20 21:49
Agreed. Does anyone object to Tony's suggestion?

To reiterate:

> Given we want to release 5.32 soonish I think we should apply @pjacklam's patch and remove this as a blocker, but not close it.

**Comment by xsawyerx** [comment] 2020-05-24 19:17
Created the PR at #17803. Will be merging within an hour unless it fails or anyone objects. Also running the test suite locally on the branch.

**Comment by xsawyerx** [comment] 2020-05-25 07:17
@tonycoz Perhaps opening a fresh ticket on what we still want to do with this  would be easier than continuing to use this. What do you think?

Meanwhile, I removed this from blocking.

**Comment by tonycoz** [comment] 2020-05-26 00:43
Done as #17805, closing this one.

**Closed as completed by tonycoz** 2020-05-26 00:43 UTC
Labels: distro-cygwin
