### ISSUE TITLE
BBC: Sys-Proctitle-0.04 does not compile anymore

### ISSUE THREAD

**Issue by andk** [Perl/perl5#20088] opened 2022-08-13 17:57 UTC
**Description**

With `v5.35.1-108-g7169efc775` the cpan pkg `OPI/Sys-Proctitle-0.04.tar.gz` stopped compiling on all of my smokers. Bisect lead me to:
``` text
 commit 7169efc77525df70484a824bff4ceebd1fafc760
 Author: Tony Cook <tony@develop-help.com>
 Date:   Thu Jul 15 13:13:03 2021 +1000
 
     skip using gcc brace groups for STMT_START/END
```

**Steps to Reproduce**

`cpan -i OPI/Sys-Proctitle-0.04.tar.gz`

**Expected behavior**

It should build, test, and install the pkg 

Instead I get output like:
``` text
cc -c  -I. -D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"0.04\" -DXS_VERSION=\"0.04\" -fPIC "-I/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119/lib/5.37.2/x86_64-linux-thread-multi/CORE"   Proctitle.c
In file included from Proctitle.xs:2:
Proctitle.xs: In function ‘XS_Sys__Proctitle_kernel_support’:
/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119/lib/5.37.2/x86_64-linux-thread-multi/CORE/perl.h:885:23: error: expected expression before ‘do’
  885 | #   define STMT_START do
      |                       ^~
/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119/lib/5.37.2/x86_64-linux-thread-multi/CORE/XSUB.h:338:24: note: in expansion of macro ‘STMT_START’
  338 | #define XSRETURN_YES   STMT_START { XST_mYES(0);   XSRETURN(1); } STMT_END
      |                        ^~~~~~~~~~
Proctitle.xs:71:36: note: in expansion of macro ‘XSRETURN_YES’
   71 |       proctitle_kernel_support() ? XSRETURN_YES : XSRETURN_EMPTY;
      |                                    ^~~~~~~~~~~~
make: *** [Makefile:341: Proctitle.o] Error 1
```

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 37 subversion 2) configuration:
  Commit id: 7f9b65d969a1c8b44028cacbb9e88596d1e5a8a3
  Platform:
    osname=linux
    osvers=5.4.0-122-generic
    archname=x86_64-linux-thread-multi
    uname='linux k93focal 5.4.0-122-generic #138-ubuntu smp wed jun 22 15:00:31 utc 2022 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119 -Dmyhostname=k93focal -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Uuselongdouble -DEBUGGING=both'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Jul 30 2022 05:44:13
  %ENV:
    PERL="/tmp/basesmoker-reloperl-1mEb/bin/perl"
    PERL5LIB="/tmp/loop_over_bdir-3589605-XjwJT5/downsexta-0/blib/arch:/tmp/loop_over_bdir-3589605-XjwJT5/downsexta-0/blib/lib:/tmp/loop_over_bdir-3589605-XjwJT5/Lingua-YaTeA-0.626-0/blib/arch:/tmp/loop_over_bdir-3589605-XjwJT5/Lingua-YaTeA-0.626-0/blib/lib:/tmp/loop_over_bdir-3589605-XjwJT5/App-nrun-v1.1.2-0/blib/arch:/tmp/loop_over_bdir-3589605-XjwJT5/App-nrun-v1.1.2-0/blib/lib:/tmp/loop_over_bdir-3589605-XjwJT5/Devel-Required-0.16-0/blib/arch:/tmp/loop_over_bdir-3589605-XjwJT5/Devel-Required-0.16-0/blib/lib:/tmp/loop_over_bdir-3589605-XjwJT5/Net-ISP-Balance-1.31-0/blib/arch:/tmp/loop_over_bdir-3589605-XjwJT5/Net-ISP-Balance-1.31-0/blib/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="3589613"
    PERL5_CPAN_IS_RUNNING="3589613"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /tmp/loop_over_bdir-3589605-XjwJT5/downsexta-0/blib/arch
    /tmp/loop_over_bdir-3589605-XjwJT5/downsexta-0/blib/lib
    /tmp/loop_over_bdir-3589605-XjwJT5/Lingua-YaTeA-0.626-0/blib/arch
    /tmp/loop_over_bdir-3589605-XjwJT5/Lingua-YaTeA-0.626-0/blib/lib
    /tmp/loop_over_bdir-3589605-XjwJT5/App-nrun-v1.1.2-0/blib/arch
    /tmp/loop_over_bdir-3589605-XjwJT5/App-nrun-v1.1.2-0/blib/lib
    /tmp/loop_over_bdir-3589605-XjwJT5/Devel-Required-0.16-0/blib/arch
    /tmp/loop_over_bdir-3589605-XjwJT5/Devel-Required-0.16-0/blib/lib
    /tmp/loop_over_bdir-3589605-XjwJT5/Net-ISP-Balance-1.31-0/blib/arch
    /tmp/loop_over_bdir-3589605-XjwJT5/Net-ISP-Balance-1.31-0/blib/lib
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119/lib/site_perl/5.37.2/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119/lib/site_perl/5.37.2
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119/lib/5.37.2/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.2/d119/lib/5.37.2
    .
```

**Comment by jkeenan** [comment] 2022-08-13 22:16
> 
> With `v5.35.1-108-g7169efc775` the cpan pkg `OPI/Sys-Proctitle-0.04.tar.gz` stopped compiling on all of my smokers. Bisect lead me to:
> 
> ```
>  commit 7169efc77525df70484a824bff4ceebd1fafc760
>  Author: Tony Cook <tony@develop-help.com>
>  Date:   Thu Jul 15 13:13:03 2021 +1000
>  
>      skip using gcc brace groups for STMT_START/END
> ```
> 

Bisecting with this invocation:
```
perl Porting/bisect.pl  \
--start=v5.37.1 \
--end=v5.37.2 \
--module Sys::Proctitle
```
... I confirmed that this occurred in the last dev cycle:
```
7169efc77525df70484a824bff4ceebd1fafc760 is the first bad commit
commit 7169efc77525df70484a824bff4ceebd1fafc760
Author: Tony Cook <tony@develop-help.com>
Date:   Thu Jul 15 13:13:03 2021 +1000
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Thu Jul 15 13:13:03 2021 +1000


    skip using gcc brace groups for STMT_START/END
```
@tonycoz, can you take a look?

**Comment by jkeenan** [comment] 2022-08-13 23:07
If someone could review this patch I submitted upstream ...
https://rt.cpan.org/Ticket/Display.html?id=144009#txn-2313057
... then perhaps we could dispose of this issue quickly.

**Comment by Leont** [comment] 2022-08-14 01:08
That code would have failed on non-GCC previously already, so a change in the module is appropriate.

> If someone could review this patch I submitted upstream ...

Patch looks correct to me.

**Comment by jkeenan** [comment] 2022-08-20 12:40
I think we can close this ticket.  CPAN library Sys-Proctitle (which is Linux-only) has not been updated since [2010](https://metacpan.org/dist/Sys-Proctitle/changes).  On CPANtesters, it's getting panics on older versions of perl (see, *e.g.,* [this report](http://www.cpantesters.org/cpan/report/40f8e074-ce91-11e7-9ef3-8859389b4f94)) which have not been addressed for years.  I suspect the library is abandonware.  If and when someone resumes maintenance, that person can evaluate the patch I submitted.

I will self-assign this ticket for the purpose of closing it in 7 days unless someone objects and wants to take the discussion further.

**Comment by jkeenan** [comment] 2022-08-29 14:18
> I think we can close this ticket. CPAN library Sys-Proctitle (which is Linux-only) has not been updated since [2010](https://metacpan.org/dist/Sys-Proctitle/changes). On CPANtesters, it's getting panics on older versions of perl (see, _e.g.,_ [this report](http://www.cpantesters.org/cpan/report/40f8e074-ce91-11e7-9ef3-8859389b4f94)) which have not been addressed for years. I suspect the library is abandonware. If and when someone resumes maintenance, that person can evaluate the patch I submitted.
> 
> I will self-assign this ticket for the purpose of closing it in 7 days unless someone objects and wants to take the discussion further.

No one has objected to closing this ticket.  Closing now.

**Closed as completed by jkeenan** 2022-08-29 14:18 UTC
Labels: BBC
