### ISSUE TITLE
BBC: Blead Breaks XS::Parse::Sublike

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#18459] opened 2021-01-06 20:58 UTC
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.33.6.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks XS::Parse::Sublike

Please see http://matrix.cpantesters.org/?dist=XS-Parse-Sublike

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.33.6:

Configured by cpan at Wed Jan  6 12:42:07 EST 2021.

Summary of my perl5 (revision 5 version 33 subversion 6) configuration:
  Commit id: 64a5950af609117d2098f7616334aff77df9ed63
  Platform:
    osname=openbsd
    osvers=6.8
    archname=OpenBSD.amd64-openbsd
    uname='openbsd cjg-openbsd6 6.8 generic#2 amd64 '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    optimize='-O2'
    cppflags='-fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='OpenBSD Clang 10.0.1 '
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-Wl,-E  -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lpthread -lm -lutil -lc
    perllibs=-lpthread -lm -lutil -lc
    libc=/usr/lib/libc.so.96.0
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags='-DPIC -fPIC '
    lddlflags='-shared -fPIC  -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.33.6:
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.6/OpenBSD.amd64-openbsd
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.6
    /home/cpan/bin/perl-blead/lib/5.33.6/OpenBSD.amd64-openbsd
    /home/cpan/bin/perl-blead/lib/5.33.6

---
Environment for perl 5.33.6:
    HOME=/home/cpan
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/home/cpan/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

**Comment by tonycoz** [comment] 2021-01-07 03:36
Caused by 0f14f058b16bfb27c6240d4ea745a895c7e6dd28, since the error message changed (in a good way), @leonerd will need to adapt XS::Parse::Sublike to the new message

**Comment by tonycoz** [comment] 2021-01-07 03:43
Reported as https://rt.cpan.org/Ticket/Display.html?id=134012 and closing.

**Closed as completed by tonycoz** 2021-01-07 03:43 UTC

**Comment by tonycoz** [comment] 2021-01-18 21:32
Fixed the 0.11 release of XS::Parse::Sublike
