### ISSUE TITLE
Give Wrong Output 

### ISSUE THREAD

**Issue by kkshitish** [Perl/perl5#18648] opened 2021-03-17 06:40 UTC
$a = 10;
$b = 11;

if ($a <=> $b && $a .. $b) {
 
    print "Yes";
   
} else {
    
    print "No";
}

Output: Yes

Bug: This code should print "No"; But it print "Yes";

**Comment by reneeb** [comment] 2021-03-17 08:03
Why do you think this is wrong? What do you think happens here?

Maybe B::Deparse helps:

```
> perl -MO=Deparse,-p -e '$a = 10;
$b = 11;
                                         
if ($a <=> $b && $a .. $b) {
 
    print "Yes";
   
} else {
    
    print "No";
}'


($a = 10);
($b = 11);
if (((($a <=> $b) && $a) .. $b)) {
    print('Yes');
}
else {
    print('No');
}
-e syntax OK
```

So, the if-condition looks like `(($a <=> $b) && $a) .. $b`. The first condition is `$a <=> $b` (10 <=> 11), which is `-1`, which is _true_ . So, the next condition is `(-1) && 10`, which is 10 and hence it is _true_ . And then you have the range `10 .. 11`, which is _true_ .

**Comment by rwp0** [comment] 2021-03-17 10:06
conclusion: in Perl `-1` is **[true](https://perldoc.perl.org/perldata#Scalar-values)** (while `0`, `''`, `undef()` are not, and unfortunately, a separate boolean type is missing)

note: parenthesize range operator operands `a .. b` (for correct priority/[precedence](https://perldoc.perl.org/perlop#Operator-Precedence-and-Associativity))

thanks: @reneeb, and [B::Deparse](https://perldoc.perl.org/B::Deparse) for explanation, and explicitness

**Comment by rsFalse** [comment] 2021-03-17 13:08
Although `perldoc` says that `..` is range operator in any context, more explicitly saying it is `flip-flop` operator in this case, because `if` forces its conditional to be evaluated in scalar context.

**Comment by jkeenan** [comment] 2021-03-22 22:25
Not a bug.  Closing.

**Closed as completed by jkeenan** 2021-03-22 22:25 UTC
